var searchData=
[
  ['p_20convexity_0',['Digital convexity, full convexity and P-convexity',['../moduleDigitalConvexity.html',1,'packageGeometry']]],
  ['package_1',['package',['../packageArithmetic.html',1,'Arithmetic package'],['../packageBase.html',1,'Base package'],['../packageDEC.html',1,'DEC package'],['../packageGeometry.html',1,'Geometry package'],['../packageGraph.html',1,'Graph package'],['../packageImage.html',1,'Image package'],['../packageIO.html',1,'IO package'],['../packageKernel.html',1,'Kernel package'],['../packageMath.html',1,'Mathematical package'],['../packageShapes.html',1,'Shapes package'],['../packageTopology.html',1,'Topology package']]],
  ['parameter_20passing_20cloning_20and_20referencing_2',['Parameter passing, cloning and referencing',['../moduleCloneAndReference.html',1,'packageBase']]],
  ['parametric_20curves_3',['Digitization of 3D parametric curves',['../moduleParametricCurves.html',1,'packageGeometry']]],
  ['part_20i_20models_20of_20graph_4',['Topology Concepts and Models (part I, models of graph)',['../packageTopologyConcepts1.html',1,'packageTopology']]],
  ['part_20ii_20digital_20surfaces_20surfel_20predicates_5',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['../packageTopologyConcepts2.html',1,'packageTopology']]],
  ['passing_20cloning_20and_20referencing_6',['Parameter passing, cloning and referencing',['../moduleCloneAndReference.html',1,'packageBase']]],
  ['patterns_20digital_20straight_20lines_20and_20subsegments_7',['Patterns, digital straight lines and subsegments',['../moduleDigitalStraightness.html',1,'packageArithmetic']]],
  ['patterntriangulation_8',['patternTriangulation',['http://dgtal.org/doc/tools/nightly/patternTriangulation.html',1,'']]],
  ['piecewise_20smooth_20approximation_20using_20a_20discrete_20calculus_20model_20of_20ambrosio_20tortorelli_20functional_9',['Piecewise-smooth approximation using a discrete calculus model of Ambrosio-Tortorelli functional',['../moduleGenericAT.html',1,'packageDEC']]],
  ['plane_10',['Convex hull and alpha-shape in the plane',['../moduleHull2D.html',1,'packageGeometry']]],
  ['plane_20probing_20based_20normal_20estimators_11',['Plane-probing based normal estimators',['../modulePlaneProbing.html',1,'packageGeometry']]],
  ['plane_20recognition_20algorithm_12',['Detailed explanation of COBA plane recognition algorithm',['../moduleCOBANaivePlaneRecognition.html',1,'packageGeometry']]],
  ['plane_20recognition_20and_20plane_20width_20computation_13',['Plane recognition and plane width computation',['../modulePlaneRecognition.html',1,'packageGeometry']]],
  ['plane_20zxz_20convex_20polygons_20with_20vertices_20at_20integer_20coordinates_14',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['../moduleLatticePolytope2D.html',1,'packageArithmetic']]],
  ['point_20cloud_15',['Voxelization from an oriented point cloud',['../moduleWinding.html',1,'packageShapes']]],
  ['points_20in_20digital_20spaces_16',['Sets of points in digital spaces',['../moduleDigitalSets.html',1,'packageKernel']]],
  ['points_20vectors_20and_20domains_17',['Digital Spaces, Points, Vectors and Domains',['../moduleSpacePointVectorDomain.html',1,'packageKernel']]],
  ['poisson_20problem_18',['Poisson problem',['../moduleDECPoisson.html',1,'packageDEC']]],
  ['polygonal_20calculus_19',['polygonal calculus',['../moduleGeodesicsInHeat.html',1,'Geodesics In Heat using discrete polygonal calculus'],['../moduleVectorsInHeat.html',1,'Vector Heat Method using discrete polygonal calculus']]],
  ['polygonal_20surfaces_20',['polygonal surfaces',['../modulePolygonalCalculus.html',1,'Discrete differential calculus on polygonal surfaces'],['../moduleHalfEdgeMesh.html',1,'Half-edge data structure, triangulated surfaces and polygonal surfaces']]],
  ['polygonal_20surfaces_20in_20r3_21',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['polygons_20with_20vertices_20at_20integer_20coordinates_22',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['../moduleLatticePolytope2D.html',1,'packageArithmetic']]],
  ['polyhedra_23',['Fully convex envelope, relative fully convex envelope and digital polyhedra',['../moduleEnvelope.html',1,'packageGeometry']]],
  ['polyhedron_20from_20a_20digital_20object_24',['Tutorial: making a polyhedron from a digital object',['../tutoPolyhedralisation.html',1,'packageTutorials']]],
  ['polynomials_25',['Multivariate polynomials',['../modulePolynomial.html',1,'packageMath']]],
  ['polytopes_20in_20the_20digital_20plane_20zxz_20convex_20polygons_20with_20vertices_20at_20integer_20coordinates_26',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['../moduleLatticePolytope2D.html',1,'packageArithmetic']]],
  ['predicates_27',['predicates',['../moduleGeometricPredicates.html',1,'Implementation of geometric predicates'],['../packageTopologyConcepts2.html',1,'Topology Concepts and Models (part II, digital surfaces, surfel predicates)']]],
  ['probing_20based_20normal_20estimators_28',['Plane-probing based normal estimators',['../modulePlaneProbing.html',1,'packageGeometry']]],
  ['problem_29',['Poisson problem',['../moduleDECPoisson.html',1,'packageDEC']]],
  ['processes_30',['nD Volumetric Analysis using Separable Processes',['../moduleVolumetric.html',1,'packageGeometry']]],
  ['processing_31',['Image processing',['http://dgtal.org/doc/tools/nightly/imageProcessing.html',1,'']]],
  ['project_32',['How to use DGtal in my own project ?',['../moduleHowToUseDGtal.html',1,'packageIntroduction']]],
  ['propagation_33',['Propagation',['../moduleDECPropagation.html',1,'packageDEC']]],
  ['python_20binding_34',['DGtal python binding',['../packagePython.html',1,'packageIntroduction']]]
];
