var searchData=
[
  ['m_20dimensional_20space_0',['Embedding n-dimensional DEC structures into m-dimensional space',['../moduleDECEmbedding.html',1,'packageDEC']]],
  ['main_20concepts_1',['main concepts',['../packageDECConcepts.html',1,'DEC Main Concepts'],['../packageGraphConcepts.html',1,'Graph Main Concepts'],['../packageMathConcepts.html',1,'Math Main Concepts']]],
  ['main_20image_20concepts_2',['Main Image Concepts',['../packageImageConcepts.html',1,'packageImage']]],
  ['making_20a_20polyhedron_20from_20a_20digital_20object_3',['Tutorial: making a polyhedron from a digital object',['../tutoPolyhedralisation.html',1,'packageTutorials']]],
  ['management_20in_20dgtal_4',['Git/Github source code management in DGtal',['../moduleFAQGit.html',1,'packageDev']]],
  ['manifold_20or_20non_20manifold_20polygonal_20surfaces_20in_20r3_5',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['manipulating_20simple_20mesh_6',['Manipulating Simple Mesh',['../moduleMesh.html',1,'packageShapes']]],
  ['manipulations_7',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['../tutoImageManipulations.html',1,'packageTutorials']]],
  ['marching_20method_8',['Tutorial: Local morphological opening of a 3d volume by the Fast Marching Method',['../tutoFMMErosion.html',1,'packageTutorials']]],
  ['marching_20methods_9',['nD Fast Marching Methods',['../moduleFMM.html',1,'packageGeometry']]],
  ['math_20main_20concepts_10',['Math Main Concepts',['../packageMathConcepts.html',1,'packageMath']]],
  ['mathematical_20package_11',['Mathematical package',['../packageMath.html',1,'index']]],
  ['maximal_20segments_20and_20slices_20of_20digital_20surface_20based_20normal_20estimator_12',['Maximal segments and slices of digital surface based normal estimator',['../moduleMaximalSegmentSliceEstimation.html',1,'packageGeometry']]],
  ['measure_20and_20geometry_20estimation_13',['Digital Voronoi Covariance Measure and geometry estimation',['../moduleVCM.html',1,'packageGeometry']]],
  ['measures_20on_20meshes_20and_20digital_20surfaces_14',['Curvature measures on meshes and digital surfaces',['../moduleCurvatureMeasures.html',1,'packageGeometry']]],
  ['mechanism_15',['Limited interaction when using selection with QGLViewer Viewer3D stream mechanism',['../moduleQGLInteraction.html',1,'packageIO']]],
  ['mechanism_20for_20displaying_202d_20digital_20objects_16',['Board2D: a stream mechanism for displaying 2D digital objects',['../moduleBoard2D.html',1,'packageIO']]],
  ['mechanism_20for_20displaying_203d_20dgtal_20objects_17',['Display3D: a stream mechanism for displaying 3D DGtal objects',['../moduleDisplay3D.html',1,'packageIO']]],
  ['mesh_18',['Manipulating Simple Mesh',['../moduleMesh.html',1,'packageShapes']]],
  ['mesh_20data_20structure_20for_20representing_20manifold_20or_20non_20manifold_20polygonal_20surfaces_20in_20r3_19',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['mesh_20voxelization_20',['Mesh Voxelization',['../moduleMeshVoxelization.html',1,'packageShapes']]],
  ['mesh2heightfield_21',['mesh2heightfield',['http://dgtal.org/doc/tools/nightly/mesh2heightfield.html',1,'']]],
  ['meshes_20and_20digital_20surfaces_22',['Curvature measures on meshes and digital surfaces',['../moduleCurvatureMeasures.html',1,'packageGeometry']]],
  ['meshviewer_23',['meshViewer',['http://dgtal.org/doc/tools/nightly/meshViewer.html',1,'']]],
  ['method_24',['Tutorial: Local morphological opening of a 3d volume by the Fast Marching Method',['../tutoFMMErosion.html',1,'packageTutorials']]],
  ['method_20using_20discrete_20polygonal_20calculus_25',['Vector Heat Method using discrete polygonal calculus',['../moduleVectorsInHeat.html',1,'packageDEC']]],
  ['methods_26',['nD Fast Marching Methods',['../moduleFMM.html',1,'packageGeometry']]],
  ['metric_20spaces_20digital_20metric_20spaces_20and_20related_20concepts_27',['Metric Spaces, Digital Metric Spaces and Related Concepts',['../moduleMetrics.html',1,'packageGeometry']]],
  ['model_20of_20ambrosio_20tortorelli_20functional_28',['Piecewise-smooth approximation using a discrete calculus model of Ambrosio-Tortorelli functional',['../moduleGenericAT.html',1,'packageDEC']]],
  ['models_29',['Arithmetic Concepts and Models',['../packageArithmeticConcepts.html',1,'packageArithmetic']]],
  ['models_20part_20i_20models_20of_20graph_30',['Topology Concepts and Models (part I, models of graph)',['../packageTopologyConcepts1.html',1,'packageTopology']]],
  ['models_20part_20ii_20digital_20surfaces_20surfel_20predicates_31',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['../packageTopologyConcepts2.html',1,'packageTopology']]],
  ['morphological_20opening_20of_20a_203d_20volume_20by_20the_20fast_20marching_20method_32',['Tutorial: Local morphological opening of a 3d volume by the Fast Marching Method',['../tutoFMMErosion.html',1,'packageTutorials']]],
  ['multivariate_20polynomials_33',['Multivariate polynomials',['../modulePolynomial.html',1,'packageMath']]],
  ['my_20own_20project_34',['How to use DGtal in my own project ?',['../moduleHowToUseDGtal.html',1,'packageIntroduction']]]
];
