var searchData=
[
  ['sdp2vol_0',['sdp2vol',['http://dgtal.org/doc/tools/nightly/sdp2vol.html',1,'']]],
  ['segment_20recognition_20br_1',['Alpha-thick Segment Recognition   &lt;br&gt;',['../moduleAlphaThickSegmentReco.html',1,'packageGeometry']]],
  ['segments_20and_20slices_20of_20digital_20surface_20based_20normal_20estimator_2',['Maximal segments and slices of digital surface based normal estimator',['../moduleMaximalSegmentSliceEstimation.html',1,'packageGeometry']]],
  ['segments_20br_3',['Digital straight lines and segments   &lt;br&gt;',['../moduleArithDSSReco.html',1,'packageGeometry']]],
  ['selection_20with_20qglviewer_20viewer3d_20stream_20mechanism_4',['Limited interaction when using selection with QGLViewer Viewer3D stream mechanism',['../moduleQGLInteraction.html',1,'packageIO']]],
  ['separable_20processes_5',['nD Volumetric Analysis using Separable Processes',['../moduleVolumetric.html',1,'packageGeometry']]],
  ['set_20boundary_20from_20image_6',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt;  Extracting level set boundary from Image&quot;',['../tutoImageGridCurveExtraction.html',1,'packageTutorials']]],
  ['set_20operations_20on_20arbitrary_20containers_7',['Set operations on arbitrary containers',['../moduleSetFunctions.html',1,'packageBase']]],
  ['sets_20of_20points_20in_20digital_20spaces_8',['Sets of points in digital spaces',['../moduleDigitalSets.html',1,'packageKernel']]],
  ['shape_20grid_20curve_20length_20estimation_9',['Tutorial &quot;Generated shape -&gt; Grid curve -&gt; Length estimation&quot;',['../tutoShapeGridCurveEstimator.html',1,'packageTutorials']]],
  ['shape_20in_20the_20plane_10',['Convex hull and alpha-shape in the plane',['../moduleHull2D.html',1,'packageGeometry']]],
  ['shapegenerator_11',['shapeGenerator',['http://dgtal.org/doc/tools/nightly/shapeGenerator.html',1,'']]],
  ['shapers_20and_20digitizers_12',['Shapes, Shapers and Digitizers',['../moduleShape.html',1,'packageShapes']]],
  ['shapes_20concepts_13',['Shapes Concepts',['../packageShapesConcepts.html',1,'packageShapes']]],
  ['shapes_20package_14',['Shapes package',['../packageShapes.html',1,'index']]],
  ['shapes_20shapers_20and_20digitizers_15',['Shapes, Shapers and Digitizers',['../moduleShape.html',1,'packageShapes']]],
  ['shortcuts_16',['Fréchet Shortcuts',['../moduleFrechetShortcut.html',1,'packageGeometry']]],
  ['shortcuts_20for_20the_20impatient_20developper_17',['Shortcuts (for the impatient developper)',['../moduleShortcuts.html',1,'index']]],
  ['shrouds_20algorithm_18',['Digital surface regularization using the Shrouds algorithm',['../moduleShrouds.html',1,'packageGeometry']]],
  ['simple_203d_20volume_20viewer_20in_20less_20than_2050_20lines_19',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['../tutoImageGridVolume3dVolViewer.html',1,'packageTutorials']]],
  ['simple_20image_20manipulations_20',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['../tutoImageManipulations.html',1,'packageTutorials']]],
  ['simple_20mesh_21',['Manipulating Simple Mesh',['../moduleMesh.html',1,'packageShapes']]],
  ['slice2vol_22',['slice2vol',['http://dgtal.org/doc/tools/nightly/slice2vol.html',1,'']]],
  ['slices_20of_20digital_20surface_20based_20normal_20estimator_23',['Maximal segments and slices of digital surface based normal estimator',['../moduleMaximalSegmentSliceEstimation.html',1,'packageGeometry']]],
  ['sliceviewer_24',['sliceViewer',['http://dgtal.org/doc/tools/nightly/sliceViewer.html',1,'']]],
  ['smooth_20approximation_20using_20a_20discrete_20calculus_20model_20of_20ambrosio_20tortorelli_20functional_25',['Piecewise-smooth approximation using a discrete calculus model of Ambrosio-Tortorelli functional',['../moduleGenericAT.html',1,'packageDEC']]],
  ['some_20simple_20image_20manipulations_26',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['../tutoImageManipulations.html',1,'packageTutorials']]],
  ['source_20code_20management_20in_20dgtal_27',['Git/Github source code management in DGtal',['../moduleFAQGit.html',1,'packageDev']]],
  ['space_28',['Embedding n-dimensional DEC structures into m-dimensional space',['../moduleDECEmbedding.html',1,'packageDEC']]],
  ['space_20and_20topology_20unoriented_20and_20oriented_20cells_20incidence_29',['Cellular grid space and topology, unoriented and oriented cells, incidence',['../moduleCellularTopology.html',1,'packageTopology']]],
  ['spaces_30',['Sets of points in digital spaces',['../moduleDigitalSets.html',1,'packageKernel']]],
  ['spaces_20digital_20metric_20spaces_20and_20related_20concepts_31',['Metric Spaces, Digital Metric Spaces and Related Concepts',['../moduleMetrics.html',1,'packageGeometry']]],
  ['spaces_20points_20vectors_20and_20domains_32',['Digital Spaces, Points, Vectors and Domains',['../moduleSpacePointVectorDomain.html',1,'packageKernel']]],
  ['started_33',['Getting started',['../packageIntroduction.html',1,'index']]],
  ['statisticsestimators_34',['statisticsEstimators',['http://dgtal.org/doc/tools/nightly/statisticsEstimators.html',1,'']]],
  ['straight_20lines_20and_20segments_20br_35',['Digital straight lines and segments   &lt;br&gt;',['../moduleArithDSSReco.html',1,'packageGeometry']]],
  ['straight_20lines_20and_20subsegments_36',['Patterns, digital straight lines and subsegments',['../moduleDigitalStraightness.html',1,'packageArithmetic']]],
  ['stream_20mechanism_37',['Limited interaction when using selection with QGLViewer Viewer3D stream mechanism',['../moduleQGLInteraction.html',1,'packageIO']]],
  ['stream_20mechanism_20for_20displaying_202d_20digital_20objects_38',['Board2D: a stream mechanism for displaying 2D digital objects',['../moduleBoard2D.html',1,'packageIO']]],
  ['stream_20mechanism_20for_20displaying_203d_20dgtal_20objects_39',['Display3D: a stream mechanism for displaying 3D DGtal objects',['../moduleDisplay3D.html',1,'packageIO']]],
  ['structure_20for_20representing_20manifold_20or_20non_20manifold_20polygonal_20surfaces_20in_20r3_40',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['structure_20triangulated_20surfaces_20and_20polygonal_20surfaces_41',['Half-edge data structure, triangulated surfaces and polygonal surfaces',['../moduleHalfEdgeMesh.html',1,'packageTopology']]],
  ['structures_42',['Analysis of one-dimensional discrete structures',['../moduleGridCurveAnalysis.html',1,'packageGeometry']]],
  ['structures_20into_20m_20dimensional_20space_43',['Embedding n-dimensional DEC structures into m-dimensional space',['../moduleDECEmbedding.html',1,'packageDEC']]],
  ['subsegments_44',['Patterns, digital straight lines and subsegments',['../moduleDigitalStraightness.html',1,'packageArithmetic']]],
  ['surface_20area_20estimation_45',['Tutorial: Surface area estimation',['../tutoAreaSurface.html',1,'packageTutorials']]],
  ['surface_20based_20normal_20estimator_46',['Maximal segments and slices of digital surface based normal estimator',['../moduleMaximalSegmentSliceEstimation.html',1,'packageGeometry']]],
  ['surface_20estimators_20from_20surfel_20functors_47',['Local digital surface estimators from surfel functors',['../LocalEstimatorsFromSurfel.html',1,'packageGeometry']]],
  ['surface_20mesh_20data_20structure_20for_20representing_20manifold_20or_20non_20manifold_20polygonal_20surfaces_20in_20r3_48',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['surface_20regularization_20by_20normal_20vector_20alignment_49',['Digital surface regularization by normal vector alignment',['../moduleRegularization.html',1,'packageGeometry']]],
  ['surface_20regularization_20using_20the_20shrouds_20algorithm_50',['Digital surface regularization using the Shrouds algorithm',['../moduleShrouds.html',1,'packageGeometry']]],
  ['surfaces_51',['surfaces',['../moduleCurvatureMeasures.html',1,'Curvature measures on meshes and digital surfaces'],['../moduleDigitalSurfaces.html',1,'Digital surfaces'],['../modulePolygonalCalculus.html',1,'Discrete differential calculus on polygonal surfaces'],['../moduleDigitalSurfaceHelpers.html',1,'Helpers for digital surfaces']]],
  ['surfaces_20and_20polygonal_20surfaces_52',['Half-edge data structure, triangulated surfaces and polygonal surfaces',['../moduleHalfEdgeMesh.html',1,'packageTopology']]],
  ['surfaces_20in_20r3_53',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['surfaces_20surfel_20predicates_54',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['../packageTopologyConcepts2.html',1,'packageTopology']]],
  ['surfel_20functors_55',['Local digital surface estimators from surfel functors',['../LocalEstimatorsFromSurfel.html',1,'packageGeometry']]],
  ['surfel_20predicates_56',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['../packageTopologyConcepts2.html',1,'packageTopology']]]
];
