var searchData=
[
  ['pair1st_9489',['Pair1st',['../classDGtal_1_1functors_1_1Pair1st.html',1,'DGtal::functors']]],
  ['pair1st_3c_20point_20_3e_9490',['Pair1st&lt; Point &gt;',['../classDGtal_1_1functors_1_1Pair1st.html',1,'DGtal::functors']]],
  ['pair1stmutator_9491',['Pair1stMutator',['../classDGtal_1_1functors_1_1Pair1stMutator.html',1,'DGtal::functors']]],
  ['pair2nd_9492',['Pair2nd',['../classDGtal_1_1functors_1_1Pair2nd.html',1,'DGtal::functors']]],
  ['pair2ndmutator_9493',['Pair2ndMutator',['../classDGtal_1_1functors_1_1Pair2ndMutator.html',1,'DGtal::functors']]],
  ['pairassociativecategory_9494',['PairAssociativeCategory',['../structDGtal_1_1PairAssociativeCategory.html',1,'DGtal']]],
  ['pairassociativecontainer_9495',['PairAssociativeContainer',['../structboost_1_1PairAssociativeContainer.html',1,'boost']]],
  ['parallelstrip_9496',['ParallelStrip',['../classDGtal_1_1ParallelStrip.html',1,'DGtal']]],
  ['parameters_9497',['Parameters',['../structDGtal_1_1Parameters.html',1,'DGtal']]],
  ['parametervalue_9498',['ParameterValue',['../structDGtal_1_1ParameterValue.html',1,'DGtal']]],
  ['parametricshapearclengthfunctor_9499',['ParametricShapeArcLengthFunctor',['../classDGtal_1_1ParametricShapeArcLengthFunctor.html',1,'DGtal']]],
  ['parametricshapecurvaturefunctor_9500',['ParametricShapeCurvatureFunctor',['../classDGtal_1_1ParametricShapeCurvatureFunctor.html',1,'DGtal']]],
  ['parametricshapetangentfunctor_9501',['ParametricShapeTangentFunctor',['../classDGtal_1_1ParametricShapeTangentFunctor.html',1,'DGtal']]],
  ['pardircollapse_9502',['ParDirCollapse',['../classDGtal_1_1ParDirCollapse.html',1,'DGtal']]],
  ['patatepoint_9503',['PatatePoint',['../classDGtal_1_1functors_1_1SphereFittingEstimator_1_1PatatePoint.html',1,'DGtal::functors::SphereFittingEstimator']]],
  ['path_9504',['Path',['../structLibBoard_1_1Path.html',1,'LibBoard']]],
  ['pattern_9505',['Pattern',['../classDGtal_1_1Pattern.html',1,'DGtal']]],
  ['pattern_3c_20fraction_20_3e_9506',['Pattern&lt; Fraction &gt;',['../classDGtal_1_1Pattern.html',1,'DGtal']]],
  ['pconvexity_9507',['PConvexity',['../classDGtal_1_1PConvexity.html',1,'DGtal']]],
  ['pgmreader_9508',['PGMReader',['../structDGtal_1_1PGMReader.html',1,'DGtal']]],
  ['pgmwriter_9509',['PGMWriter',['../structDGtal_1_1PGMWriter.html',1,'DGtal']]],
  ['planeprobingdigitalsurfacelocalestimator_9510',['PlaneProbingDigitalSurfaceLocalEstimator',['../classDGtal_1_1PlaneProbingDigitalSurfaceLocalEstimator.html',1,'DGtal']]],
  ['planeprobinghneighborhood_9511',['PlaneProbingHNeighborhood',['../classDGtal_1_1PlaneProbingHNeighborhood.html',1,'DGtal']]],
  ['planeprobinglneighborhood_9512',['PlaneProbingLNeighborhood',['../classDGtal_1_1PlaneProbingLNeighborhood.html',1,'DGtal']]],
  ['planeprobingneighborhood_9513',['PlaneProbingNeighborhood',['../classDGtal_1_1PlaneProbingNeighborhood.html',1,'DGtal']]],
  ['planeprobingparallelepipedestimator_9514',['PlaneProbingParallelepipedEstimator',['../classDGtal_1_1PlaneProbingParallelepipedEstimator.html',1,'DGtal']]],
  ['planeprobingr1neighborhood_9515',['PlaneProbingR1Neighborhood',['../classDGtal_1_1PlaneProbingR1Neighborhood.html',1,'DGtal']]],
  ['planeprobingrneighborhood_9516',['PlaneProbingRNeighborhood',['../classDGtal_1_1PlaneProbingRNeighborhood.html',1,'DGtal']]],
  ['planeprobingtetrahedronestimator_9517',['PlaneProbingTetrahedronEstimator',['../classDGtal_1_1PlaneProbingTetrahedronEstimator.html',1,'DGtal']]],
  ['planeprobingtetrahedronestimator_3c_20notabovepredicate_2c_20mode_20_3e_9518',['PlaneProbingTetrahedronEstimator&lt; NotAbovePredicate, mode &gt;',['../classDGtal_1_1PlaneProbingTetrahedronEstimator.html',1,'DGtal']]],
  ['point_9519',['Point',['../structLibBoard_1_1Point.html',1,'LibBoard']]],
  ['point2dembedderin3d_9520',['Point2DEmbedderIn3D',['../classDGtal_1_1functors_1_1Point2DEmbedderIn3D.html',1,'DGtal::functors']]],
  ['point2shapepredicate_9521',['Point2ShapePredicate',['../classDGtal_1_1functors_1_1Point2ShapePredicate.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_9522',['Point2ShapePredicateComparator',['../structDGtal_1_1functors_1_1Point2ShapePredicateComparator.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20false_2c_20false_20_3e_9523',['Point2ShapePredicateComparator&lt; T, false, false &gt;',['../structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01false_00_01false_01_4.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20false_2c_20true_20_3e_9524',['Point2ShapePredicateComparator&lt; T, false, true &gt;',['../structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01false_00_01true_01_4.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20true_2c_20false_20_3e_9525',['Point2ShapePredicateComparator&lt; T, true, false &gt;',['../structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01true_00_01false_01_4.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20true_2c_20true_20_3e_9526',['Point2ShapePredicateComparator&lt; T, true, true &gt;',['../structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01true_00_01true_01_4.html',1,'DGtal::functors']]],
  ['pointfunctorfrompointpredicateanddomain_9527',['PointFunctorFromPointPredicateAndDomain',['../structDGtal_1_1functors_1_1PointFunctorFromPointPredicateAndDomain.html',1,'DGtal::functors']]],
  ['pointfunctorholder_9528',['PointFunctorHolder',['../classDGtal_1_1functors_1_1PointFunctorHolder.html',1,'DGtal::functors']]],
  ['pointfunctorpredicate_9529',['PointFunctorPredicate',['../structDGtal_1_1functors_1_1PointFunctorPredicate.html',1,'DGtal::functors']]],
  ['pointlistreader_9530',['PointListReader',['../structDGtal_1_1PointListReader.html',1,'DGtal']]],
  ['pointonprobingray_9531',['PointOnProbingRay',['../classDGtal_1_1detail_1_1PointOnProbingRay.html',1,'DGtal::detail']]],
  ['pointvaluecompare_9532',['PointValueCompare',['../classDGtal_1_1detail_1_1PointValueCompare.html',1,'DGtal::detail']]],
  ['pointvector_9533',['PointVector',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_202_2c_20double_20_3e_9534',['PointVector&lt; 2, double &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_202_2c_20integer_20_3e_9535',['PointVector&lt; 2, Integer &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_203_2c_20double_20_3e_9536',['PointVector&lt; 3, double &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_203_2c_20internalinteger_20_3e_9537',['PointVector&lt; 3, InternalInteger &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_203_2c_20internalscalar_20_3e_9538',['PointVector&lt; 3, InternalScalar &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_20dim_2c_20integer_20_3e_9539',['PointVector&lt; dim, Integer &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_20dim_2c_20internalinteger_20_3e_9540',['PointVector&lt; dim, InternalInteger &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_20space_3a_3adimension_2c_20real_20_3e_9541',['PointVector&lt; Space::dimension, Real &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['polarpointcomparatorby2x2detcomputer_9542',['PolarPointComparatorBy2x2DetComputer',['../classDGtal_1_1functors_1_1PolarPointComparatorBy2x2DetComputer.html',1,'DGtal::functors']]],
  ['polygonalcalculus_9543',['PolygonalCalculus',['../classDGtal_1_1PolygonalCalculus.html',1,'DGtal']]],
  ['polygonalsurface_9544',['PolygonalSurface',['../classDGtal_1_1PolygonalSurface.html',1,'DGtal']]],
  ['polygond3d_9545',['PolygonD3D',['../structDGtal_1_1Display3D_1_1PolygonD3D.html',1,'DGtal::Display3D']]],
  ['polyline_9546',['Polyline',['../structLibBoard_1_1Polyline.html',1,'LibBoard']]],
  ['posdepscaledepscestimator_9547',['PosDepScaleDepSCEstimator',['../classDGtal_1_1detail_1_1PosDepScaleDepSCEstimator.html',1,'DGtal::detail']]],
  ['posdepscaledepscestimator_3c_20dcacomputer_2c_20detail_3a_3adistancefromdca_20_3e_9548',['PosDepScaleDepSCEstimator&lt; DCAComputer, detail::DistanceFromDCA &gt;',['../classDGtal_1_1detail_1_1PosDepScaleDepSCEstimator.html',1,'DGtal::detail']]],
  ['posdepscaleindepscestimator_9549',['PosDepScaleIndepSCEstimator',['../classDGtal_1_1detail_1_1PosDepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posdepscaleindepscestimator_3c_20dcacomputer_2c_20detail_3a_3anormalvectorfromdca_20_3e_9550',['PosDepScaleIndepSCEstimator&lt; DCAComputer, detail::NormalVectorFromDCA &gt;',['../classDGtal_1_1detail_1_1PosDepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posdepscaleindepscestimator_3c_20dcacomputer_2c_20detail_3a_3atangentvectorfromdca_20_3e_9551',['PosDepScaleIndepSCEstimator&lt; DCAComputer, detail::TangentVectorFromDCA &gt;',['../classDGtal_1_1detail_1_1PosDepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaledepscestimator_9552',['PosIndepScaleDepSCEstimator',['../classDGtal_1_1detail_1_1PosIndepScaleDepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaledepscestimator_3c_20dcacomputer_2c_20detail_3a_3acurvaturefromdca_3c_20true_20_3e_20_3e_9553',['PosIndepScaleDepSCEstimator&lt; DCAComputer, detail::CurvatureFromDCA&lt; true &gt; &gt;',['../classDGtal_1_1detail_1_1PosIndepScaleDepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaleindepscestimator_9554',['PosIndepScaleIndepSCEstimator',['../classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaleindepscestimator_3c_20dsscomputer_2c_20detail_3a_3anormalizedtangentvectorfromdss_20_3e_9555',['PosIndepScaleIndepSCEstimator&lt; DSSComputer, detail::NormalizedTangentVectorFromDSS &gt;',['../classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaleindepscestimator_3c_20dsscomputer_2c_20detail_3a_3atangentanglefromdss_20_3e_9556',['PosIndepScaleIndepSCEstimator&lt; DSSComputer, detail::TangentAngleFromDSS &gt;',['../classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaleindepscestimator_3c_20dsscomputer_2c_20detail_3a_3atangentvectorfromdss_3c_20dsscomputer_20_3e_20_3e_9557',['PosIndepScaleIndepSCEstimator&lt; DSSComputer, detail::TangentVectorFromDSS&lt; DSSComputer &gt; &gt;',['../classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['positionfunctorfrom2dpoint_9558',['PositionFunctorFrom2DPoint',['../structDGtal_1_1functors_1_1PositionFunctorFrom2DPoint.html',1,'DGtal::functors']]],
  ['pow_9559',['POW',['../classDGtal_1_1POW.html',1,'DGtal']]],
  ['pow_3c_20x_2c_200_20_3e_9560',['POW&lt; X, 0 &gt;',['../classDGtal_1_1POW_3_01X_00_010_01_4.html',1,'DGtal']]],
  ['pow_3c_20x_2c_201_20_3e_9561',['POW&lt; X, 1 &gt;',['../classDGtal_1_1POW_3_01X_00_011_01_4.html',1,'DGtal']]],
  ['power_5fnode_9562',['power_node',['../structDGtal_1_1detail_1_1power__node.html',1,'DGtal::detail']]],
  ['powermap_9563',['PowerMap',['../classDGtal_1_1PowerMap.html',1,'DGtal']]],
  ['powermap_3c_20tweightimage_2c_20tpseparablemetric_2c_20imagecontainerbystlvector_3c_20hyperrectdomain_3c_20typename_20tweightimage_3a_3adomain_3a_3aspace_20_3e_2c_20typename_20tweightimage_3a_3adomain_3a_3aspace_3a_3avector_20_3e_20_3e_9564',['PowerMap&lt; TWeightImage, TPSeparableMetric, ImageContainerBySTLVector&lt; HyperRectDomain&lt; typename TWeightImage::Domain::Space &gt;, typename TWeightImage::Domain::Space::Vector &gt; &gt;',['../classDGtal_1_1PowerMap.html',1,'DGtal']]],
  ['ppmreader_9565',['PPMReader',['../structDGtal_1_1PPMReader.html',1,'DGtal']]],
  ['ppmwriter_9566',['PPMWriter',['../structDGtal_1_1PPMWriter.html',1,'DGtal']]],
  ['precelldirectioniterator_9567',['PreCellDirectionIterator',['../classDGtal_1_1PreCellDirectionIterator.html',1,'DGtal']]],
  ['predicatecombiner_9568',['PredicateCombiner',['../structDGtal_1_1functors_1_1PredicateCombiner.html',1,'DGtal::functors']]],
  ['predicatecombiner_3c_20tlow_2c_20tup_2c_20andboolfct2_20_3e_9569',['PredicateCombiner&lt; Tlow, Tup, AndBoolFct2 &gt;',['../structDGtal_1_1functors_1_1PredicateCombiner.html',1,'DGtal::functors']]],
  ['predicatefromorientationfunctor2_9570',['PredicateFromOrientationFunctor2',['../classDGtal_1_1PredicateFromOrientationFunctor2.html',1,'DGtal']]],
  ['predicatefromorientationfunctor2_3c_20functor_2c_20false_2c_20false_20_3e_9571',['PredicateFromOrientationFunctor2&lt; Functor, false, false &gt;',['../classDGtal_1_1PredicateFromOrientationFunctor2.html',1,'DGtal']]],
  ['predicatefromorientationfunctor2_3c_20functor_2c_20true_2c_20false_20_3e_9572',['PredicateFromOrientationFunctor2&lt; Functor, true, false &gt;',['../classDGtal_1_1PredicateFromOrientationFunctor2.html',1,'DGtal']]],
  ['preimage2d_9573',['Preimage2D',['../classDGtal_1_1Preimage2D.html',1,'DGtal']]],
  ['probingframe_9574',['ProbingFrame',['../structDGtal_1_1PlaneProbingDigitalSurfaceLocalEstimator_1_1ProbingFrame.html',1,'DGtal::PlaneProbingDigitalSurfaceLocalEstimator']]],
  ['profile_9575',['Profile',['../classDGtal_1_1Profile.html',1,'DGtal']]],
  ['projector_9576',['Projector',['../structDGtal_1_1functors_1_1Projector.html',1,'DGtal::functors']]],
  ['projector_3c_20spacend_3c_202_2c_20coordinate_20_3e_20_3e_9577',['Projector&lt; SpaceND&lt; 2, Coordinate &gt; &gt;',['../structDGtal_1_1functors_1_1Projector.html',1,'DGtal::functors']]],
  ['projector_3c_20spacend_3c_202_2c_20int_20_3e_20_3e_9578',['Projector&lt; SpaceND&lt; 2, int &gt; &gt;',['../structDGtal_1_1functors_1_1Projector.html',1,'DGtal::functors']]],
  ['projector_3c_20spacend_3c_202_2c_20typename_20tkspace_3a_3aspace_3a_3ainteger_20_3e_20_3e_9579',['Projector&lt; SpaceND&lt; 2, typename TKSpace::Space::Integer &gt; &gt;',['../structDGtal_1_1functors_1_1Projector.html',1,'DGtal::functors']]],
  ['promote_5ftrait_9580',['promote_trait',['../structDGtal_1_1promote__trait.html',1,'DGtal']]],
  ['promote_5ftrait_3c_20int32_5ft_2c_20int64_5ft_20_3e_9581',['promote_trait&lt; int32_t, int64_t &gt;',['../structDGtal_1_1promote__trait_3_01int32__t_00_01int64__t_01_4.html',1,'DGtal']]],
  ['property_9582',['Property',['../structDGtal_1_1DiscreteExteriorCalculus_1_1Property.html',1,'DGtal::DiscreteExteriorCalculus']]]
];
