var searchData=
[
  ['i_20models_20of_20graph_0',['Topology Concepts and Models (part I, models of graph)',['../packageTopologyConcepts1.html',1,'packageTopology']]],
  ['ii_20digital_20surfaces_20surfel_20predicates_1',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['../packageTopologyConcepts2.html',1,'packageTopology']]],
  ['image_20and_20digital_20object_20import_20export_2',['Image and digital object import/export',['../moduleIO.html',1,'packageIO']]],
  ['image_20concepts_3',['Main Image Concepts',['../packageImageConcepts.html',1,'packageImage']]],
  ['image_20imageadapter_3a_20some_20simple_20image_20manipulations_4',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['../tutoImageManipulations.html',1,'packageTutorials']]],
  ['image_20package_5',['Image package',['../packageImage.html',1,'index']]],
  ['image_20processing_6',['Image processing',['http://dgtal.org/doc/tools/nightly/imageProcessing.html',1,'']]],
  ['image_20region_20distance_20transformation_7',['Tutorial &quot;Image -&gt; Region -&gt; Distance Transformation&quot;',['../tutoImageRegionDT.html',1,'packageTutorials']]],
  ['image_20region_20grid_20curve_20extracting_20level_20set_20boundary_20from_20image_8',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt;  Extracting level set boundary from Image&quot;',['../tutoImageGridCurveExtraction.html',1,'packageTutorials']]],
  ['image_20region_20grid_20curve_20length_20estimation_9',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt; Length estimation&quot;',['../tutoImageGridCurveEstimator.html',1,'packageTutorials']]],
  ['image_20region_20volume_203dvolviewer_20_3a_20a_20simple_203d_20volume_20viewer_20in_20less_20than_2050_20lines_10',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['../tutoImageGridVolume3dVolViewer.html',1,'packageTutorials']]],
  ['image_20restoration_20and_20inpainting_20with_20ambrosio_20tortorelli_20functional_11',['Image restoration and inpainting with Ambrosio-Tortorelli functional',['http://dgtal.org/doc/tools/nightly/moduleAT.html',1,'']]],
  ['imageadapter_3a_20some_20simple_20image_20manipulations_12',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['../tutoImageManipulations.html',1,'packageTutorials']]],
  ['imageprocessing_20at_20u0_20v1_13',['imageProcessing/at-u0-v1',['http://dgtal.org/doc/tools/nightly/DocATu0v1.html',1,'']]],
  ['imageprocessing_20at_20u2_20v0_14',['imageProcessing/at-u2-v0',['http://dgtal.org/doc/tools/nightly/DocATu2v0.html',1,'']]],
  ['images_15',['Images',['../moduleImages.html',1,'packageImage']]],
  ['images_20in_20dgtal_16',['Handle large images in DGtal',['../moduleBigImages.html',1,'packageImage']]],
  ['img2freeman_17',['img2freeman',['http://dgtal.org/doc/tools/nightly/img2freeman.html',1,'']]],
  ['imgaddnoise_18',['imgAddNoise',['http://dgtal.org/doc/tools/nightly/imgAddNoise.html',1,'']]],
  ['implementation_20of_20geometric_20predicates_19',['Implementation of geometric predicates',['../moduleGeometricPredicates.html',1,'packageGeometry']]],
  ['import_20export_20',['Image and digital object import/export',['../moduleIO.html',1,'packageIO']]],
  ['in_20arbitrary_20dimension_20for_20convex_20hull_20and_20delaunay_20cell_20complex_20computation_21',['QuickHull algorithm in arbitrary dimension for convex hull and Delaunay cell complex computation',['../moduleQuickHull.html',1,'packageGeometry']]],
  ['in_20dgtal_22',['in dgtal',['../moduleFAQGit.html',1,'Git/Github source code management in DGtal'],['../moduleBigImages.html',1,'Handle large images in DGtal'],['../moduleFunctors.html',1,'Using functions, functors and lambdas in DGtal']]],
  ['in_20dgtal_20using_20catch_23',['Unit test in DGtal using Catch',['../moduleCatch.html',1,'packageDev']]],
  ['in_20digital_20spaces_24',['Sets of points in digital spaces',['../moduleDigitalSets.html',1,'packageKernel']]],
  ['in_20heat_20using_20discrete_20polygonal_20calculus_25',['Geodesics In Heat using discrete polygonal calculus',['../moduleGeodesicsInHeat.html',1,'packageDEC']]],
  ['in_20less_20than_2050_20lines_26',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['../tutoImageGridVolume3dVolViewer.html',1,'packageTutorials']]],
  ['in_20my_20own_20project_27',['How to use DGtal in my own project ?',['../moduleHowToUseDGtal.html',1,'packageIntroduction']]],
  ['in_20r3_28',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['in_20the_20digital_20plane_20zxz_20convex_20polygons_20with_20vertices_20at_20integer_20coordinates_29',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['../moduleLatticePolytope2D.html',1,'packageArithmetic']]],
  ['in_20the_20plane_30',['Convex hull and alpha-shape in the plane',['../moduleHull2D.html',1,'packageGeometry']]],
  ['incidence_31',['Cellular grid space and topology, unoriented and oriented cells, incidence',['../moduleCellularTopology.html',1,'packageTopology']]],
  ['inpainting_20with_20ambrosio_20tortorelli_20functional_32',['Image restoration and inpainting with Ambrosio-Tortorelli functional',['http://dgtal.org/doc/tools/nightly/moduleAT.html',1,'']]],
  ['integer_20computations_33',['Integer computations',['../moduleIntegerComputations.html',1,'packageArithmetic']]],
  ['integer_20concepts_34',['Number and Integer Concepts',['../moduleNumber.html',1,'packageKernel']]],
  ['integer_20coordinates_35',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['../moduleLatticePolytope2D.html',1,'packageArithmetic']]],
  ['integral_20invariant_20curvature_20estimator_202d_203d_36',['Integral invariant curvature estimator 2D/3D',['../moduleIntegralInvariant.html',1,'packageGeometry']]],
  ['interfacing_20with_20boost_3a_3agraph_20library_37',['Interfacing with boost::graph library',['../moduleBoostGraphWrapping.html',1,'packageGraph']]],
  ['into_20m_20dimensional_20space_38',['Embedding n-dimensional DEC structures into m-dimensional space',['../moduleDECEmbedding.html',1,'packageDEC']]],
  ['introduction_39',['Introduction',['../moduleIntroduction.html',1,'packageIntroduction']]],
  ['invariant_20curvature_20estimator_202d_203d_40',['Integral invariant curvature estimator 2D/3D',['../moduleIntegralInvariant.html',1,'packageGeometry']]],
  ['io_20package_41',['IO package',['../packageIO.html',1,'index']]],
  ['irreducible_20fraction_20continued_20fractions_42',['Irreducible fraction, continued fractions',['../moduleIrreducibleFraction.html',1,'packageArithmetic']]],
  ['iterators_20and_20ranges_43',['Iterators and ranges',['../moduleIteratorsRanges.html',1,'packageBase']]],
  ['itk2vol_44',['itk2vol',['http://dgtal.org/doc/tools/nightly/itk2vol.html',1,'']]]
];
