var searchData=
[
  ['tangentbc_0',['tangentBC',['http://dgtal.org/doc/tools/nightly/tangentBC.html',1,'']]],
  ['test_20in_20dgtal_20using_20catch_1',['Unit test in DGtal using Catch',['../moduleCatch.html',1,'packageDev']]],
  ['than_2050_20lines_2',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['../tutoImageGridVolume3dVolViewer.html',1,'packageTutorials']]],
  ['the_20digital_20plane_20zxz_20convex_20polygons_20with_20vertices_20at_20integer_20coordinates_3',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['../moduleLatticePolytope2D.html',1,'packageArithmetic']]],
  ['the_20fast_20marching_20method_4',['Tutorial: Local morphological opening of a 3d volume by the Fast Marching Method',['../tutoFMMErosion.html',1,'packageTutorials']]],
  ['the_20impatient_20developper_5',['Shortcuts (for the impatient developper)',['../moduleShortcuts.html',1,'index']]],
  ['the_20plane_6',['Convex hull and alpha-shape in the plane',['../moduleHull2D.html',1,'packageGeometry']]],
  ['the_20shrouds_20algorithm_7',['Digital surface regularization using the Shrouds algorithm',['../moduleShrouds.html',1,'packageGeometry']]],
  ['thick_20segment_20recognition_20br_8',['Alpha-thick Segment Recognition   &lt;br&gt;',['../moduleAlphaThickSegmentReco.html',1,'packageGeometry']]],
  ['to_202_200_9',['Migrating viewer from 1.4 to 2.0',['../migratingViewer3D.html',1,'packageIO']]],
  ['to_20use_20dgtal_20in_20my_20own_20project_10',['How to use DGtal in my own project ?',['../moduleHowToUseDGtal.html',1,'packageIntroduction']]],
  ['tools_20and_20algorithms_20library_11',['DGtal - Digital Geometry Tools and Algorithms Library.',['../index.html',1,'']]],
  ['topology_20and_20digital_20objects_12',['Digital topology and digital objects',['../moduleDigitalTopology.html',1,'packageTopology']]],
  ['topology_20concepts_20and_20models_20part_20i_20models_20of_20graph_13',['Topology Concepts and Models (part I, models of graph)',['../packageTopologyConcepts1.html',1,'packageTopology']]],
  ['topology_20concepts_20and_20models_20part_20ii_20digital_20surfaces_20surfel_20predicates_14',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['../packageTopologyConcepts2.html',1,'packageTopology']]],
  ['topology_20package_15',['Topology package',['../packageTopology.html',1,'index']]],
  ['topology_20unoriented_20and_20oriented_20cells_20incidence_16',['Cellular grid space and topology, unoriented and oriented cells, incidence',['../moduleCellularTopology.html',1,'packageTopology']]],
  ['tortorelli_20functional_17',['tortorelli functional',['http://dgtal.org/doc/tools/nightly/moduleAT.html',1,'Image restoration and inpainting with Ambrosio-Tortorelli functional'],['../moduleGenericAT.html',1,'Piecewise-smooth approximation using a discrete calculus model of Ambrosio-Tortorelli functional']]],
  ['transformation_18',['Tutorial &quot;Image -&gt; Region -&gt; Distance Transformation&quot;',['../tutoImageRegionDT.html',1,'packageTutorials']]],
  ['transformations_19',['Geometric transformations',['../moduleGeometricTransform.html',1,'packageImage']]],
  ['triangulated_20surfaces_20and_20polygonal_20surfaces_20',['Half-edge data structure, triangulated surfaces and polygonal surfaces',['../moduleHalfEdgeMesh.html',1,'packageTopology']]],
  ['tutorial_20file_20grid_20curve_20ranges_21',['Tutorial &quot;File -&gt; Grid Curve -&gt; Ranges&quot;',['../tutoFileGridCurveRanges.html',1,'packageTutorials']]],
  ['tutorial_20generated_20shape_20grid_20curve_20length_20estimation_22',['Tutorial &quot;Generated shape -&gt; Grid curve -&gt; Length estimation&quot;',['../tutoShapeGridCurveEstimator.html',1,'packageTutorials']]],
  ['tutorial_20image_20imageadapter_3a_20some_20simple_20image_20manipulations_23',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['../tutoImageManipulations.html',1,'packageTutorials']]],
  ['tutorial_20image_20region_20distance_20transformation_24',['Tutorial &quot;Image -&gt; Region -&gt; Distance Transformation&quot;',['../tutoImageRegionDT.html',1,'packageTutorials']]],
  ['tutorial_20image_20region_20grid_20curve_20extracting_20level_20set_20boundary_20from_20image_25',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt;  Extracting level set boundary from Image&quot;',['../tutoImageGridCurveExtraction.html',1,'packageTutorials']]],
  ['tutorial_20image_20region_20grid_20curve_20length_20estimation_26',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt; Length estimation&quot;',['../tutoImageGridCurveEstimator.html',1,'packageTutorials']]],
  ['tutorial_20image_20region_20volume_203dvolviewer_20_3a_20a_20simple_203d_20volume_20viewer_20in_20less_20than_2050_20lines_27',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['../tutoImageGridVolume3dVolViewer.html',1,'packageTutorials']]],
  ['tutorial_3a_20local_20morphological_20opening_20of_20a_203d_20volume_20by_20the_20fast_20marching_20method_28',['Tutorial: Local morphological opening of a 3d volume by the Fast Marching Method',['../tutoFMMErosion.html',1,'packageTutorials']]],
  ['tutorial_3a_20making_20a_20polyhedron_20from_20a_20digital_20object_29',['Tutorial: making a polyhedron from a digital object',['../tutoPolyhedralisation.html',1,'packageTutorials']]],
  ['tutorial_3a_20surface_20area_20estimation_30',['Tutorial: Surface area estimation',['../tutoAreaSurface.html',1,'packageTutorials']]],
  ['tutorial_3a_20volumetric_20analysis_20and_20granulometry_31',['Tutorial: Volumetric analysis and Granulometry',['../tutoVolDTGranulometry.html',1,'packageTutorials']]],
  ['tutorials_32',['Tutorials',['../packageTutorials.html',1,'index']]]
];
