var searchData=
[
  ['sdp2vol_0',['sdp2vol',['http://dgtal.org/doc/tools/nightly/sdp2vol.html',1,'']]],
  ['segment_20recognition_1',['Alpha-thick Segment Recognition',['../moduleAlphaThickSegmentReco.html',1,'packageGeometry']]],
  ['segments_2',['Digital straight lines and segments',['../moduleArithDSSReco.html',1,'packageGeometry']]],
  ['segments_20and_20slices_20of_20digital_20surface_20based_20normal_20estimator_3',['Maximal segments and slices of digital surface based normal estimator',['../moduleMaximalSegmentSliceEstimation.html',1,'packageGeometry']]],
  ['separable_20processes_4',['nD Volumetric Analysis using Separable Processes',['../moduleVolumetric.html',1,'packageGeometry']]],
  ['set_20boundary_20from_20image_5',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt;  Extracting level set boundary from Image&quot;',['../tutoImageGridCurveExtraction.html',1,'packageTutorials']]],
  ['set_20operations_20on_20arbitrary_20containers_6',['Set operations on arbitrary containers',['../moduleSetFunctions.html',1,'packageBase']]],
  ['sets_20of_20points_20in_20digital_20spaces_7',['Sets of points in digital spaces',['../moduleDigitalSets.html',1,'packageKernel']]],
  ['shape_20grid_20curve_20length_20estimation_8',['Tutorial &quot;Generated shape -&gt; Grid curve -&gt; Length estimation&quot;',['../tutoShapeGridCurveEstimator.html',1,'packageTutorials']]],
  ['shape_20in_20the_20plane_9',['Convex hull and alpha-shape in the plane',['../moduleHull2D.html',1,'packageGeometry']]],
  ['shapegenerator_10',['shapeGenerator',['http://dgtal.org/doc/tools/nightly/shapeGenerator.html',1,'']]],
  ['shapers_20and_20digitizers_11',['Shapes, Shapers and Digitizers',['../moduleShape.html',1,'packageShapes']]],
  ['shapes_20concepts_12',['Shapes Concepts',['../packageShapesConcepts.html',1,'packageShapes']]],
  ['shapes_20package_13',['Shapes package',['../packageShapes.html',1,'index']]],
  ['shapes_20shapers_20and_20digitizers_14',['Shapes, Shapers and Digitizers',['../moduleShape.html',1,'packageShapes']]],
  ['shortcuts_15',['shortcuts',['../moduleFrechetShortcut.html',1,'Fréchet Shortcuts'],['../moduleShortcuts.html',1,'Shortcuts']]],
  ['shrouds_20algorithm_16',['Digital surface regularization using the Shrouds algorithm',['../moduleShrouds.html',1,'packageGeometry']]],
  ['simple_203d_20volume_20viewer_20in_20less_20than_2050_20lines_17',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['../tutoImageGridVolume3dVolViewer.html',1,'packageTutorials']]],
  ['simple_20image_20manipulations_18',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['../tutoImageManipulations.html',1,'packageTutorials']]],
  ['simple_20mesh_19',['Manipulating Simple Mesh',['../moduleMesh.html',1,'packageShapes']]],
  ['slice2vol_20',['slice2vol',['http://dgtal.org/doc/tools/nightly/slice2vol.html',1,'']]],
  ['slices_20of_20digital_20surface_20based_20normal_20estimator_21',['Maximal segments and slices of digital surface based normal estimator',['../moduleMaximalSegmentSliceEstimation.html',1,'packageGeometry']]],
  ['sliceviewer_22',['sliceViewer',['http://dgtal.org/doc/tools/nightly/sliceViewer.html',1,'']]],
  ['smooth_20approximation_20using_20a_20discrete_20calculus_20model_20of_20ambrosio_20tortorelli_20functional_23',['Piecewise-smooth approximation using a discrete calculus model of Ambrosio-Tortorelli functional',['../moduleGenericAT.html',1,'packageDEC']]],
  ['some_20simple_20image_20manipulations_24',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['../tutoImageManipulations.html',1,'packageTutorials']]],
  ['source_20code_20management_20in_20dgtal_25',['Git/Github source code management in DGtal',['../moduleFAQGit.html',1,'packageDev']]],
  ['space_26',['Embedding n-dimensional DEC structures into m-dimensional space',['../moduleDECEmbedding.html',1,'packageDEC']]],
  ['space_20and_20topology_20unoriented_20and_20oriented_20cells_20incidence_27',['Cellular grid space and topology, unoriented and oriented cells, incidence',['../moduleCellularTopology.html',1,'packageTopology']]],
  ['spaces_28',['Sets of points in digital spaces',['../moduleDigitalSets.html',1,'packageKernel']]],
  ['spaces_20digital_20metric_20spaces_20and_20related_20concepts_29',['Metric Spaces, Digital Metric Spaces and Related Concepts',['../moduleMetrics.html',1,'packageGeometry']]],
  ['spaces_20points_20vectors_20and_20domains_30',['Digital Spaces, Points, Vectors and Domains',['../moduleSpacePointVectorDomain.html',1,'packageKernel']]],
  ['started_31',['Getting started',['../packageIntroduction.html',1,'index']]],
  ['statisticsestimators_32',['statisticsEstimators',['http://dgtal.org/doc/tools/nightly/statisticsEstimators.html',1,'']]],
  ['straight_20lines_20and_20segments_33',['Digital straight lines and segments',['../moduleArithDSSReco.html',1,'packageGeometry']]],
  ['straight_20lines_20and_20subsegments_34',['Patterns, digital straight lines and subsegments',['../moduleDigitalStraightness.html',1,'packageArithmetic']]],
  ['stream_20mechanism_20for_20displaying_202d_20digital_20objects_35',['Board2D: a stream mechanism for displaying 2D digital objects',['../moduleBoard2D.html',1,'packageIO']]],
  ['stream_20mechanism_20for_20displaying_203d_20dgtal_20objects_36',['Display3D: a stream mechanism for displaying 3D DGtal objects',['../moduleDisplay3D.html',1,'packageIO']]],
  ['structure_20for_20representing_20manifold_20or_20non_20manifold_20polygonal_20surfaces_20in_20r3_37',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['structure_20triangulated_20surfaces_20and_20polygonal_20surfaces_38',['Half-edge data structure, triangulated surfaces and polygonal surfaces',['../moduleHalfEdgeMesh.html',1,'packageTopology']]],
  ['structures_39',['Analysis of one-dimensional discrete structures',['../moduleGridCurveAnalysis.html',1,'packageGeometry']]],
  ['structures_20into_20m_20dimensional_20space_40',['Embedding n-dimensional DEC structures into m-dimensional space',['../moduleDECEmbedding.html',1,'packageDEC']]],
  ['subsegments_41',['Patterns, digital straight lines and subsegments',['../moduleDigitalStraightness.html',1,'packageArithmetic']]],
  ['surface_20area_20estimation_42',['Tutorial: Surface area estimation',['../tutoAreaSurface.html',1,'packageTutorials']]],
  ['surface_20based_20normal_20estimator_43',['Maximal segments and slices of digital surface based normal estimator',['../moduleMaximalSegmentSliceEstimation.html',1,'packageGeometry']]],
  ['surface_20estimators_20from_20surfel_20functors_44',['Local digital surface estimators from surfel functors',['../LocalEstimatorsFromSurfel.html',1,'packageGeometry']]],
  ['surface_20mesh_20data_20structure_20for_20representing_20manifold_20or_20non_20manifold_20polygonal_20surfaces_20in_20r3_45',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['surface_20regularization_20by_20normal_20vector_20alignment_46',['Digital surface regularization by normal vector alignment',['../moduleRegularization.html',1,'packageGeometry']]],
  ['surface_20regularization_20using_20the_20shrouds_20algorithm_47',['Digital surface regularization using the Shrouds algorithm',['../moduleShrouds.html',1,'packageGeometry']]],
  ['surfaces_48',['surfaces',['../moduleCurvatureMeasures.html',1,'Curvature measures on meshes and digital surfaces'],['../moduleDigitalSurfaces.html',1,'Digital surfaces'],['../modulePolygonalCalculus.html',1,'Discrete differential calculus on polygonal surfaces'],['../moduleDigitalSurfaceHelpers.html',1,'Helpers for digital surfaces']]],
  ['surfaces_20and_20polygonal_20surfaces_49',['Half-edge data structure, triangulated surfaces and polygonal surfaces',['../moduleHalfEdgeMesh.html',1,'packageTopology']]],
  ['surfaces_20in_20r3_50',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['surfaces_20surfel_20predicates_51',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['../packageTopologyConcepts2.html',1,'packageTopology']]],
  ['surfel_20functors_52',['Local digital surface estimators from surfel functors',['../LocalEstimatorsFromSurfel.html',1,'packageGeometry']]],
  ['surfel_20predicates_53',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['../packageTopologyConcepts2.html',1,'packageTopology']]]
];
