var searchData=
[
  ['calculus_0',['calculus',['../moduleDECIntroduction.html',1,'Discrete exterior calculus'],['../moduleGeodesicsInHeat.html',1,'Geodesics In Heat using discrete polygonal calculus'],['../moduleVectorsInHeat.html',1,'Vector Heat Method using discrete polygonal calculus']]],
  ['calculus_20model_20of_20ambrosio_20tortorelli_20functional_1',['Piecewise-smooth approximation using a discrete calculus model of Ambrosio-Tortorelli functional',['../moduleGenericAT.html',1,'packageDEC']]],
  ['calculus_20on_20polygonal_20surfaces_2',['Discrete differential calculus on polygonal surfaces',['../modulePolygonalCalculus.html',1,'packageDEC']]],
  ['catch_3',['Unit test in DGtal using Catch',['../moduleCatch.html',1,'index']]],
  ['cell_20complex_20computation_4',['QuickHull algorithm in arbitrary dimension for convex hull and Delaunay cell complex computation',['../moduleQuickHull.html',1,'packageGeometry']]],
  ['cells_20incidence_5',['Cellular grid space and topology, unoriented and oriented cells, incidence',['../moduleCellularTopology.html',1,'packageTopology']]],
  ['cellular_20grid_20space_20and_20topology_20unoriented_20and_20oriented_20cells_20incidence_6',['Cellular grid space and topology, unoriented and oriented cells, incidence',['../moduleCellularTopology.html',1,'packageTopology']]],
  ['cloning_20and_20referencing_7',['Parameter passing, cloning and referencing',['../moduleCloneAndReference.html',1,'packageBase']]],
  ['cloud_8',['Voxelization from an oriented point cloud',['../moduleWinding.html',1,'packageShapes']]],
  ['coba_20plane_20recognition_20algorithm_9',['Detailed explanation of COBA plane recognition algorithm',['../moduleCOBANaivePlaneRecognition.html',1,'packageGeometry']]],
  ['code_20management_20in_20dgtal_10',['Git/Github source code management in DGtal',['../moduleFAQGit.html',1,'index']]],
  ['complex_11',['complex',['../moduleCubicalComplex.html',1,'Cubical Complex'],['../moduleVoxelComplex.html',1,'Voxel Complex']]],
  ['complex_20computation_12',['QuickHull algorithm in arbitrary dimension for convex hull and Delaunay cell complex computation',['../moduleQuickHull.html',1,'packageGeometry']]],
  ['computation_13',['computation',['../modulePlaneRecognition.html',1,'Plane recognition and plane width computation'],['../moduleQuickHull.html',1,'QuickHull algorithm in arbitrary dimension for convex hull and Delaunay cell complex computation']]],
  ['computations_14',['Integer computations',['../moduleIntegerComputations.html',1,'packageArithmetic']]],
  ['concepts_15',['concepts',['../packageBaseConcepts.html',1,'Base Concepts'],['../moduleGraphDefinitions.html',1,'Basic graph definitions and concepts'],['../packageDECConcepts.html',1,'DEC Main Concepts'],['../packageGeometryConcepts.html',1,'Geometry Concepts'],['../packageGraphConcepts.html',1,'Graph Main Concepts'],['../packageKernelConcepts.html',1,'Kernel Concepts'],['../packageImageConcepts.html',1,'Main Image Concepts'],['../packageMathConcepts.html',1,'Math Main Concepts'],['../moduleMetrics.html',1,'Metric Spaces, Digital Metric Spaces and Related Concepts'],['../moduleNumber.html',1,'Number and Integer Concepts'],['../packageShapesConcepts.html',1,'Shapes Concepts']]],
  ['concepts_20and_20models_16',['Arithmetic Concepts and Models',['../packageArithmeticConcepts.html',1,'packageArithmetic']]],
  ['concepts_20and_20models_20part_20i_20models_20of_20graph_17',['Topology Concepts and Models (part I, models of graph)',['../packageTopologyConcepts1.html',1,'packageTopology']]],
  ['concepts_20and_20models_20part_20ii_20digital_20surfaces_20surfel_20predicates_18',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['../packageTopologyConcepts2.html',1,'packageTopology']]],
  ['containers_19',['Set operations on arbitrary containers',['../moduleSetFunctions.html',1,'packageBase']]],
  ['continued_20fractions_20',['Irreducible fraction, continued fractions',['../moduleIrreducibleFraction.html',1,'packageArithmetic']]],
  ['contourgenerator_21',['contourGenerator',['http://dgtal.org/doc/tools/nightly/contourGenerator.html',1,'']]],
  ['converters_22',['converters',['http://dgtal.org/doc/tools/nightly/converters.html',1,'']]],
  ['convertvol_23',['convertVol',['http://dgtal.org/doc/tools/nightly/convertVol.html',1,'']]],
  ['convex_20envelope_20relative_20fully_20convex_20envelope_20and_20digital_20polyhedra_24',['Fully convex envelope, relative fully convex envelope and digital polyhedra',['../moduleEnvelope.html',1,'packageGeometry']]],
  ['convex_20hull_20and_20alpha_20shape_20in_20the_20plane_25',['Convex hull and alpha-shape in the plane',['../moduleHull2D.html',1,'packageGeometry']]],
  ['convex_20hull_20and_20delaunay_20cell_20complex_20computation_26',['QuickHull algorithm in arbitrary dimension for convex hull and Delaunay cell complex computation',['../moduleQuickHull.html',1,'packageGeometry']]],
  ['convex_20polygons_20with_20vertices_20at_20integer_20coordinates_27',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['../moduleLatticePolytope2D.html',1,'packageArithmetic']]],
  ['convexity_28',['Applications of full digital convexity',['../moduleDigitalConvexityApplications.html',1,'packageGeometry']]],
  ['convexity_20full_20convexity_20and_20p_20convexity_29',['Digital convexity, full convexity and P-convexity',['../moduleDigitalConvexity.html',1,'packageGeometry']]],
  ['coordinates_30',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['../moduleLatticePolytope2D.html',1,'packageArithmetic']]],
  ['covariance_20measure_20and_20geometry_20estimation_31',['Digital Voronoi Covariance Measure and geometry estimation',['../moduleVCM.html',1,'packageGeometry']]],
  ['cubical_20complex_32',['Cubical Complex',['../moduleCubicalComplex.html',1,'packageTopology']]],
  ['curvature_20estimator_202d_203d_33',['Integral invariant curvature estimator 2D/3D',['../moduleIntegralInvariant.html',1,'packageGeometry']]],
  ['curvature_20measures_20on_20meshes_20and_20digital_20surfaces_34',['Curvature measures on meshes and digital surfaces',['../moduleCurvatureMeasures.html',1,'packageGeometry']]],
  ['curvaturebc_35',['curvatureBC',['http://dgtal.org/doc/tools/nightly/curvatureBC.html',1,'']]],
  ['curvaturemcms_36',['curvatureMCMS',['http://dgtal.org/doc/tools/nightly/curvatureMCMS.html',1,'']]],
  ['curvaturescalespacebcc_37',['curvatureScaleSpaceBCC',['http://dgtal.org/doc/tools/nightly/curvatureScaleSpaceBCC.html',1,'']]],
  ['curve_20extracting_20level_20set_20boundary_20from_20image_38',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt;  Extracting level set boundary from Image&quot;',['../tutoImageGridCurveExtraction.html',1,'packageTutorials']]],
  ['curve_20length_20estimation_39',['curve length estimation',['../tutoShapeGridCurveEstimator.html',1,'Tutorial &quot;Generated shape -&gt; Grid curve -&gt; Length estimation&quot;'],['../tutoImageGridCurveEstimator.html',1,'Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt; Length estimation&quot;']]],
  ['curve_20ranges_40',['Tutorial &quot;File -&gt; Grid Curve -&gt; Ranges&quot;',['../tutoFileGridCurveRanges.html',1,'packageTutorials']]],
  ['curves_41',['Digitization of 3D parametric curves',['../moduleParametricCurves.html',1,'packageGeometry']]]
];
