var searchData=
[
  ['pair1st_9429',['Pair1st',['../classDGtal_1_1functors_1_1Pair1st.html',1,'DGtal::functors']]],
  ['pair1st_3c_20point_20_3e_9430',['Pair1st&lt; Point &gt;',['../classDGtal_1_1functors_1_1Pair1st.html',1,'DGtal::functors']]],
  ['pair1stmutator_9431',['Pair1stMutator',['../classDGtal_1_1functors_1_1Pair1stMutator.html',1,'DGtal::functors']]],
  ['pair2nd_9432',['Pair2nd',['../classDGtal_1_1functors_1_1Pair2nd.html',1,'DGtal::functors']]],
  ['pair2ndmutator_9433',['Pair2ndMutator',['../classDGtal_1_1functors_1_1Pair2ndMutator.html',1,'DGtal::functors']]],
  ['pairassociativecategory_9434',['PairAssociativeCategory',['../structDGtal_1_1PairAssociativeCategory.html',1,'DGtal']]],
  ['pairassociativecontainer_9435',['PairAssociativeContainer',['../structboost_1_1PairAssociativeContainer.html',1,'boost']]],
  ['parallelstrip_9436',['ParallelStrip',['../classDGtal_1_1ParallelStrip.html',1,'DGtal']]],
  ['parameters_9437',['Parameters',['../structDGtal_1_1Parameters.html',1,'DGtal']]],
  ['parametervalue_9438',['ParameterValue',['../structDGtal_1_1ParameterValue.html',1,'DGtal']]],
  ['parametricshapearclengthfunctor_9439',['ParametricShapeArcLengthFunctor',['../classDGtal_1_1ParametricShapeArcLengthFunctor.html',1,'DGtal']]],
  ['parametricshapecurvaturefunctor_9440',['ParametricShapeCurvatureFunctor',['../classDGtal_1_1ParametricShapeCurvatureFunctor.html',1,'DGtal']]],
  ['parametricshapetangentfunctor_9441',['ParametricShapeTangentFunctor',['../classDGtal_1_1ParametricShapeTangentFunctor.html',1,'DGtal']]],
  ['pardircollapse_9442',['ParDirCollapse',['../classDGtal_1_1ParDirCollapse.html',1,'DGtal']]],
  ['patatepoint_9443',['PatatePoint',['../classDGtal_1_1functors_1_1SphereFittingEstimator_1_1PatatePoint.html',1,'DGtal::functors::SphereFittingEstimator']]],
  ['path_9444',['Path',['../structLibBoard_1_1Path.html',1,'LibBoard']]],
  ['pattern_9445',['Pattern',['../classDGtal_1_1Pattern.html',1,'DGtal']]],
  ['pattern_3c_20fraction_20_3e_9446',['Pattern&lt; Fraction &gt;',['../classDGtal_1_1Pattern.html',1,'DGtal']]],
  ['pgmreader_9447',['PGMReader',['../structDGtal_1_1PGMReader.html',1,'DGtal']]],
  ['pgmwriter_9448',['PGMWriter',['../structDGtal_1_1PGMWriter.html',1,'DGtal']]],
  ['planeprobingdigitalsurfacelocalestimator_9449',['PlaneProbingDigitalSurfaceLocalEstimator',['../classDGtal_1_1PlaneProbingDigitalSurfaceLocalEstimator.html',1,'DGtal']]],
  ['planeprobinghneighborhood_9450',['PlaneProbingHNeighborhood',['../classDGtal_1_1PlaneProbingHNeighborhood.html',1,'DGtal']]],
  ['planeprobingneighborhood_9451',['PlaneProbingNeighborhood',['../classDGtal_1_1PlaneProbingNeighborhood.html',1,'DGtal']]],
  ['planeprobingparallelepipedestimator_9452',['PlaneProbingParallelepipedEstimator',['../classDGtal_1_1PlaneProbingParallelepipedEstimator.html',1,'DGtal']]],
  ['planeprobingr1neighborhood_9453',['PlaneProbingR1Neighborhood',['../classDGtal_1_1PlaneProbingR1Neighborhood.html',1,'DGtal']]],
  ['planeprobingrneighborhood_9454',['PlaneProbingRNeighborhood',['../classDGtal_1_1PlaneProbingRNeighborhood.html',1,'DGtal']]],
  ['planeprobingtetrahedronestimator_9455',['PlaneProbingTetrahedronEstimator',['../classDGtal_1_1PlaneProbingTetrahedronEstimator.html',1,'DGtal']]],
  ['planeprobingtetrahedronestimator_3c_20notabovepredicate_2c_20mode_20_3e_9456',['PlaneProbingTetrahedronEstimator&lt; NotAbovePredicate, mode &gt;',['../classDGtal_1_1PlaneProbingTetrahedronEstimator.html',1,'DGtal']]],
  ['point_9457',['Point',['../structLibBoard_1_1Point.html',1,'LibBoard']]],
  ['point2dembedderin3d_9458',['Point2DEmbedderIn3D',['../classDGtal_1_1functors_1_1Point2DEmbedderIn3D.html',1,'DGtal::functors']]],
  ['point2shapepredicate_9459',['Point2ShapePredicate',['../classDGtal_1_1functors_1_1Point2ShapePredicate.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_9460',['Point2ShapePredicateComparator',['../structDGtal_1_1functors_1_1Point2ShapePredicateComparator.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20false_2c_20false_20_3e_9461',['Point2ShapePredicateComparator&lt; T, false, false &gt;',['../structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01false_00_01false_01_4.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20false_2c_20true_20_3e_9462',['Point2ShapePredicateComparator&lt; T, false, true &gt;',['../structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01false_00_01true_01_4.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20true_2c_20false_20_3e_9463',['Point2ShapePredicateComparator&lt; T, true, false &gt;',['../structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01true_00_01false_01_4.html',1,'DGtal::functors']]],
  ['point2shapepredicatecomparator_3c_20t_2c_20true_2c_20true_20_3e_9464',['Point2ShapePredicateComparator&lt; T, true, true &gt;',['../structDGtal_1_1functors_1_1Point2ShapePredicateComparator_3_01T_00_01true_00_01true_01_4.html',1,'DGtal::functors']]],
  ['pointfunctorfrompointpredicateanddomain_9465',['PointFunctorFromPointPredicateAndDomain',['../structDGtal_1_1functors_1_1PointFunctorFromPointPredicateAndDomain.html',1,'DGtal::functors']]],
  ['pointfunctorholder_9466',['PointFunctorHolder',['../classDGtal_1_1functors_1_1PointFunctorHolder.html',1,'DGtal::functors']]],
  ['pointfunctorpredicate_9467',['PointFunctorPredicate',['../structDGtal_1_1functors_1_1PointFunctorPredicate.html',1,'DGtal::functors']]],
  ['pointlistreader_9468',['PointListReader',['../structDGtal_1_1PointListReader.html',1,'DGtal']]],
  ['pointonprobingray_9469',['PointOnProbingRay',['../classDGtal_1_1detail_1_1PointOnProbingRay.html',1,'DGtal::detail']]],
  ['pointvaluecompare_9470',['PointValueCompare',['../classDGtal_1_1detail_1_1PointValueCompare.html',1,'DGtal::detail']]],
  ['pointvector_9471',['PointVector',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_202_2c_20double_20_3e_9472',['PointVector&lt; 2, double &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_202_2c_20integer_20_3e_9473',['PointVector&lt; 2, Integer &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_203_2c_20double_20_3e_9474',['PointVector&lt; 3, double &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_203_2c_20internalinteger_20_3e_9475',['PointVector&lt; 3, InternalInteger &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_203_2c_20internalscalar_20_3e_9476',['PointVector&lt; 3, InternalScalar &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_20dim_2c_20integer_20_3e_9477',['PointVector&lt; dim, Integer &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_20dim_2c_20internalinteger_20_3e_9478',['PointVector&lt; dim, InternalInteger &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['pointvector_3c_20space_3a_3adimension_2c_20real_20_3e_9479',['PointVector&lt; Space::dimension, Real &gt;',['../classDGtal_1_1PointVector.html',1,'DGtal']]],
  ['polarpointcomparatorby2x2detcomputer_9480',['PolarPointComparatorBy2x2DetComputer',['../classDGtal_1_1functors_1_1PolarPointComparatorBy2x2DetComputer.html',1,'DGtal::functors']]],
  ['polygonalcalculus_9481',['PolygonalCalculus',['../classDGtal_1_1PolygonalCalculus.html',1,'DGtal']]],
  ['polygonalsurface_9482',['PolygonalSurface',['../classDGtal_1_1PolygonalSurface.html',1,'DGtal']]],
  ['polygond3d_9483',['PolygonD3D',['../structDGtal_1_1Display3D_1_1PolygonD3D.html',1,'DGtal::Display3D']]],
  ['polyline_9484',['Polyline',['../structLibBoard_1_1Polyline.html',1,'LibBoard']]],
  ['posdepscaledepscestimator_9485',['PosDepScaleDepSCEstimator',['../classDGtal_1_1detail_1_1PosDepScaleDepSCEstimator.html',1,'DGtal::detail']]],
  ['posdepscaledepscestimator_3c_20dcacomputer_2c_20detail_3a_3adistancefromdca_20_3e_9486',['PosDepScaleDepSCEstimator&lt; DCAComputer, detail::DistanceFromDCA &gt;',['../classDGtal_1_1detail_1_1PosDepScaleDepSCEstimator.html',1,'DGtal::detail']]],
  ['posdepscaleindepscestimator_9487',['PosDepScaleIndepSCEstimator',['../classDGtal_1_1detail_1_1PosDepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posdepscaleindepscestimator_3c_20dcacomputer_2c_20detail_3a_3anormalvectorfromdca_20_3e_9488',['PosDepScaleIndepSCEstimator&lt; DCAComputer, detail::NormalVectorFromDCA &gt;',['../classDGtal_1_1detail_1_1PosDepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posdepscaleindepscestimator_3c_20dcacomputer_2c_20detail_3a_3atangentvectorfromdca_20_3e_9489',['PosDepScaleIndepSCEstimator&lt; DCAComputer, detail::TangentVectorFromDCA &gt;',['../classDGtal_1_1detail_1_1PosDepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaledepscestimator_9490',['PosIndepScaleDepSCEstimator',['../classDGtal_1_1detail_1_1PosIndepScaleDepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaledepscestimator_3c_20dcacomputer_2c_20detail_3a_3acurvaturefromdca_3c_20true_20_3e_20_3e_9491',['PosIndepScaleDepSCEstimator&lt; DCAComputer, detail::CurvatureFromDCA&lt; true &gt; &gt;',['../classDGtal_1_1detail_1_1PosIndepScaleDepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaleindepscestimator_9492',['PosIndepScaleIndepSCEstimator',['../classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaleindepscestimator_3c_20dsscomputer_2c_20detail_3a_3anormalizedtangentvectorfromdss_20_3e_9493',['PosIndepScaleIndepSCEstimator&lt; DSSComputer, detail::NormalizedTangentVectorFromDSS &gt;',['../classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaleindepscestimator_3c_20dsscomputer_2c_20detail_3a_3atangentanglefromdss_20_3e_9494',['PosIndepScaleIndepSCEstimator&lt; DSSComputer, detail::TangentAngleFromDSS &gt;',['../classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['posindepscaleindepscestimator_3c_20dsscomputer_2c_20detail_3a_3atangentvectorfromdss_3c_20dsscomputer_20_3e_20_3e_9495',['PosIndepScaleIndepSCEstimator&lt; DSSComputer, detail::TangentVectorFromDSS&lt; DSSComputer &gt; &gt;',['../classDGtal_1_1detail_1_1PosIndepScaleIndepSCEstimator.html',1,'DGtal::detail']]],
  ['positionfunctorfrom2dpoint_9496',['PositionFunctorFrom2DPoint',['../structDGtal_1_1functors_1_1PositionFunctorFrom2DPoint.html',1,'DGtal::functors']]],
  ['pow_9497',['POW',['../classDGtal_1_1POW.html',1,'DGtal']]],
  ['pow_3c_20x_2c_200_20_3e_9498',['POW&lt; X, 0 &gt;',['../classDGtal_1_1POW_3_01X_00_010_01_4.html',1,'DGtal']]],
  ['pow_3c_20x_2c_201_20_3e_9499',['POW&lt; X, 1 &gt;',['../classDGtal_1_1POW_3_01X_00_011_01_4.html',1,'DGtal']]],
  ['power_5fnode_9500',['power_node',['../structDGtal_1_1detail_1_1power__node.html',1,'DGtal::detail']]],
  ['powermap_9501',['PowerMap',['../classDGtal_1_1PowerMap.html',1,'DGtal']]],
  ['powermap_3c_20tweightimage_2c_20tpseparablemetric_2c_20imagecontainerbystlvector_3c_20hyperrectdomain_3c_20typename_20tweightimage_3a_3adomain_3a_3aspace_20_3e_2c_20typename_20tweightimage_3a_3adomain_3a_3aspace_3a_3avector_20_3e_20_3e_9502',['PowerMap&lt; TWeightImage, TPSeparableMetric, ImageContainerBySTLVector&lt; HyperRectDomain&lt; typename TWeightImage::Domain::Space &gt;, typename TWeightImage::Domain::Space::Vector &gt; &gt;',['../classDGtal_1_1PowerMap.html',1,'DGtal']]],
  ['ppmreader_9503',['PPMReader',['../structDGtal_1_1PPMReader.html',1,'DGtal']]],
  ['ppmwriter_9504',['PPMWriter',['../structDGtal_1_1PPMWriter.html',1,'DGtal']]],
  ['precelldirectioniterator_9505',['PreCellDirectionIterator',['../classDGtal_1_1PreCellDirectionIterator.html',1,'DGtal']]],
  ['predicatecombiner_9506',['PredicateCombiner',['../structDGtal_1_1functors_1_1PredicateCombiner.html',1,'DGtal::functors']]],
  ['predicatecombiner_3c_20tlow_2c_20tup_2c_20andboolfct2_20_3e_9507',['PredicateCombiner&lt; Tlow, Tup, AndBoolFct2 &gt;',['../structDGtal_1_1functors_1_1PredicateCombiner.html',1,'DGtal::functors']]],
  ['predicatefromorientationfunctor2_9508',['PredicateFromOrientationFunctor2',['../classDGtal_1_1PredicateFromOrientationFunctor2.html',1,'DGtal']]],
  ['predicatefromorientationfunctor2_3c_20functor_2c_20false_2c_20false_20_3e_9509',['PredicateFromOrientationFunctor2&lt; Functor, false, false &gt;',['../classDGtal_1_1PredicateFromOrientationFunctor2.html',1,'DGtal']]],
  ['predicatefromorientationfunctor2_3c_20functor_2c_20true_2c_20false_20_3e_9510',['PredicateFromOrientationFunctor2&lt; Functor, true, false &gt;',['../classDGtal_1_1PredicateFromOrientationFunctor2.html',1,'DGtal']]],
  ['preimage2d_9511',['Preimage2D',['../classDGtal_1_1Preimage2D.html',1,'DGtal']]],
  ['probingframe_9512',['ProbingFrame',['../structDGtal_1_1PlaneProbingDigitalSurfaceLocalEstimator_1_1ProbingFrame.html',1,'DGtal::PlaneProbingDigitalSurfaceLocalEstimator']]],
  ['profile_9513',['Profile',['../classDGtal_1_1Profile.html',1,'DGtal']]],
  ['projector_9514',['Projector',['../structDGtal_1_1functors_1_1Projector.html',1,'DGtal::functors']]],
  ['projector_3c_20spacend_3c_202_2c_20coordinate_20_3e_20_3e_9515',['Projector&lt; SpaceND&lt; 2, Coordinate &gt; &gt;',['../structDGtal_1_1functors_1_1Projector.html',1,'DGtal::functors']]],
  ['projector_3c_20spacend_3c_202_2c_20int_20_3e_20_3e_9516',['Projector&lt; SpaceND&lt; 2, int &gt; &gt;',['../structDGtal_1_1functors_1_1Projector.html',1,'DGtal::functors']]],
  ['promote_5ftrait_9517',['promote_trait',['../structDGtal_1_1promote__trait.html',1,'DGtal']]],
  ['promote_5ftrait_3c_20int32_5ft_2c_20int64_5ft_20_3e_9518',['promote_trait&lt; int32_t, int64_t &gt;',['../structDGtal_1_1promote__trait_3_01int32__t_00_01int64__t_01_4.html',1,'DGtal']]],
  ['property_9519',['Property',['../structDGtal_1_1DiscreteExteriorCalculus_1_1Property.html',1,'DGtal::DiscreteExteriorCalculus']]]
];
