var searchData=
[
  ['l1lengthestimator_9402',['L1LengthEstimator',['../classDGtal_1_1L1LengthEstimator.html',1,'DGtal']]],
  ['l1localdistance_9403',['L1LocalDistance',['../classDGtal_1_1L1LocalDistance.html',1,'DGtal']]],
  ['l2_9404',['L2',['../structDGtal_1_1L2.html',1,'DGtal']]],
  ['l2firstorderlocaldistance_9405',['L2FirstOrderLocalDistance',['../classDGtal_1_1L2FirstOrderLocalDistance.html',1,'DGtal']]],
  ['l2firstorderlocaldistancefromcells_9406',['L2FirstOrderLocalDistanceFromCells',['../classDGtal_1_1L2FirstOrderLocalDistanceFromCells.html',1,'DGtal']]],
  ['l2secondorderlocaldistance_9407',['L2SecondOrderLocalDistance',['../classDGtal_1_1L2SecondOrderLocalDistance.html',1,'DGtal']]],
  ['labelledmap_9408',['LabelledMap',['../classDGtal_1_1LabelledMap.html',1,'DGtal']]],
  ['labelledmap_3c_20value_2c_20l_2c_20tword_2c_20n_2c_20m_20_3e_9409',['LabelledMap&lt; Value, L, TWord, N, M &gt;',['../classDGtal_1_1LabelledMap.html',1,'DGtal']]],
  ['labelledmapmemfunctor_9410',['LabelledMapMemFunctor',['../structDGtal_1_1detail_1_1LabelledMapMemFunctor.html',1,'DGtal::detail']]],
  ['labels_9411',['Labels',['../classDGtal_1_1Labels.html',1,'DGtal']]],
  ['labels_3c_20l_2c_20word_20_3e_9412',['Labels&lt; L, Word &gt;',['../classDGtal_1_1Labels.html',1,'DGtal']]],
  ['lagrangeinterpolation_9413',['LagrangeInterpolation',['../classDGtal_1_1LagrangeInterpolation.html',1,'DGtal']]],
  ['lambda64function_9414',['Lambda64Function',['../structDGtal_1_1functors_1_1Lambda64Function.html',1,'DGtal::functors']]],
  ['lambdaexponentialfunction_9415',['LambdaExponentialFunction',['../structDGtal_1_1functors_1_1LambdaExponentialFunction.html',1,'DGtal::functors']]],
  ['lambdamst2d_9416',['LambdaMST2D',['../classDGtal_1_1LambdaMST2D.html',1,'DGtal']]],
  ['lambdamst2destimator_9417',['LambdaMST2DEstimator',['../classDGtal_1_1LambdaMST2DEstimator.html',1,'DGtal']]],
  ['lambdamst2destimator_3c_20z2i_3a_3aspace_2c_20dsssegmentationcomputer_2c_20tangentfromdss2dfunctor_3c_20dsssegmentationcomputer_3a_3asegmentcomputer_2c_20functors_3a_3alambda64function_20_3e_20_3e_9418',['LambdaMST2DEstimator&lt; Z2i::Space, DSSSegmentationComputer, TangentFromDSS2DFunctor&lt; DSSSegmentationComputer::SegmentComputer, functors::Lambda64Function &gt; &gt;',['../classDGtal_1_1LambdaMST2DEstimator.html',1,'DGtal']]],
  ['lambdamst3d_9419',['LambdaMST3D',['../classDGtal_1_1LambdaMST3D.html',1,'DGtal']]],
  ['lambdamst3dby2d_9420',['LambdaMST3DBy2D',['../classDGtal_1_1LambdaMST3DBy2D.html',1,'DGtal']]],
  ['lambdamst3dby2destimator_9421',['LambdaMST3DBy2DEstimator',['../classDGtal_1_1LambdaMST3DBy2DEstimator.html',1,'DGtal']]],
  ['lambdamst3dby2destimator_3c_20iterator3d_2c_20tangentfromdss3dby2dfunctor_2c_20functors_3a_3alambda64function_2c_208_20_3e_9422',['LambdaMST3DBy2DEstimator&lt; Iterator3D, TangentFromDSS3DBy2DFunctor, functors::Lambda64Function, 8 &gt;',['../classDGtal_1_1LambdaMST3DBy2DEstimator.html',1,'DGtal']]],
  ['lambdamst3destimator_9423',['LambdaMST3DEstimator',['../classDGtal_1_1LambdaMST3DEstimator.html',1,'DGtal']]],
  ['lambdamst3destimator_3c_20z3i_3a_3aspace_2c_20dsssegmentationcomputer_2c_20tangentfromdss3dfunctor_3c_20dsssegmentationcomputer_3a_3asegmentcomputer_2c_20functors_3a_3alambda64function_20_3e_2c_20dssmutefilter_3c_20typename_20dsssegmentationcomputer_3a_3asegmentcomputer_20_3e_20_3e_9424',['LambdaMST3DEstimator&lt; Z3i::Space, DSSSegmentationComputer, TangentFromDSS3DFunctor&lt; DSSSegmentationComputer::SegmentComputer, functors::Lambda64Function &gt;, DSSMuteFilter&lt; typename DSSSegmentationComputer::SegmentComputer &gt; &gt;',['../classDGtal_1_1LambdaMST3DEstimator.html',1,'DGtal']]],
  ['lambdasinfrompifunction_9425',['LambdaSinFromPiFunction',['../structDGtal_1_1functors_1_1LambdaSinFromPiFunction.html',1,'DGtal::functors']]],
  ['largetruncationfunctor_9426',['LargeTruncationFunctor',['../structDGtal_1_1functors_1_1LargeTruncationFunctor.html',1,'DGtal::functors']]],
  ['latticepolytope2d_9427',['LatticePolytope2D',['../classDGtal_1_1LatticePolytope2D.html',1,'DGtal']]],
  ['latticepolytope2d_3c_20internalspace2_20_3e_9428',['LatticePolytope2D&lt; InternalSpace2 &gt;',['../classDGtal_1_1LatticePolytope2D.html',1,'DGtal']]],
  ['latticesetbyintervals_9429',['LatticeSetByIntervals',['../classDGtal_1_1LatticeSetByIntervals.html',1,'DGtal']]],
  ['latticesetbyintervals_3c_20space_20_3e_9430',['LatticeSetByIntervals&lt; Space &gt;',['../classDGtal_1_1LatticeSetByIntervals.html',1,'DGtal']]],
  ['lcontinuitypolicy_9431',['LcontinuityPolicy',['../structDGtal_1_1LcontinuityPolicy.html',1,'DGtal']]],
  ['leftstrictunitcell_9432',['LeftStrictUnitCell',['../structDGtal_1_1BoundedLatticePolytope_1_1LeftStrictUnitCell.html',1,'DGtal::BoundedLatticePolytope']]],
  ['leftstrictunitsegment_9433',['LeftStrictUnitSegment',['../structDGtal_1_1BoundedLatticePolytope_1_1LeftStrictUnitSegment.html',1,'DGtal::BoundedLatticePolytope']]],
  ['lemniscate2d_9434',['Lemniscate2D',['../classDGtal_1_1Lemniscate2D.html',1,'DGtal']]],
  ['lessoreqthanangular_9435',['LessOrEqThanAngular',['../structDGtal_1_1experimental_1_1ChamferNorm2D_1_1LessOrEqThanAngular.html',1,'DGtal::experimental::ChamferNorm2D']]],
  ['lessthanangular_9436',['LessThanAngular',['../structDGtal_1_1experimental_1_1ChamferNorm2D_1_1LessThanAngular.html',1,'DGtal::experimental::ChamferNorm2D']]],
  ['lessthancomparable_9437',['LessThanComparable',['../structboost_1_1LessThanComparable.html',1,'boost']]],
  ['lightersternbrocot_9438',['LighterSternBrocot',['../classDGtal_1_1LighterSternBrocot.html',1,'DGtal']]],
  ['lightexplicitdigitalsurface_9439',['LightExplicitDigitalSurface',['../classDGtal_1_1LightExplicitDigitalSurface.html',1,'DGtal']]],
  ['lightimplicitdigitalsurface_9440',['LightImplicitDigitalSurface',['../classDGtal_1_1LightImplicitDigitalSurface.html',1,'DGtal']]],
  ['lightsternbrocot_9441',['LightSternBrocot',['../classDGtal_1_1LightSternBrocot.html',1,'DGtal']]],
  ['line_9442',['Line',['../structLibBoard_1_1Line.html',1,'LibBoard']]],
  ['linearalgebra_9443',['LinearAlgebra',['../structDGtal_1_1LinearAlgebra.html',1,'DGtal']]],
  ['linearizer_9444',['Linearizer',['../structDGtal_1_1Linearizer.html',1,'DGtal']]],
  ['linearizer_3c_20hyperrectdomain_3c_20tspace_20_3e_2c_20tstorageorder_20_3e_9445',['Linearizer&lt; HyperRectDomain&lt; TSpace &gt;, TStorageOrder &gt;',['../structDGtal_1_1Linearizer_3_01HyperRectDomain_3_01TSpace_01_4_00_01TStorageOrder_01_4.html',1,'DGtal']]],
  ['linearleastsquarefittingnormalvectorestimator_9446',['LinearLeastSquareFittingNormalVectorEstimator',['../classDGtal_1_1functors_1_1LinearLeastSquareFittingNormalVectorEstimator.html',1,'DGtal::functors']]],
  ['linearoperator_9447',['LinearOperator',['../classDGtal_1_1LinearOperator.html',1,'DGtal']]],
  ['lined3d_9448',['LineD3D',['../structDGtal_1_1Display3D_1_1LineD3D.html',1,'DGtal::Display3D']]],
  ['linflocaldistance_9449',['LInfLocalDistance',['../classDGtal_1_1LInfLocalDistance.html',1,'DGtal']]],
  ['linfpolicy_9450',['LinfPolicy',['../structDGtal_1_1LinfPolicy.html',1,'DGtal']]],
  ['localconvolutionnormalvectorestimator_9451',['LocalConvolutionNormalVectorEstimator',['../classDGtal_1_1deprecated_1_1LocalConvolutionNormalVectorEstimator.html',1,'DGtal::deprecated']]],
  ['localestimatorfromsurfelfunctoradapter_9452',['LocalEstimatorFromSurfelFunctorAdapter',['../classDGtal_1_1LocalEstimatorFromSurfelFunctorAdapter.html',1,'DGtal']]],
  ['log2_9453',['LOG2',['../classDGtal_1_1LOG2.html',1,'DGtal']]],
  ['log2_3c_201_20_3e_9454',['LOG2&lt; 1 &gt;',['../classDGtal_1_1LOG2_3_011_01_4.html',1,'DGtal']]],
  ['log2_3c_202_20_3e_9455',['LOG2&lt; 2 &gt;',['../classDGtal_1_1LOG2_3_012_01_4.html',1,'DGtal']]],
  ['longvolreader_9456',['LongvolReader',['../structDGtal_1_1LongvolReader.html',1,'DGtal']]],
  ['longvolwriter_9457',['LongvolWriter',['../structDGtal_1_1LongvolWriter.html',1,'DGtal']]],
  ['lpmetric_9458',['LpMetric',['../classDGtal_1_1LpMetric.html',1,'DGtal']]],
  ['lvalueiteratorconcept_9459',['LvalueIteratorConcept',['../structboost__concepts_1_1LvalueIteratorConcept.html',1,'boost_concepts']]]
];
