DGtal: digitalPolyhedronBuilder3D.cpp File Reference
digitalPolyhedronBuilder3D.cpp File Reference
DGtal Examples
#include <iostream>
#include <queue>
#include "DGtal/base/Common.h"
#include "DGtal/helpers/StdDefs.h"
#include "DGtal/io/viewers/Viewer3D.h"
#include "DGtal/shapes/Shapes.h"
#include "DGtal/shapes/SurfaceMesh.h"
#include "DGtal/io/readers/SurfaceMeshReader.h"
#include "DGtal/geometry/volumes/DigitalConvexity.h"
#include "ConfigExamples.h"
Namespaces
DGtal
DGtal is the top-level namespace which contains all DGtal functions and types.
Typedefs
typedef Z3i::Space Space
typedef Z3i::Integer Integer
typedef Z3i::KSpace KSpace
typedef Z3i::Domain Domain
typedef Z3i::SCell SCell
typedef Space::Point Point
typedef Space::RealPoint RealPoint
typedef Space::RealVector RealVector
typedef Space::Vector Vector
typedef std::vector< Point > PointRange
Functions
int main (int argc, char **argv)
Detailed Description
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jacques-Olivier Lachaud (jacqu.nosp@m.es-o.nosp@m.livie.nosp@m.r.la.nosp@m.chaud.nosp@m.@uni.nosp@m.v-sav.nosp@m.oie..nosp@m.fr) Laboratory of Mathematics (CNRS, UMR 5127), University of Savoie, France
Date
2022/06/20
An example file named digitalPolyhedronBuilder3D
This file is part of the DGtal library.
Definition in file digitalPolyhedronBuilder3D.cpp.
Typedef Documentation
Domain
typedef Z3i::Domain Domain
Definition at line 78 of file digitalPolyhedronBuilder3D.cpp.
Integer
typedef Z3i::Integer Integer
Definition at line 76 of file digitalPolyhedronBuilder3D.cpp.
KSpace
typedef Z3i::KSpace KSpace
Definition at line 77 of file digitalPolyhedronBuilder3D.cpp.
Point
typedef Space::Point Point
Definition at line 80 of file digitalPolyhedronBuilder3D.cpp.
PointRange
typedef std::vector<Point> PointRange
Examples
geometry/tools/exampleAlphaShape.cpp, geometry/volumes/checkFullConvexityTheorems.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, and geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp.
Definition at line 84 of file digitalPolyhedronBuilder3D.cpp.
RealPoint
typedef Space::RealPoint RealPoint
Definition at line 81 of file digitalPolyhedronBuilder3D.cpp.
RealVector
typedef Space::RealVector RealVector
Examples
dec/exampleHeatLaplace.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/surfaces/dvcm-3d.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/dvcm-2d.cpp, geometry/volumes/fullConvexitySphereGeodesics.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, images/exampleRigidtransformation2d.cpp, images/exampleRigidtransformation3d.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 82 of file digitalPolyhedronBuilder3D.cpp.
SCell
typedef Z3i::SCell SCell
Examples
dec/exampleDECSurface.cpp, dec/exampleDiscreteExteriorCalculusUsage.cpp, geometry/volumes/digitalPolyhedronBuilder3D.cpp, geometry/volumes/distance/exampleFMM3D.cpp, geometry/volumes/fullConvexityShortestPaths3D.cpp, geometry/volumes/fullConvexitySphereGeodesics.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, io/viewers/viewer3D-10-interaction.cpp, topology/ctopo-2-3d.cpp, topology/ctopo-2.cpp, topology/ctopo-fillContours.cpp, topology/volScanBoundary.cpp, and tutorial-examples/FMMErosion.cpp.
Definition at line 79 of file digitalPolyhedronBuilder3D.cpp.
Space
typedef Z3i::Space Space
Definition at line 75 of file digitalPolyhedronBuilder3D.cpp.
Vector
typedef Space::Vector Vector
Definition at line 83 of file digitalPolyhedronBuilder3D.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 86 of file digitalPolyhedronBuilder3D.cpp.
 {
   trace.info() << "Usage: " << argv[ 0 ] << " <input.obj> <h> <view>" << std::endl;
   trace.info() << "\tComputes a digital polyhedron from an OBJ file" << std::endl;
   trace.info() << "\t- input.obj: choose your favorite mesh" << std::endl;
   trace.info() << "\t- h [==1]: the digitization gridstep" << std::endl;
   trace.info() << "\t- view [==7]: display vertices(1), edges(2), faces(4)" << std::endl;
   string filename = examplesPath + "samples/lion.obj";
   std::string  fn = argc > 1 ? argv[ 1 ]         : filename; //< vol filename
   double        h = argc > 2 ? atof( argv[ 2 ] ) : 1.0;
   int        view = argc > 3 ? atoi( argv[ 3 ] ) : 7;
   // Read OBJ file
   std::ifstream input( fn.c_str() );
   DGtal::SurfaceMesh< RealPoint, RealVector > surfmesh;
   bool ok = SurfaceMeshReader< RealPoint, RealVector >::readOBJ( input, surfmesh );
   if ( ! ok )
     {
       trace.error() << "Unable to read obj file : " << fn << std::endl;
       return 1;
     }
   QApplication application(argc,argv);
   typedef Viewer3D<Space,KSpace> MViewer;
   MViewer viewer;
   viewer.setWindowTitle("digitalPolyhedronBuilder3D");
   viewer.show();
   Point lo(-500,-500,-500);
   Point up(500,500,500);
   DigitalConvexity< KSpace > dconv( lo, up );
   typedef DigitalConvexity< KSpace >::EnvelopeAlgorithm Algorithm;
   auto vertices = std::vector<Point>( surfmesh.nbVertices() );
   for ( auto v : surfmesh )
     {
       RealPoint p = (1.0 / h) * surfmesh.position( v );
       Point q ( (Integer) round( p[ 0 ] ),
                 (Integer) round( p[ 1 ] ),
                 (Integer) round( p[ 2 ] ) );
       vertices[ v ] = q;
     }
   std::set< Point > faces_set, edges_set;
   auto faceVertices = surfmesh.allIncidentVertices();
   auto edgeVertices = surfmesh.allEdgeVertices();
   trace.beginBlock( "Computing polyhedron" );
   for ( int f = 0; f < surfmesh.nbFaces(); ++f )
     {
       PointRange X;
       for ( auto v : faceVertices[ f ] )
         X.push_back( vertices[ v ] );
       auto F = dconv.envelope( X, Algorithm::DIRECT );
       faces_set.insert( F.cbegin(), F.cend() );
     }
   for ( int e = 0; e < surfmesh.nbEdges(); ++e )
     {
       PointRange X =
         { vertices[ edgeVertices[ e ].first  ],
           vertices[ edgeVertices[ e ].second ] };
       auto E = dconv.envelope( X, Algorithm::DIRECT );
       edges_set.insert( E.cbegin(), E.cend() );
     }
   trace.endBlock();
   std::vector< Point > face_points, edge_points;
   std::vector< Point > vertex_points = vertices;
   std::sort( vertex_points.begin(), vertex_points.end() );
   std::set_difference( faces_set.cbegin(), faces_set.cend(),
                        edges_set.cbegin(), edges_set.cend(),
                        std::back_inserter( face_points ) );
   std::set_difference( edges_set.cbegin(), edges_set.cend(),
                        vertex_points.cbegin(), vertex_points.cend(),
                        std::back_inserter( edge_points ) );
   auto total = vertex_points.size() + edge_points.size() + face_points.size();
   trace.info() << "#vertex points=" << vertex_points.size() << std::endl;
   trace.info() << "#edge   points=" << edge_points.size() << std::endl;
   trace.info() << "#face   points=" << face_points.size() << std::endl;
   trace.info() << "#total  points=" << total << std::endl;
   // display everything
   Color colors[] = { Color::Black, Color( 100, 100, 100 ), Color( 200, 200, 200 ) };
   if ( view & 0x1 )
     {
       viewer.setLineColor( colors[ 0 ] );
       viewer.setFillColor( colors[ 0 ] );
       for ( auto p : vertices ) viewer << p;
     }
   if ( view & 0x2 )
     {
       viewer.setLineColor( colors[ 1 ] );
       viewer.setFillColor( colors[ 1 ] );
       for ( auto p : edge_points ) viewer << p;
     }
   if ( view & 0x4 )
     {
       viewer.setLineColor( colors[ 2 ] );
       viewer.setFillColor( colors[ 2 ] );
       for ( auto p : face_points ) viewer << p;
     }
   viewer << MViewer::updateDisplay;
   return application.exec();
 }
References DGtal::SurfaceMesh< TRealPoint, TRealVector >::allEdgeVertices(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::allIncidentVertices(), DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::DigitalConvexity< TKSpace >::envelope(), DGtal::Trace::error(), DGtal::Trace::info(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbEdges(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbFaces(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::nbVertices(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::position(), DGtal::Viewer3D< TSpace, TKSpace >::show(), and DGtal::trace.