DGtal: DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue > Struct Template Reference
DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue > Struct Template Reference
Aim: stores an arbitrary measure on a SurfaceMesh object. The measure can be spread onto its vertices, edges, or faces. This class is notably used by CorrectedNormalCurrentComputer and NormalCycleComputer to store the curvature measures, which may be located on different cells. The measure can be scalar or any other summable type (see template parameter TValue).
#include <DGtal/geometry/meshes/SurfaceMeshMeasure.h>
Public Types
typedef TRealPoint RealPoint
typedef TRealVector RealVector
typedef TValue Value
typedef SurfaceMeshMeasure< RealPoint, RealVector, Value > Self
typedef DGtal::SurfaceMesh< RealPoint, RealVector > SurfaceMesh
typedef SurfaceMesh::Index Index
typedef SurfaceMesh::Size Size
typedef SurfaceMesh::Vertex Vertex
typedef SurfaceMesh::Edge Edge
typedef SurfaceMesh::Face Face
typedef std::vector< Value > Values
typedef RealVector::Component Scalar
typedef std::pair< Face, Scalar > WeightedFace
typedef std::pair< Edge, Scalar > WeightedEdge
typedef std::pair< Vertex, Scalar > WeightedVertex
typedef std::vector< Vertex > Vertices
The type that defines a range of vertices.
typedef std::vector< Edge > Edges
The type that defines a range of edges.
typedef std::vector< Face > Faces
The type that defines a range of faces.
typedef std::vector< WeightedVertex > WeightedVertices
typedef std::vector< WeightedEdge > WeightedEdges
typedef std::vector< WeightedFace > WeightedFaces
Public Member Functions
Standard services (construction, initialization, assignment)
SurfaceMeshMeasure (ConstAlias< SurfaceMesh > aMesh=nullptr, Value zero_value=Value())
const SurfaceMesh * meshPtr () const
const Values & kMeasures (Dimension dim) const
Values & kMeasures (Dimension dim)
Measure services
Value measure () const
Value measure (const RealPoint &x, Scalar r, Face f) const
Value vertexMeasure (Vertex v) const
Value vertexMeasure (const Vertices &vertices) const
Value vertexMeasure (const WeightedVertices &wvertices) const
Value edgeMeasure (Edge e) const
Value edgeMeasure (const Edges &edges) const
Value edgeMeasure (const WeightedEdges &wedges) const
Value faceMeasure (Face f) const
Value faceMeasure (const Faces &faces) const
Value faceMeasure (const WeightedFaces &wfaces) const
Data Fields
Values vertex_measures
Stores the scalar curvature measure per indexed vertex element.
Values edge_measures
Stores the scalar curvature measure per indexed edge element.
Values face_measures
Stores the scalar curvature measure per indexed face element.
Static Public Attributes
static const Dimension dimension = RealPoint::dimension
Protected Attributes
const SurfaceMesh * myMeshPtr
A pointer to the mesh over which computations are done.
Value myZero
Zero value for the given type.
Detailed Description
template<typename TRealPoint, typename TRealVector, typename TValue>
struct DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >
Aim: stores an arbitrary measure on a SurfaceMesh object. The measure can be spread onto its vertices, edges, or faces. This class is notably used by CorrectedNormalCurrentComputer and NormalCycleComputer to store the curvature measures, which may be located on different cells. The measure can be scalar or any other summable type (see template parameter TValue).
Description of template class 'SurfaceMeshMeasure'
The common workflow to use this object is to access its public array data with a call to SurfaceMeshMeasure::kMeasures, then resize it and fill in its values. Of course, the indices used to number cells in the SurfaceMesh are the same as the indices used to store the measure associated to cells.
ScalarMeasure mu0(&myMesh, 0.0);
auto& face_mu0 = mu0.kMeasures(2);
face_mu0.resize(myMesh.nbFaces());
...
Afterwards, you can access the global measure of a set of cells specified by their indices through convenient methods like SurfaceMeshMeasure::vertexMeasure, SurfaceMeshMeasure::edgeMeasure, SurfaceMeshMeasure::faceMeasure, with potential weights.
Template Parameters
TRealPoint an arbitrary model of RealPoint.
TRealVector an arbitrary model of RealVector.
TValue an arbitrary model of CCommutativeRing
Definition at line 82 of file SurfaceMeshMeasure.h.
Member Typedef Documentation
Edge
template<typename TRealPoint , typename TRealVector , typename TValue > typedef SurfaceMesh::Edge DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Edge
Definition at line 99 of file SurfaceMeshMeasure.h.
Edges
template<typename TRealPoint , typename TRealVector , typename TValue > typedef std::vector< Edge > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Edges
The type that defines a range of edges.
Definition at line 109 of file SurfaceMeshMeasure.h.
Face
template<typename TRealPoint , typename TRealVector , typename TValue > typedef SurfaceMesh::Face DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Face
Definition at line 100 of file SurfaceMeshMeasure.h.
Faces
template<typename TRealPoint , typename TRealVector , typename TValue > typedef std::vector< Face > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Faces
The type that defines a range of faces.
Definition at line 111 of file SurfaceMeshMeasure.h.
Index
template<typename TRealPoint , typename TRealVector , typename TValue > typedef SurfaceMesh::Index DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Index
Definition at line 96 of file SurfaceMeshMeasure.h.
RealPoint
template<typename TRealPoint , typename TRealVector , typename TValue > typedef TRealPoint DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::RealPoint
Definition at line 87 of file SurfaceMeshMeasure.h.
RealVector
template<typename TRealPoint , typename TRealVector , typename TValue > typedef TRealVector DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::RealVector
Definition at line 88 of file SurfaceMeshMeasure.h.
Scalar
template<typename TRealPoint , typename TRealVector , typename TValue > typedef RealVector::Component DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Scalar
Definition at line 102 of file SurfaceMeshMeasure.h.
Self
template<typename TRealPoint , typename TRealVector , typename TValue > typedef SurfaceMeshMeasure< RealPoint, RealVector, Value > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Self
Definition at line 90 of file SurfaceMeshMeasure.h.
Size
template<typename TRealPoint , typename TRealVector , typename TValue > typedef SurfaceMesh::Size DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Size
Definition at line 97 of file SurfaceMeshMeasure.h.
SurfaceMesh
template<typename TRealPoint , typename TRealVector , typename TValue > typedef DGtal::SurfaceMesh< RealPoint, RealVector > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::SurfaceMesh
Definition at line 95 of file SurfaceMeshMeasure.h.
Value
template<typename TRealPoint , typename TRealVector , typename TValue > typedef TValue DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Value
Definition at line 89 of file SurfaceMeshMeasure.h.
Values
template<typename TRealPoint , typename TRealVector , typename TValue > typedef std::vector< Value > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Values
Definition at line 101 of file SurfaceMeshMeasure.h.
Vertex
template<typename TRealPoint , typename TRealVector , typename TValue > typedef SurfaceMesh::Vertex DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Vertex
Definition at line 98 of file SurfaceMeshMeasure.h.
Vertices
template<typename TRealPoint , typename TRealVector , typename TValue > typedef std::vector< Vertex > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::Vertices
The type that defines a range of vertices.
Definition at line 107 of file SurfaceMeshMeasure.h.
WeightedEdge
template<typename TRealPoint , typename TRealVector , typename TValue > typedef std::pair< Edge, Scalar > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::WeightedEdge
Definition at line 104 of file SurfaceMeshMeasure.h.
WeightedEdges
template<typename TRealPoint , typename TRealVector , typename TValue > typedef std::vector< WeightedEdge > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::WeightedEdges
Definition at line 113 of file SurfaceMeshMeasure.h.
WeightedFace
template<typename TRealPoint , typename TRealVector , typename TValue > typedef std::pair< Face, Scalar > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::WeightedFace
Definition at line 103 of file SurfaceMeshMeasure.h.
WeightedFaces
template<typename TRealPoint , typename TRealVector , typename TValue > typedef std::vector< WeightedFace > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::WeightedFaces
Definition at line 114 of file SurfaceMeshMeasure.h.
WeightedVertex
template<typename TRealPoint , typename TRealVector , typename TValue > typedef std::pair< Vertex, Scalar > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::WeightedVertex
Definition at line 105 of file SurfaceMeshMeasure.h.
WeightedVertices
template<typename TRealPoint , typename TRealVector , typename TValue > typedef std::vector< WeightedVertex > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::WeightedVertices
Definition at line 112 of file SurfaceMeshMeasure.h.
Constructor & Destructor Documentation
SurfaceMeshMeasure()
template<typename TRealPoint , typename TRealVector , typename TValue > DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::SurfaceMeshMeasure (ConstAlias< SurfaceMesh > aMesh = nullptr, Value zero_value = Value()) inline
Constructor from mesh.
Parameters
aMesh any simplified mesh that is referenced in this object.
zero_value the value 0 for the specified type TValue.
Definition at line 125 of file SurfaceMeshMeasure.h.
       : myMeshPtr( &aMesh ), myZero( zero_value ) {}
Member Function Documentation
edgeMeasure() [1/3]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edgeMeasure (const Edges & edges) const inline
Parameters
edges any range of (valid) edge indices.
Returns
its measure.
Definition at line 231 of file SurfaceMeshMeasure.h.
     {
       Value m = myZero;
       if ( edge_measures.empty() ) return m;
       for ( auto&& e : edges )  m += edge_measures[ e ];
       return m;
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edge_measures, and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myZero.
edgeMeasure() [2/3]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edgeMeasure (const WeightedEdges & wedges) const inline
Parameters
wedges any range of weighted (valid) edge indices.
Returns
its measure.
Definition at line 241 of file SurfaceMeshMeasure.h.
     {
       Value m = myZero;
       if ( edge_measures.empty() ) return m;
       for ( auto&& e : wedges )  m += edge_measures[ e.first ] * e.second;
       return m;
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edge_measures, and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myZero.
edgeMeasure() [3/3]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edgeMeasure (Edge e) const inline
Parameters
e any edge index.
Returns
its measure.
Definition at line 224 of file SurfaceMeshMeasure.h.
     {
       return e < edge_measures.size() ? edge_measures[ e ] : Value();
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edge_measures.
Referenced by DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::measure().
faceMeasure() [1/3]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::faceMeasure (const Faces & faces) const inline
Parameters
faces any range of (valid) face indices.
Returns
its measure.
Definition at line 258 of file SurfaceMeshMeasure.h.
     {
       Value m = myZero;
       if ( face_measures.empty() ) return m;
       for ( auto&& v : faces )  m += face_measures[ v ];
       return m;
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::face_measures, and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myZero.
faceMeasure() [2/3]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::faceMeasure (const WeightedFaces & wfaces) const inline
Parameters
wfaces any range of weighted (valid) face indices.
Returns
its measure.
Definition at line 268 of file SurfaceMeshMeasure.h.
     {
       Value m = myZero;
       if ( face_measures.empty() ) return m;
       for ( auto&& v : wfaces )  m += face_measures[ v.first ] * v.second;
       return m;
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::face_measures, and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myZero.
faceMeasure() [3/3]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::faceMeasure (Face f) const inline
Parameters
f any face index.
Returns
its measure.
Definition at line 251 of file SurfaceMeshMeasure.h.
     {
       return f < face_measures.size() ? face_measures[ f ] : Value();
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::face_measures.
Referenced by DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::measure().
kMeasures() [1/2]
template<typename TRealPoint , typename TRealVector , typename TValue > Values& DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::kMeasures (Dimension dim) inline
Parameters
dim the dimension of the cells where the measures are defined, among 0: vertex, 1: edges, 2: faces.
Returns
a reference to the dim-measures.
Definition at line 147 of file SurfaceMeshMeasure.h.
     {
       return ( dim == 0 ) ? vertex_measures
         : ( (dim == 1 ) ? edge_measures : face_measures );
     }
References dim(), DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edge_measures, DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::face_measures, and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertex_measures.
kMeasures() [2/2]
template<typename TRealPoint , typename TRealVector , typename TValue > const Values& DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::kMeasures (Dimension dim) const inline
Parameters
dim the dimension of the cells where the measures are defined, among 0: vertex, 1: edges, 2: faces.
Returns
a const reference to the dim-measures.
Definition at line 139 of file SurfaceMeshMeasure.h.
     {
       return ( dim == 0 ) ? vertex_measures
         : ( (dim == 1 ) ? edge_measures : face_measures );
     }
References dim(), DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edge_measures, DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::face_measures, and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertex_measures.
measure() [1/2]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::measure () const inline
Returns
the total measure (i.e. onto the whole space).
Definition at line 161 of file SurfaceMeshMeasure.h.
     {
       Value m = myZero;
       for ( auto&& lm : vertex_measures ) m += lm;
       for ( auto&& lm : edge_measures   ) m += lm;
       for ( auto&& lm : face_measures   ) m += lm;
       return m;
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edge_measures, DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::face_measures, DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myZero, and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertex_measures.
measure() [2/2]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::measure (const RealPoint & x, Scalar r, Face f) const inline
Computes the total measure on the ball of center x and radius r. The center x must lie on or close to the face f (as a hint to compute cells in the given ball).
Parameters
x the position where the ball is centered.
r the radius of the ball.
f the face where center point x lies.
Definition at line 176 of file SurfaceMeshMeasure.h.
     {
       if ( vertex_measures.empty() && edge_measures.empty() )
         {
           WeightedFaces
             faces = myMeshPtr->computeFacesInclusionsInBall( r, f, x );
           return faceMeasure( faces );
         }
       else
         {
           std::tuple< Vertices, WeightedEdges, WeightedFaces >
             wcells = myMeshPtr->computeCellsInclusionsInBall( r, f, x );
           Value m = vertexMeasure( std::get< 0 >( wcells ) );
           m      += edgeMeasure  ( std::get< 1 >( wcells ) );
           m      += faceMeasure  ( std::get< 2 >( wcells ) );
           return m;
         }
     }
References DGtal::SurfaceMesh< TRealPoint, TRealVector >::computeCellsInclusionsInBall(), DGtal::SurfaceMesh< TRealPoint, TRealVector >::computeFacesInclusionsInBall(), DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edge_measures, DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edgeMeasure(), DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::faceMeasure(), DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myMeshPtr, DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertex_measures, and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertexMeasure().
meshPtr()
template<typename TRealPoint , typename TRealVector , typename TValue > const SurfaceMesh* DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::meshPtr () const inline
Returns
a pointer to the associated mesh or nullptr if the measure is not valid.
Definition at line 131 of file SurfaceMeshMeasure.h.
     {
       return myMeshPtr;
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myMeshPtr.
vertexMeasure() [1/3]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertexMeasure (const Vertices & vertices) const inline
Parameters
vertices any range of (valid) vertex indices.
Returns
its measure.
Definition at line 204 of file SurfaceMeshMeasure.h.
     {
       Value m = myZero;
       if ( vertex_measures.empty() ) return m;
       for ( auto&& v : vertices )  m += vertex_measures[ v ];
       return m;
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myZero, and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertex_measures.
vertexMeasure() [2/3]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertexMeasure (const WeightedVertices & wvertices) const inline
Parameters
wvertices any range of weighted (valid) vertex indices.
Returns
its measure.
Definition at line 214 of file SurfaceMeshMeasure.h.
     {
       Value m = myZero;
       if ( vertex_measures.empty() ) return m;
       for ( auto&& v : wvertices )  m += vertex_measures[ v.first ] * v.second;
       return m;
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myZero, and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertex_measures.
vertexMeasure() [3/3]
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertexMeasure (Vertex v) const inline
Parameters
v any vertex index.
Returns
its measure.
Definition at line 197 of file SurfaceMeshMeasure.h.
     {
       return v < vertex_measures.size() ? vertex_measures[ v ] : Value();
     }
References DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertex_measures.
Referenced by DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::measure().
Field Documentation
dimension
template<typename TRealPoint , typename TRealVector , typename TValue > const Dimension DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::dimension = RealPoint::dimension static
Definition at line 115 of file SurfaceMeshMeasure.h.
edge_measures
template<typename TRealPoint , typename TRealVector , typename TValue > Values DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edge_measures
Stores the scalar curvature measure per indexed edge element.
Definition at line 283 of file SurfaceMeshMeasure.h.
Referenced by DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edgeMeasure(), DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::kMeasures(), and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::measure().
face_measures
template<typename TRealPoint , typename TRealVector , typename TValue > Values DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::face_measures
Stores the scalar curvature measure per indexed face element.
Definition at line 285 of file SurfaceMeshMeasure.h.
Referenced by DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::faceMeasure(), DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::kMeasures(), and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::measure().
myMeshPtr
template<typename TRealPoint , typename TRealVector , typename TValue > const SurfaceMesh* DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myMeshPtr protected
A pointer to the mesh over which computations are done.
Definition at line 290 of file SurfaceMeshMeasure.h.
Referenced by DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::measure(), and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::meshPtr().
myZero
template<typename TRealPoint , typename TRealVector , typename TValue > Value DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::myZero protected
Zero value for the given type.
Definition at line 292 of file SurfaceMeshMeasure.h.
Referenced by DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::edgeMeasure(), DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::faceMeasure(), DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::measure(), and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertexMeasure().
vertex_measures
template<typename TRealPoint , typename TRealVector , typename TValue > Values DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertex_measures
Stores the scalar curvature measure per indexed vertex element.
Definition at line 281 of file SurfaceMeshMeasure.h.
Referenced by DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::kMeasures(), DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::measure(), and DGtal::SurfaceMeshMeasure< TRealPoint, TRealVector, TValue >::vertexMeasure().
The documentation for this struct was generated from the following file:
SurfaceMeshMeasure.h