DGtal: DGtal::CDLR< TSpace, TInputValue, TOutputValue > Class Template Reference
DGtal::CDLR< TSpace, TInputValue, TOutputValue > Class Template Reference
CDLR : Rotation with Discrete Line Reflections,.
#include <DGtal/images/bijectiveRotations/CDLR.h>
Public Member Functions
CDLR (double ang, TOutputValue ptCenter, std::shared_ptr< Policy< TSpace, HyperRectDomain< TSpace >, CDLR_naiverotation< TSpace >>> policy)
double angle () const
void set_angle (const double new_angle)
void dslSolver (double ang, TOutputValue ptCenter)
TOutputValue center () const
TOutputValue & center ()
TOutputValue rotate (const TInputValue &p) const
TOutputValue operator() (const TInputValue &p) const
template<typename Img >
Img rotateImage (Img img) const
std::string tostring () const
template<typename TImage >
TImage rotateImage (const TImage img) const
Protected Attributes
double my_angle
The angle of rotation.
TOutputValue my_center
The center of rotation.
CDLR_naiverotation< TSpace, TInputValue, TOutputValue > my_naive_rdlr_rotation
std::shared_ptr< Policy< TSpace, HyperRectDomain< TSpace >, CDLR_naiverotation< TSpace > > > my_policy
Private Attributes
double a
DSL specific variables, see Andres paper.
double b
double my_minAngle
Detailed Description
template<typename TSpace, typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point>
class DGtal::CDLR< TSpace, TInputValue, TOutputValue >
CDLR : Rotation with Discrete Line Reflections,.
Description of template struct CDLR
Template Parameters
TSpace a 2 dimensional space.
TInputValue type of the input point e.g., TSpace::RealPoint.
TOutputValue type of the output point e.g., TSpace::Point
Definition at line 53 of file CDLR.h.
Constructor & Destructor Documentation
CDLR()
template<typename TSpace , typename TInputValue , typename TOutputValue > DGtal::CDLR< TSpace, TInputValue, TOutputValue >::CDLR (double ang, TOutputValue ptCenter, std::shared_ptr< Policy< TSpace, HyperRectDomain< TSpace >, CDLR_naiverotation< TSpace >>> policy)
CDLR Constructor.
Parameters
ang the angle given in radians.
ptCenter the center of rotation.
policy either Linf, L2, Lcontinuity, see Policy
Definition at line 115 of file CDLR.h.
                                                                                                                                                                                         :my_angle(ang),my_center(ptCenter),my_naive_rdlr_rotation(ang,ptCenter,0.),my_policy(policy){
         dslSolver(ang,ptCenter);
     }
References DGtal::CDLR< TSpace, TInputValue, TOutputValue >::dslSolver().
Member Function Documentation
angle()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> double DGtal::CDLR< TSpace, TInputValue, TOutputValue >::angle () const inline
Returns
the angle of rotation.
Definition at line 64 of file CDLR.h.
 {return my_angle;};
References DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_angle.
center() [1/2]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> TOutputValue& DGtal::CDLR< TSpace, TInputValue, TOutputValue >::center () inline
Returns
a reference to the centre of rotation
Definition at line 81 of file CDLR.h.
 {return my_center;};
References DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_center.
center() [2/2]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::CDLR< TSpace, TInputValue, TOutputValue >::center () const inline
Returns
the centre of rotation
Definition at line 79 of file CDLR.h.
 {return my_center;};
References DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_center.
dslSolver()
template<typename TSpace , typename TInputValue , typename TOutputValue > void DGtal::CDLR< TSpace, TInputValue, TOutputValue >::dslSolver (double ang, TOutputValue ptCenter)
initialisation function to find the composition of Discrete Line Reflection that minimises the sum of linf and lcontinuity
look for the pair of reflections that minimizes the Linf and Lcontinuity norm
Definition at line 120 of file CDLR.h.
{
         a = std::sin(ang/2.0);
         b = std::cos(ang/2.0);
         TInputValue origin(0,0);
         DGtal::functors::ForwardRigidTransformation2D<TSpace,TInputValue,DGtal::SpaceND< 2, DGtal::int32_t >::RealPoint,DGtal::functors::Identity> euclideanRot(my_center,my_angle,origin);
         double errorMinAlpha = 200.*200;
         int N = 200;
         // create the domain
         TOutputValue A(0,0);
         TOutputValue B(1000,1000);
         HyperRectDomain<TSpace> my_domain(A,B);
         std::vector<double> mix_errors;
         std::vector<double> angles;
         for(int k=0;k<N;++k){
             double alphaCourant = -M_PI_2 + (k*M_PI_2)/N;
             angles.push_back(alphaCourant);
             // compute both reflections and get both the Linf and Lcontinuity errors
             std::vector<double> linf_per_image;
             my_naive_rdlr_rotation.set_startingAngle(alphaCourant);
             double error = my_policy->evaluate(my_domain,my_naive_rdlr_rotation,my_angle,my_center);
             mix_errors.push_back(error);
         }
         for(int idxImages = 0 ; idxImages < mix_errors.size() ; idxImages++) {
             if(mix_errors[idxImages] < errorMinAlpha) {
                 errorMinAlpha = mix_errors[idxImages];
                 my_minAngle = angles[idxImages];
             }
         }
     }
Referenced by DGtal::CDLR< TSpace, TInputValue, TOutputValue >::CDLR(), and DGtal::CDLR< TSpace, TInputValue, TOutputValue >::set_angle().
operator()()
template<typename TSpace , typename TInputValue , typename TOutputValue > TOutputValue DGtal::CDLR< TSpace, TInputValue, TOutputValue >::operator() (const TInputValue & p) const
Definition at line 171 of file CDLR.h.
{
         return my_naive_rdlr_rotation.reflect(my_minAngle+(my_angle),my_center,my_naive_rdlr_rotation.reflect(my_minAngle,my_center,p-my_center))+my_center;
     }
rotate()
template<typename TSpace , typename TInputValue , typename TOutputValue > TOutputValue DGtal::CDLR< TSpace, TInputValue, TOutputValue >::rotate (const TInputValue & p) const
Parameters
p a lattice point
Returns
the rotation of the point p according to the current angle and center.
Definition at line 160 of file CDLR.h.
{
         return this->operator()(p);
     }
rotateImage() [1/2]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> template<typename TImage > TImage DGtal::CDLR< TSpace, TInputValue, TOutputValue >::rotateImage (const TImage img) const
Definition at line 178 of file CDLR.h.
{
         typedef typename TImage::Domain TDomain;
         typedef DGtal::functors::DomainRigidTransformation2D < typename TImage::Domain, DGtal::CDLR<TSpace>> MyDomainTransformer;
         typedef std::pair < typename TSpace::Point, typename TSpace::Point > Bounds;
         typename TSpace::Point bottomLeft(-2,-2);
         typename TSpace::Point topRight(2,2);
         MyDomainTransformer domainTransformer ( *this );
         Bounds bounds = domainTransformer ( img.domain() );
         TDomain transformedDomain ( bounds.first+bottomLeft, bounds.second+topRight );
         TImage rotatedImage ( transformedDomain );
         for (typename TDomain::ConstIterator it = img.domain().begin(); it != img.domain().end(); ++it )
         {
             rotatedImage.setValue((*this)(*it),img(*it));
         }
         return rotatedImage;
     }
rotateImage() [2/2]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> template<typename Img > Img DGtal::CDLR< TSpace, TInputValue, TOutputValue >::rotateImage (Img img) const
set_angle()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> void DGtal::CDLR< TSpace, TInputValue, TOutputValue >::set_angle (const double new_angle) inline
Returns
set the angle of rotation and call the composition of reflections solver.
Definition at line 66 of file CDLR.h.
{
             my_angle=new_angle;
             my_naive_rdlr_rotation.set_angle(new_angle);
             dslSolver(new_angle,my_center);
         }
References DGtal::CDLR< TSpace, TInputValue, TOutputValue >::dslSolver(), DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_angle, DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_center, and DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_naive_rdlr_rotation.
tostring()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> std::string DGtal::CDLR< TSpace, TInputValue, TOutputValue >::tostring () const inline
Definition at line 92 of file CDLR.h.
{
             return {"CDLR"};
         }
Field Documentation
a
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> double DGtal::CDLR< TSpace, TInputValue, TOutputValue >::a private
DSL specific variables, see Andres paper.
Definition at line 109 of file CDLR.h.
b
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> double DGtal::CDLR< TSpace, TInputValue, TOutputValue >::b private
Definition at line 110 of file CDLR.h.
my_angle
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> double DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_angle protected
The angle of rotation.
Definition at line 98 of file CDLR.h.
Referenced by DGtal::CDLR< TSpace, TInputValue, TOutputValue >::angle(), and DGtal::CDLR< TSpace, TInputValue, TOutputValue >::set_angle().
my_center
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_center protected
The center of rotation.
Definition at line 100 of file CDLR.h.
Referenced by DGtal::CDLR< TSpace, TInputValue, TOutputValue >::center(), and DGtal::CDLR< TSpace, TInputValue, TOutputValue >::set_angle().
my_minAngle
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> double DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_minAngle private
Definition at line 111 of file CDLR.h.
my_naive_rdlr_rotation
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> CDLR_naiverotation<TSpace,TInputValue,TOutputValue> DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_naive_rdlr_rotation protected
Definition at line 104 of file CDLR.h.
Referenced by DGtal::CDLR< TSpace, TInputValue, TOutputValue >::set_angle().
my_policy
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> std::shared_ptr<Policy<TSpace,HyperRectDomain< TSpace>,CDLR_naiverotation<TSpace> > > DGtal::CDLR< TSpace, TInputValue, TOutputValue >::my_policy protected
Definition at line 105 of file CDLR.h.
The documentation for this class was generated from the following file:
CDLR.h