DGtal: DGtal::RBC_vec< TSpace, TInputValue, TOutputValue > Struct Template Reference
DGtal::RBC_vec< TSpace, TInputValue, TOutputValue > Struct Template Reference
RBC : Bijective Rotation through Circles.
#include <DGtal/images/bijectiveRotations/RBC_vec.h>
Public Types
typedef std::vector< TOutputValue > Circle
Public Member Functions
RBC_vec (int max_radius, bool smart=false)
void init (int R, bool smart)
double angle () const
double & setAngle ()
TOutputValue center () const
TOutputValue & center ()
TOutputValue rotate (TInputValue p) const
TOutputValue operator() (const TInputValue &aInput) const
std::size_t size () const
const Circle & circle (int r) const
Static Public Member Functions
static Circle computeCircle (int r)
Data Fields
std::vector< Circle > circles
std::map< TOutputValue, TOutputValue > point2circle
Protected Attributes
double my_angle
The angle of rotation.
TOutputValue my_center
The center of rotation.
Detailed Description
template<typename TSpace, typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point>
struct DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >
RBC : Bijective Rotation through Circles.
Description of template struct RBC_vec
Template Parameters
TSpace a 2 dimensional space.
TInputValue type of the input point e.g., TSpace::RealPoint.
TOutputValue type of the output point e.g., TSpace::Point
Definition at line 56 of file RBC_vec.h.
Member Typedef Documentation
Circle
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> typedef std::vector< TOutputValue > DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::Circle
Definition at line 57 of file RBC_vec.h.
Constructor & Destructor Documentation
RBC_vec()
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::RBC_vec (int max_radius, bool smart = false) inline
Constructor
Parameters
max_radius the maximal distance of a point to the center of rotation.
smart when 'true', tries to regularize the number of points of each circle, when 'false' each circle contains the point between distance r (included) and r+1 (excluded).
Definition at line 72 of file RBC_vec.h.
{
             init( max_radius, smart );
             my_angle = 0.0;
             my_center = TOutputValue( 0, 0 );
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::init(), DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::my_angle, and DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::my_center.
Member Function Documentation
angle()
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> double DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::angle () const inline
Returns
the angle of rotation.
Definition at line 138 of file RBC_vec.h.
{
             return my_angle;
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::my_angle.
center() [1/2]
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> TOutputValue& DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::center () inline
Returns
a reference to the centre of rotation
Definition at line 150 of file RBC_vec.h.
{
             return my_center;
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::my_center.
center() [2/2]
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::center () const inline
Returns
the centre of rotation
Definition at line 146 of file RBC_vec.h.
{
             return my_center;
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::my_center.
Referenced by main().
circle()
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> const Circle& DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::circle (int r) const inline
Parameters
r an integer smaller than nbCircles().
Returns
the number of circles
Definition at line 183 of file RBC_vec.h.
{
             return circles[ r ];
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::circles.
Referenced by DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::computeCircle(), and DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::rotate().
computeCircle()
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> static Circle DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::computeCircle (int r) inline static
Parameters
r an integer specifying the digital radius of the circle.
Returns
the points lying in the circle between radius r (included) and r+1 (excluded)
Definition at line 190 of file RBC_vec.h.
{
             int d2_lo = r*r;
             int d2_up = (r+1)*(r+1);
             TOutputValue start( r, 0 );
             Circle circle;
             TOutputValue current = start;
             do {
                 circle.push_back( current );
                 auto V = nextNeighbors<TOutputValue>( current );
                 std::vector<TOutputValue> P;
                 for ( auto p : V ) {
                     int d2 = p.squaredNorm();
                     // std::cout << "p=" << p << " d2=" << d2 << std::endl;
                     if ( d2_lo <= d2 && d2 < d2_up ) P.push_back( p );
                 }
                 if ( P.empty() ) std::cerr << "Error ! " << std::endl;
                 TOutputValue b = P[ 0 ];
                 for ( int i = 1; i < P.size(); i++ )
                     if ( less<TOutputValue>( P[ i ], b ) ) b = P[ i ];
                 current = b;
             } while ( current != start );
             return circle;
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::circle().
Referenced by DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::init().
init()
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> void DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::init (int R, bool smart) inline
Initialization
Parameters
R the maximal distance of a point to the center of rotation.
smart when 'true', tries to regularize the number of points of each circle, when 'false' each circle contains the point between distance r (included) and r+1 (excluded).
Definition at line 85 of file RBC_vec.h.
{
             TOutputValue c( 0, 0 );
             circles.clear();
             circles.resize( R + 1 );
             circles[ 0 ].push_back( c );
             point2circle[ c ] = TOutputValue( 0, 0 );
             std::size_t N = 1;
             std::vector< TOutputValue > points;
             for ( int r = 1; r <= R; r++ )
             {
                 circles[ r ] = computeCircle( r );
                 for ( int i = 0; i < circles[ r ].size(); i++, N++ )
                 {
                     point2circle[ circles[ r ][ i ] ] = TOutputValue( r, i );
                     points.push_back( circles[ r ][ i ] );
                 }
             }
             if ( ! smart ) return;
             struct DistanceComparator {
                 bool operator()( TOutputValue p, TOutputValue q ) const
                 {
                     return p.squaredNorm() < q.squaredNorm();
                 }
             };
             struct AngleComparator {
                 bool operator()( TOutputValue p, TOutputValue q ) const
                 {
                     double ap = atan2( p[ 1 ], p[ 0 ] );
                     double aq = atan2( q[ 1 ], q[ 0 ] );
                     return ap < aq;
                 }
             };
             // Try to improve circles.
             // target number of points for circle r is
             // n(r) = a * r, with a = 2( N - 1 ) / (R(R+1))
             double a = 2.0 * double( N - 1 ) / double(R*(R+1));
             DistanceComparator dcomp;
             AngleComparator    acomp;
             std::sort( points.begin(), points.end(), dcomp );
             int current = 1;
             for ( int r = 1; r <= R; r++ )
             {
                 int n = int( round( a * r / 8.0 ) * 8.0 );
                 circles[ r ].resize( n );
                 for ( int i = 0; i < n; i++ )
                     circles[ r ][ i ] = points[ current++ ];
                 std::sort( circles[ r ].begin(), circles[ r ].end(), acomp );
                 // std::cout << "r=" << r << " #C=" << circles[ r ].size() << std::endl;
             }
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::circles, DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::computeCircle(), DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::operator()(), and DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::point2circle.
Referenced by DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::RBC_vec().
operator()()
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::operator() (const TInputValue & aInput) const inline
Definition at line 171 of file RBC_vec.h.
         {
             return this->rotate(aInput);
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::rotate().
Referenced by DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::init().
rotate()
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::rotate (TInputValue p) const inline
Parameters
p a lattice point
Returns
the rotation of the point p according to the current angle and center.
Definition at line 157 of file RBC_vec.h.
{
             auto   cp   = static_cast<TOutputValue>((p - my_center));
             const auto it   = point2circle.find( cp );
             if ( it == point2circle.end() ) return static_cast<TOutputValue>(p);
             TOutputValue  polar = it->second;
             int       r     = polar[ 0 ];
             int       idx   = polar[ 1 ];
             const Circle& C = circle( r );
             const int     N = C.size();
             int       shift = int( round( -my_angle * N / ( 2.0 * M_PI ) ) );
             int       jdx   = ( N + idx - shift ) % N;
             return my_center + C[ jdx ];
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::circle(), DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::my_angle, DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::my_center, and DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::point2circle.
Referenced by DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::operator()().
setAngle()
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> double& DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::setAngle () inline
Returns
a reference to the angle of rotation.
Definition at line 142 of file RBC_vec.h.
{
             return my_angle;
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::my_angle.
Referenced by main().
size()
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> std::size_t DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::size () const inline
Returns
the number of circles
Definition at line 177 of file RBC_vec.h.
{
             return circles.size();
         }
References DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::circles.
Field Documentation
circles
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> std::vector< Circle > DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::circles
the array of circles, where index is the integer radius of the circle.
Definition at line 61 of file RBC_vec.h.
Referenced by DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::circle(), DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::init(), and DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::size().
my_angle
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> double DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::my_angle protected
The angle of rotation.
Definition at line 218 of file RBC_vec.h.
Referenced by DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::angle(), DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::RBC_vec(), DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::rotate(), and DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::setAngle().
my_center
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::my_center protected
The center of rotation.
Definition at line 220 of file RBC_vec.h.
Referenced by DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::center(), DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::RBC_vec(), and DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::rotate().
point2circle
template<typename TSpace , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> std::map< TOutputValue, TOutputValue > DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::point2circle
the map associating to a lattice point its polar coordinates (r,idx) in the circles.
Definition at line 64 of file RBC_vec.h.
Referenced by DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::init(), and DGtal::RBC_vec< TSpace, TInputValue, TOutputValue >::rotate().
The documentation for this struct was generated from the following file:
RBC_vec.h