DGtal: DGtal::QSH< TSpace, TInputValue, TOutputValue > Struct Template Reference
DGtal::QSH< TSpace, TInputValue, TOutputValue > Struct Template Reference
QSH : Quasi Shears represents a bijective rotation through shears.
#include <DGtal/images/bijectiveRotations/QSH.h>
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CSpace< TSpace >))
Checking concepts.
BOOST_STATIC_ASSERT ((TSpace::dimension==2))
BOOST_STATIC_ASSERT ((TOutputValue::dimension==2))
BOOST_STATIC_ASSERT ((TInputValue::dimension==2))
TOutputValue hqs (const TOutputValue X, const double a, const double b, const double c) const
TOutputValue vqs (const TOutputValue X, const double a, const double b, const double c) const
TOutputValue hqs_p (const TOutputValue X, const double ap, const double bp, const double omega) const
TOutputValue vqs_p (const TOutputValue X, const double a, const double bp, const double omega) const
template<typename Img >
Img rotateImage (Img img) const
QSH (double ang, TOutputValue ptCenter)
void initQSHRotation ()
init a QSH rotation using Andres' parameters
double angle () const
void set_angle (const double new_angle)
set rotation angle
TOutputValue center () const
TOutputValue & center ()
TOutputValue rotate (const TInputValue &p) const
TOutputValue operator() (const TInputValue &p) const
std::string tostring () const
template<typename TImage >
TImage rotateImage (const TImage img) const
Protected Attributes
double my_angle
The angle of rotation.
TOutputValue my_center
The center of rotation.
Private Attributes
const double omega =1<<15
shears variables
double a
double aprime
double bprime
Detailed Description
template<typename TSpace, typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point>
struct DGtal::QSH< TSpace, TInputValue, TOutputValue >
QSH : Quasi Shears represents a bijective rotation through shears.
Description of template struct CDLR
Template Parameters
TSpace a 2 dimensional space.
TInputValue type of the input point e.g., TSpace::RealPoint.
TOutputValue type of the output point e.g., TSpace::Point
Definition at line 50 of file QSH.h.
Constructor & Destructor Documentation
QSH()
template<typename TSpace , typename TInputValue , typename TOutputValue > DGtal::QSH< TSpace, TInputValue, TOutputValue >::QSH (double ang, TOutputValue ptCenter)
QSH Constructor.
Parameters
ang the angle given in radians.
ptCenter the center of rotation.
Definition at line 132 of file QSH.h.
                                                                                          :my_angle(ang),my_center(ptCenter){
     initQSHRotation();
 }
References DGtal::QSH< TSpace, TInputValue, TOutputValue >::initQSHRotation().
Member Function Documentation
angle()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> double DGtal::QSH< TSpace, TInputValue, TOutputValue >::angle () const inline
Returns
the angle of rotation.
Definition at line 92 of file QSH.h.
 {return my_angle;};
References DGtal::QSH< TSpace, TInputValue, TOutputValue >::my_angle.
BOOST_CONCEPT_ASSERT()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> DGtal::QSH< TSpace, TInputValue, TOutputValue >::BOOST_CONCEPT_ASSERT ((concepts::CSpace< TSpace >))
Checking concepts.
BOOST_STATIC_ASSERT() [1/3]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> DGtal::QSH< TSpace, TInputValue, TOutputValue >::BOOST_STATIC_ASSERT ((TInputValue::dimension==2))
BOOST_STATIC_ASSERT() [2/3]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> DGtal::QSH< TSpace, TInputValue, TOutputValue >::BOOST_STATIC_ASSERT ((TOutputValue::dimension==2))
BOOST_STATIC_ASSERT() [3/3]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> DGtal::QSH< TSpace, TInputValue, TOutputValue >::BOOST_STATIC_ASSERT ((TSpace::dimension==2))
center() [1/2]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> TOutputValue& DGtal::QSH< TSpace, TInputValue, TOutputValue >::center () inline
Returns
a reference to the centre of rotation
Definition at line 101 of file QSH.h.
 {return my_center;};
References DGtal::QSH< TSpace, TInputValue, TOutputValue >::my_center.
center() [2/2]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::QSH< TSpace, TInputValue, TOutputValue >::center () const inline
Returns
the centre of rotation
Definition at line 99 of file QSH.h.
 {return my_center;};
References DGtal::QSH< TSpace, TInputValue, TOutputValue >::my_center.
hqs()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::QSH< TSpace, TInputValue, TOutputValue >::hqs (const TOutputValue X, const double a, const double b, const double c) const inline
Definition at line 60 of file QSH.h.
{
         return TOutputValue{X[0] + static_cast<int>(round((a*X[1]+c)/b)),X[1]};
     }
Referenced by DGtal::QSH< TSpace, TInputValue, TOutputValue >::hqs_p().
hqs_p()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::QSH< TSpace, TInputValue, TOutputValue >::hqs_p (const TOutputValue X, const double ap, const double bp, const double omega) const inline
Definition at line 67 of file QSH.h.
{
         return hqs(X, -ap, bp, 0.0);
     }
References DGtal::QSH< TSpace, TInputValue, TOutputValue >::hqs().
initQSHRotation()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> void DGtal::QSH< TSpace, TInputValue, TOutputValue >::initQSHRotation () inline
init a QSH rotation using Andres' parameters
Definition at line 85 of file QSH.h.
{
             a = round(omega*std::sin(my_angle));
             aprime = round(omega*std::sin(my_angle/2.0));
             bprime = round(omega*std::cos(my_angle/2.0));
     }
References DGtal::QSH< TSpace, TInputValue, TOutputValue >::aprime, DGtal::QSH< TSpace, TInputValue, TOutputValue >::bprime, DGtal::QSH< TSpace, TInputValue, TOutputValue >::my_angle, and DGtal::QSH< TSpace, TInputValue, TOutputValue >::omega.
Referenced by DGtal::QSH< TSpace, TInputValue, TOutputValue >::QSH(), and DGtal::QSH< TSpace, TInputValue, TOutputValue >::set_angle().
operator()()
template<typename TSpace , typename TInputValue , typename TOutputValue > TOutputValue DGtal::QSH< TSpace, TInputValue, TOutputValue >::operator() (const TInputValue & p) const
Definition at line 144 of file QSH.h.
{
     TOutputValue pcentered = p-my_center;
     TOutputValue y1 = hqs_p(pcentered, aprime, bprime, omega);
     TOutputValue y2 = vqs_p(y1, a, bprime, omega);
     TOutputValue y = hqs_p(y2, aprime, bprime, omega);
     return y+my_center;
 }
rotate()
template<typename TSpace , typename TInputValue , typename TOutputValue > TOutputValue DGtal::QSH< TSpace, TInputValue, TOutputValue >::rotate (const TInputValue & p) const
Parameters
p a lattice point
Returns
the rotation of the point p according to the current angle and center.
Definition at line 139 of file QSH.h.
{
     return this->operator()(p);
 }
rotateImage() [1/2]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> template<typename TImage > TImage DGtal::QSH< TSpace, TInputValue, TOutputValue >::rotateImage (const TImage img) const
Definition at line 158 of file QSH.h.
{
     typedef typename TImage::Domain TDomain;
     typedef DGtal::functors::DomainRigidTransformation2D < typename TImage::Domain, DGtal::QSH<TSpace>> MyDomainTransformer;
     typedef std::pair < typename TSpace::Point, typename TSpace::Point > Bounds;
     MyDomainTransformer domainTransformer ( *this );
     Bounds bounds = domainTransformer ( img.domain() );
     TDomain transformedDomain ( bounds.first, bounds.second );
     TImage rotatedImage ( transformedDomain );
     for (typename TDomain::ConstIterator it = img.domain().begin(); it != img.domain().end(); ++it )
     {
         rotatedImage.setValue((*this)(*it),img(*it));
     }
     return rotatedImage;
 }
rotateImage() [2/2]
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> template<typename Img > Img DGtal::QSH< TSpace, TInputValue, TOutputValue >::rotateImage (Img img) const
set_angle()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> void DGtal::QSH< TSpace, TInputValue, TOutputValue >::set_angle (const double new_angle) inline
set rotation angle
Definition at line 95 of file QSH.h.
 {my_angle=new_angle;initQSHRotation();}
References DGtal::QSH< TSpace, TInputValue, TOutputValue >::initQSHRotation(), and DGtal::QSH< TSpace, TInputValue, TOutputValue >::my_angle.
tostring()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> std::string DGtal::QSH< TSpace, TInputValue, TOutputValue >::tostring () const inline
Definition at line 110 of file QSH.h.
{
         return {"QSH"};
     }
vqs()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::QSH< TSpace, TInputValue, TOutputValue >::vqs (const TOutputValue X, const double a, const double b, const double c) const inline
Definition at line 63 of file QSH.h.
{
         return TOutputValue{X[0], X[1] + static_cast<int>((round((a*X[0]+c)/b)))};
     }
Referenced by DGtal::QSH< TSpace, TInputValue, TOutputValue >::vqs_p().
vqs_p()
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::QSH< TSpace, TInputValue, TOutputValue >::vqs_p (const TOutputValue X, const double a, const double bp, const double omega) const inline
Definition at line 70 of file QSH.h.
{
         return vqs(X,a, omega, round(omega/2.0));
     }
References DGtal::QSH< TSpace, TInputValue, TOutputValue >::omega, and DGtal::QSH< TSpace, TInputValue, TOutputValue >::vqs().
Field Documentation
a
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> double DGtal::QSH< TSpace, TInputValue, TOutputValue >::a private
Definition at line 124 of file QSH.h.
aprime
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> double DGtal::QSH< TSpace, TInputValue, TOutputValue >::aprime private
Definition at line 125 of file QSH.h.
Referenced by DGtal::QSH< TSpace, TInputValue, TOutputValue >::initQSHRotation().
bprime
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> double DGtal::QSH< TSpace, TInputValue, TOutputValue >::bprime private
Definition at line 126 of file QSH.h.
Referenced by DGtal::QSH< TSpace, TInputValue, TOutputValue >::initQSHRotation().
my_angle
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> double DGtal::QSH< TSpace, TInputValue, TOutputValue >::my_angle protected
The angle of rotation.
Definition at line 116 of file QSH.h.
Referenced by DGtal::QSH< TSpace, TInputValue, TOutputValue >::angle(), DGtal::QSH< TSpace, TInputValue, TOutputValue >::initQSHRotation(), and DGtal::QSH< TSpace, TInputValue, TOutputValue >::set_angle().
my_center
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> TOutputValue DGtal::QSH< TSpace, TInputValue, TOutputValue >::my_center protected
The center of rotation.
Definition at line 118 of file QSH.h.
Referenced by DGtal::QSH< TSpace, TInputValue, TOutputValue >::center().
omega
template<typename TSpace , typename TInputValue = typename TSpace::Point, typename TOutputValue = typename TSpace::Point> const double DGtal::QSH< TSpace, TInputValue, TOutputValue >::omega =1<<15 private
shears variables
Definition at line 123 of file QSH.h.
Referenced by DGtal::QSH< TSpace, TInputValue, TOutputValue >::initQSHRotation(), and DGtal::QSH< TSpace, TInputValue, TOutputValue >::vqs_p().
The documentation for this struct was generated from the following file:
QSH.h