DGtal: DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue > Struct Template Reference
DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue > Struct Template Reference
#include <DGtal/images/bijectiveRotations/ErrorBijectiveRotation.h>
Public Types
typedef functors::ForwardRigidTransformation2D< TSpace, TInputValue, typename TSpace::RealPoint, functors::Identity > RealRotation
typedef std::vector< std::vector< typename TSpace::RealPoint > > VectorField
typedef functors::ForwardRigidTransformation2D< TSpace, TInputValue, typename TSpace::RealPoint, functors::Identity > RealRotation
typedef std::vector< std::vector< typename TSpace::RealPoint > > VectorField
Public Member Functions
ErrorVectorField (const TBijectiveReflections &reflections, const double theta, const typename TSpace::Point center)
VectorField getOutputVectorFieldFromContour (const TDomain &set2dContour, bool continuityVecField=false)
ErrorVectorField (const TBijectiveReflections &reflections, const double theta, const typename TSpace::Point center)
VectorField getOutputVectorFieldFromContour (const TDomain &set2dContour, bool continuityVecField=false)
Protected Attributes
TBijectiveReflections normalVectors
TSpace::Point my_center
RealRotation targetRotation
RealRotation originCenteredRotation
Detailed Description
template<typename TSpace, typename TDomain, typename TBijectiveReflections, typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point>
struct DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >
Definition at line 44 of file ErrorBijectiveRotation.h.
Member Typedef Documentation
RealRotation [1/2]
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> typedef functors::ForwardRigidTransformation2D<TSpace,TInputValue,typename TSpace::RealPoint,functors::Identity> DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::RealRotation
Definition at line 46 of file ErrorBijectiveRotation.h.
RealRotation [2/2]
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> typedef functors::ForwardRigidTransformation2D<TSpace,TInputValue,typename TSpace::RealPoint,functors::Identity> DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::RealRotation
Definition at line 46 of file ErrorVectorField.h.
VectorField [1/2]
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> typedef std::vector<std::vector<typename TSpace::RealPoint> > DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::VectorField
Definition at line 47 of file ErrorBijectiveRotation.h.
VectorField [2/2]
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> typedef std::vector<std::vector<typename TSpace::RealPoint> > DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::VectorField
Definition at line 47 of file ErrorVectorField.h.
Constructor & Destructor Documentation
ErrorVectorField() [1/2]
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::ErrorVectorField (const TBijectiveReflections & reflections, const double theta, const typename TSpace::Point center) inline
Definition at line 56 of file ErrorBijectiveRotation.h.
                                                                                                                        :normalVectors(reflections),targetRotation(center,theta,{0,0}),my_center(center),originCenteredRotation({0,0},theta,{0,0})
         {}
ErrorVectorField() [2/2]
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::ErrorVectorField (const TBijectiveReflections & reflections, const double theta, const typename TSpace::Point center) inline
Definition at line 56 of file ErrorVectorField.h.
                                                                                                                        :normalVectors(reflections),targetRotation(center,theta,{0,0}),my_center(center),originCenteredRotation({0,0},theta,{0,0})
         {}
Member Function Documentation
getOutputVectorFieldFromContour() [1/2]
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> VectorField DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::getOutputVectorFieldFromContour (const TDomain & set2dContour, bool continuityVecField = false) inline
compute vector of errors for each pixel between either
each digitized reflections and the real reflection
or the the composition of digitized reflections and the final rotation
Definition at line 62 of file ErrorBijectiveRotation.h.
{
             VectorField outVecField;
             for (typename TDomain::ConstIterator it = set2dContour.begin(); it != set2dContour.end(); ++it ) {
                 std::vector<typename TSpace::RealPoint> pixelError;
                 typename TSpace::Point p = *it;
                 typename TSpace::Point preflections = normalVectors(p-my_center)+my_center;
                 typename TSpace::RealPoint protation = targetRotation(p);
                 // compute the error field
                 typename TSpace::RealPoint error = protation - preflections ;
                 pixelError.push_back(error);
                 // compute the eucliean rotation of the neighbors of p
                 if(continuityVecField) {
                     // for the 8-Neighbor, compute the rotation
                     for(int veci = -1 ; veci <2 ; ++veci) {
                         for(int vecj = -1 ; vecj<2 ; ++vecj) {
                             if(veci!=0 || vecj!=0){
                                 typename TSpace::RealPoint vecij_rot = originCenteredRotation({static_cast<double>(veci),static_cast<double>(vecj)});
                                 typename TSpace::RealPoint neigh_rot = protation+vecij_rot;
                                 pixelError.push_back(neigh_rot-preflections);
                             }
                         }
                     }
                 }
                 outVecField.push_back(pixelError);
             }
             return outVecField;
         }
References DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::my_center, DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::normalVectors, DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::originCenteredRotation, and DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::targetRotation.
Referenced by DGtal::LinfPolicy< TSpace, TDomain, TBijectiveRotation >::evaluate(), DGtal::L2< TSpace, TDomain, TBijectiveRotation >::evaluate(), and DGtal::LcontinuityPolicy< TSpace, TDomain, TBijectiveRotation >::evaluate().
getOutputVectorFieldFromContour() [2/2]
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> VectorField DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::getOutputVectorFieldFromContour (const TDomain & set2dContour, bool continuityVecField = false) inline
compute vector of errors for each pixel between either
each digitized reflections and the real reflection
or the the composition of digitized reflections and the final rotation
Definition at line 62 of file ErrorVectorField.h.
{
             VectorField outVecField;
             // std::cout << "DSL output vector error : normalVectors "<<normalVectors.my_startingAngle<<std::endl;
             // std::cout << "DSL output vector error : rotation angle "<<normalVectors.my_angle<<std::endl;
             // std::cout << "input test point = "<<*(set2dContour.begin()+30)<<std::endl;
             // std::cout << "output double reflections = "<<normalVectors(*(set2dContour.begin()+30)-my_center)+my_center<<std::endl;
             // std::cout << "output rotation = "<<targetRotation(*(set2dContour.begin()+30))<<std::endl;
             for (typename TDomain::ConstIterator it = set2dContour.begin(); it != set2dContour.end(); ++it ) {
                 std::vector<typename TSpace::RealPoint> pixelError;
                 typename TSpace::Point p = *it;
                 typename TSpace::Point preflections = normalVectors(p-my_center)+my_center;
                 typename TSpace::RealPoint protation = targetRotation(p);
                 // compute the error field
                 typename TSpace::RealPoint error = protation - preflections ;
                 pixelError.push_back(error);
                 // compute the eucliean rotation of the neighbors of p
                 if(continuityVecField) {
                     // for the 8-Neighbor, compute the rotation
                     for(int veci = -1 ; veci <2 ; ++veci) {
                         for(int vecj = -1 ; vecj<2 ; ++vecj) {
                             if(veci!=0 || vecj!=0){
                                 typename TSpace::RealPoint vecij_rot = originCenteredRotation({static_cast<double>(veci),static_cast<double>(vecj)});
                                 typename TSpace::RealPoint neigh_rot = protation+vecij_rot;
                                 pixelError.push_back(neigh_rot-preflections);
                             }
                         }
                     }
                 }
                 outVecField.push_back(pixelError);
             }
             return outVecField;
         }
References DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::my_center, DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::normalVectors, DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::originCenteredRotation, and DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::targetRotation.
Field Documentation
my_center
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> TSpace::Point DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::my_center protected
Definition at line 51 of file ErrorBijectiveRotation.h.
Referenced by DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::getOutputVectorFieldFromContour().
normalVectors
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> TBijectiveReflections DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::normalVectors protected
Definition at line 50 of file ErrorBijectiveRotation.h.
Referenced by DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::getOutputVectorFieldFromContour().
originCenteredRotation
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> RealRotation DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::originCenteredRotation protected
Definition at line 53 of file ErrorBijectiveRotation.h.
Referenced by DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::getOutputVectorFieldFromContour().
targetRotation
template<typename TSpace , typename TDomain , typename TBijectiveReflections , typename TInputValue = typename TSpace::RealPoint, typename TOutputValue = typename TSpace::Point> RealRotation DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::targetRotation protected
Definition at line 52 of file ErrorBijectiveRotation.h.
Referenced by DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::getOutputVectorFieldFromContour().
The documentation for this struct was generated from the following files:
ErrorBijectiveRotation.h
ErrorVectorField.h