DGtal: DGtal::LinfPolicy< TSpace, TDomain, TBijectiveRotation > Struct Template Reference
DGtal::LinfPolicy< TSpace, TDomain, TBijectiveRotation > Struct Template Reference
#include <DGtal/images/bijectiveRotations/Policy.h>
Public Types
typedef std::vector< std::vector< typename TSpace::RealPoint > > VectorField
typedef ErrorVectorField< TSpace, TDomain, TBijectiveRotation, typename TSpace::RealPoint > ErrorRealVectors
Public Types inherited from DGtal::Policy< TSpace, TDomain, TBijectiveRotation >
typedef std::vector< std::vector< typename TSpace::RealPoint > > VectorField
Public Member Functions
double evaluate (const TDomain &set2d, const TBijectiveRotation &reflections, double my_angle, typename TSpace::Point my_center) const override
Public Member Functions inherited from DGtal::Policy< TSpace, TDomain, TBijectiveRotation >
virtual ~Policy ()=default
Detailed Description
template<typename TSpace, typename TDomain, typename TBijectiveRotation>
struct DGtal::LinfPolicy< TSpace, TDomain, TBijectiveRotation >
Definition at line 65 of file Policy.h.
Member Typedef Documentation
ErrorRealVectors
template<typename TSpace , typename TDomain , typename TBijectiveRotation > typedef ErrorVectorField<TSpace,TDomain,TBijectiveRotation,typename TSpace::RealPoint> DGtal::LinfPolicy< TSpace, TDomain, TBijectiveRotation >::ErrorRealVectors
Definition at line 67 of file Policy.h.
VectorField
template<typename TSpace , typename TDomain , typename TBijectiveRotation > typedef std::vector<std::vector<typename TSpace::RealPoint> > DGtal::LinfPolicy< TSpace, TDomain, TBijectiveRotation >::VectorField
Definition at line 66 of file Policy.h.
Member Function Documentation
evaluate()
template<typename TSpace , typename TDomain , typename TBijectiveRotation > double DGtal::LinfPolicy< TSpace, TDomain, TBijectiveRotation >::evaluate (const TDomain & set2d, const TBijectiveRotation & reflections, double my_angle, typename TSpace::Point my_center) const inline override virtual
Implements DGtal::Policy< TSpace, TDomain, TBijectiveRotation >.
Definition at line 69 of file Policy.h.
{
             ErrorRealVectors errorsVectors(reflections,my_angle,my_center);
             VectorField errors = errorsVectors.getOutputVectorFieldFromContour(set2d);
             double outError = 0.;
             for(std::vector<typename TSpace::RealPoint> vecError: errors) {
                 typename TSpace::RealPoint vecErrorRealRot = vecError[0];
                 outError= std::max(outError,std::sqrt((vecErrorRealRot[0]*vecErrorRealRot[0]+vecErrorRealRot[1]*vecErrorRealRot[1])));
             }
             return outError;
         }
References DGtal::ErrorVectorField< TSpace, TDomain, TBijectiveReflections, TInputValue, TOutputValue >::getOutputVectorFieldFromContour(), and max().
Referenced by DGtal::MixedPolicy< TSpace, TDomain, TBijectiveRotation >::evaluate().
The documentation for this struct was generated from the following file:
Policy.h