DGtal: DGtal::GAVector< TSpace, TInputValue > Struct Template Reference
DGtal::GAVector< TSpace, TInputValue > Struct Template Reference
#include <DGtal/images/bijectiveRotations/GAVector.h>
Public Member Functions
GAVector (const TInputValue &pt=TInputValue(0, 0))
zero multivector
TInputValue::Component dot (GAVector other) const
scalar part of the a mv, i.e. compute the dot product part of the geometric product
TInputValue::Component bivectorPart (const GAVector &other) const
bivector part of the a mv, i.e. compute the outer product part of the geometric product
GAVector operator* (typename TInputValue::Component f) const
geometric product with a scalar
GAVector operator* (const GAVector &v)
geometric product between two vectors
bool operator< (const GAVector &other) const
double angleToXAxis () const
bool operator== (const GAVector &other) const
Data Fields
TInputValue my_gavec
Detailed Description
template<typename TSpace, typename TInputValue = typename TSpace::Point>
struct DGtal::GAVector< TSpace, TInputValue >
Definition at line 47 of file GAVector.h.
Constructor & Destructor Documentation
GAVector()
template<typename TSpace , typename TInputValue = typename TSpace::Point> DGtal::GAVector< TSpace, TInputValue >::GAVector (const TInputValue & pt = TInputValue(0,0)) inline explicit
zero multivector
Definition at line 51 of file GAVector.h.
           : my_gavec( pt ) {}
Referenced by DGtal::GAVector< TSpace, TInputValue >::operator*().
Member Function Documentation
angleToXAxis()
template<typename TSpace , typename TInputValue = typename TSpace::Point> double DGtal::GAVector< TSpace, TInputValue >::angleToXAxis () const inline
Definition at line 82 of file GAVector.h.
         {
             return atan2( my_gavec[1], my_gavec[0] );
         }
References DGtal::GAVector< TSpace, TInputValue >::my_gavec.
Referenced by DGtal::NBijectiveGenerator< TSpace, TInputValue >::displayNormalVectorsAndAngles().
bivectorPart()
template<typename TSpace , typename TInputValue = typename TSpace::Point> TInputValue::Component DGtal::GAVector< TSpace, TInputValue >::bivectorPart (const GAVector< TSpace, TInputValue > & other) const inline
bivector part of the a mv, i.e. compute the outer product part of the geometric product
Definition at line 61 of file GAVector.h.
         {
             return my_gavec[0] * other.my_gavec[1] - my_gavec[1] * other.my_gavec[0];
         }
References DGtal::GAVector< TSpace, TInputValue >::my_gavec.
Referenced by DGtal::GAVector< TSpace, TInputValue >::operator*(), DGtal::GAVector< TSpace, TInputValue >::operator<(), and DGtal::GAVector< TSpace, TInputValue >::operator==().
dot()
template<typename TSpace , typename TInputValue = typename TSpace::Point> TInputValue::Component DGtal::GAVector< TSpace, TInputValue >::dot (GAVector< TSpace, TInputValue > other) const inline
scalar part of the a mv, i.e. compute the dot product part of the geometric product
Definition at line 55 of file GAVector.h.
         {
             return my_gavec[0] * other.my_gavec[0] + my_gavec[1] * other.my_gavec[1];
         }
References DGtal::GAVector< TSpace, TInputValue >::my_gavec.
Referenced by DGtal::GAVector< TSpace, TInputValue >::operator*().
operator*() [1/2]
template<typename TSpace , typename TInputValue = typename TSpace::Point> GAVector DGtal::GAVector< TSpace, TInputValue >::operator* (const GAVector< TSpace, TInputValue > & v) inline
geometric product between two vectors
Definition at line 73 of file GAVector.h.
         {
             return GAVector( TInputValue(this->dot(v), this->bivectorPart(v)) );
         }
References DGtal::GAVector< TSpace, TInputValue >::bivectorPart(), DGtal::GAVector< TSpace, TInputValue >::dot(), and DGtal::GAVector< TSpace, TInputValue >::GAVector().
operator*() [2/2]
template<typename TSpace , typename TInputValue = typename TSpace::Point> GAVector DGtal::GAVector< TSpace, TInputValue >::operator* (typename TInputValue::Component f) const inline
geometric product with a scalar
Definition at line 67 of file GAVector.h.
         {
             return GAVector( TInputValue(my_gavec[0] * f, my_gavec[1] * f) );
         }
References DGtal::GAVector< TSpace, TInputValue >::GAVector(), and DGtal::GAVector< TSpace, TInputValue >::my_gavec.
operator<()
template<typename TSpace , typename TInputValue = typename TSpace::Point> bool DGtal::GAVector< TSpace, TInputValue >::operator< (const GAVector< TSpace, TInputValue > & other) const inline
Definition at line 77 of file GAVector.h.
         {
             return bivectorPart( other ) > 0;
         }
References DGtal::GAVector< TSpace, TInputValue >::bivectorPart().
operator==()
template<typename TSpace , typename TInputValue = typename TSpace::Point> bool DGtal::GAVector< TSpace, TInputValue >::operator== (const GAVector< TSpace, TInputValue > & other) const inline
Definition at line 87 of file GAVector.h.
         {
             return bivectorPart( other ) == 0;
         }
References DGtal::GAVector< TSpace, TInputValue >::bivectorPart().
Field Documentation
my_gavec
template<typename TSpace , typename TInputValue = typename TSpace::Point> TInputValue DGtal::GAVector< TSpace, TInputValue >::my_gavec
Definition at line 48 of file GAVector.h.
Referenced by DGtal::GAVector< TSpace, TInputValue >::angleToXAxis(), DGtal::GAVector< TSpace, TInputValue >::bivectorPart(), DGtal::NBijectiveGenerator< TSpace, TInputValue >::composeBijectiveReflections(), DGtal::GAVector< TSpace, TInputValue >::dot(), and DGtal::GAVector< TSpace, TInputValue >::operator*().
The documentation for this struct was generated from the following file:
GAVector.h