var searchData=
[
  ['sametype_0',['SameType',['../structDGtal_1_1concepts_1_1ConceptUtils_1_1SameType.html',1,'DGtal::concepts::ConceptUtils']]],
  ['sametype_3c_20t_2c_20t_20_3e_1',['SameType&lt; T, T &gt;',['../structDGtal_1_1concepts_1_1ConceptUtils_1_1SameType_3_01T_00_01T_01_4.html',1,'DGtal::concepts::ConceptUtils']]],
  ['saturatedsegmentation_2',['SaturatedSegmentation',['../classDGtal_1_1SaturatedSegmentation.html',1,'DGtal']]],
  ['scellmap_3',['scellmap',['../structDGtal_1_1KhalimskyPreSpaceND_1_1SCellMap.html',1,'DGtal::KhalimskyPreSpaceND&lt; dim, TInteger &gt;::SCellMap&lt; Value &gt;'],['../structDGtal_1_1KhalimskySpaceND_1_1SCellMap.html',1,'DGtal::KhalimskySpaceND&lt; dim, TInteger &gt;::SCellMap&lt; Value &gt;']]],
  ['scellreader_4',['SCellReader',['../structDGtal_1_1Shortcuts_1_1SCellReader.html',1,'DGtal::Shortcuts']]],
  ['scelltoarrow_5',['SCellToArrow',['../classDGtal_1_1functors_1_1SCellToArrow.html',1,'DGtal::functors']]],
  ['scelltocode_6',['SCellToCode',['../classDGtal_1_1functors_1_1SCellToCode.html',1,'DGtal::functors']]],
  ['scelltoincidentpoints_7',['SCellToIncidentPoints',['../classDGtal_1_1functors_1_1SCellToIncidentPoints.html',1,'DGtal::functors']]],
  ['scelltoinnerpoint_8',['SCellToInnerPoint',['../classDGtal_1_1functors_1_1SCellToInnerPoint.html',1,'DGtal::functors']]],
  ['scelltoouterpoint_9',['SCellToOuterPoint',['../classDGtal_1_1functors_1_1SCellToOuterPoint.html',1,'DGtal::functors']]],
  ['scelltopoint_10',['SCellToPoint',['../classDGtal_1_1functors_1_1SCellToPoint.html',1,'DGtal::functors']]],
  ['scellwriter_11',['SCellWriter',['../structDGtal_1_1Shortcuts_1_1SCellWriter.html',1,'DGtal::Shortcuts']]],
  ['segmentcomputeriterator_12',['segmentcomputeriterator',['../classDGtal_1_1GreedySegmentation_1_1SegmentComputerIterator.html',1,'DGtal::GreedySegmentation&lt; TSegmentComputer &gt;::SegmentComputerIterator'],['../classDGtal_1_1SaturatedSegmentation_1_1SegmentComputerIterator.html',1,'DGtal::SaturatedSegmentation&lt; TSegmentComputer &gt;::SegmentComputerIterator']]],
  ['segmentcomputertraits_13',['SegmentComputerTraits',['../structDGtal_1_1SegmentComputerTraits.html',1,'DGtal']]],
  ['segmentedplane_14',['SegmentedPlane',['../structSegmentedPlane.html',1,'']]],
  ['separablemetricadapter_15',['SeparableMetricAdapter',['../classDGtal_1_1SeparableMetricAdapter.html',1,'DGtal']]],
  ['sequence_16',['Sequence',['../structboost_1_1Sequence.html',1,'boost']]],
  ['sequencecategory_17',['SequenceCategory',['../structDGtal_1_1SequenceCategory.html',1,'DGtal']]],
  ['setassociativecategory_18',['SetAssociativeCategory',['../structDGtal_1_1SetAssociativeCategory.html',1,'DGtal']]],
  ['setfromimage_19',['SetFromImage',['../structDGtal_1_1SetFromImage.html',1,'DGtal']]],
  ['setfunctionsimpl_20',['SetFunctionsImpl',['../structDGtal_1_1detail_1_1SetFunctionsImpl.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20false_2c_20true_20_3e_21',['SetFunctionsImpl&lt; Container, false, true &gt;',['../structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01false_00_01true_01_4.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20true_2c_20false_20_3e_22',['SetFunctionsImpl&lt; Container, true, false &gt;',['../structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01true_00_01false_01_4.html',1,'DGtal::detail']]],
  ['setfunctionsimpl_3c_20container_2c_20true_2c_20true_20_3e_23',['SetFunctionsImpl&lt; Container, true, true &gt;',['../structDGtal_1_1detail_1_1SetFunctionsImpl_3_01Container_00_01true_00_01true_01_4.html',1,'DGtal::detail']]],
  ['setmode_24',['SetMode',['../structDGtal_1_1SetMode.html',1,'DGtal']]],
  ['setofsurfels_25',['SetOfSurfels',['../classDGtal_1_1SetOfSurfels.html',1,'DGtal']]],
  ['setvalueiterator_26',['SetValueIterator',['../classDGtal_1_1SetValueIterator.html',1,'DGtal']]],
  ['sgiassignable_27',['SGIAssignable',['../structboost_1_1SGIAssignable.html',1,'boost']]],
  ['shape_28',['Shape',['../structLibBoard_1_1Shape.html',1,'LibBoard']]],
  ['shapefirstprincipalcurvaturefunctor_29',['ShapeFirstPrincipalCurvatureFunctor',['../structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeFirstPrincipalCurvatureFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapefirstprincipaldirectionfunctor_30',['ShapeFirstPrincipalDirectionFunctor',['../structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeFirstPrincipalDirectionFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapegaussiancurvaturefunctor_31',['ShapeGaussianCurvatureFunctor',['../structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeGaussianCurvatureFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapelist_32',['ShapeList',['../structLibBoard_1_1ShapeList.html',1,'LibBoard']]],
  ['shapemeancurvaturefunctor_33',['ShapeMeanCurvatureFunctor',['../structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeMeanCurvatureFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapenormalvectorfunctor_34',['ShapeNormalVectorFunctor',['../structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeNormalVectorFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapepositionfunctor_35',['ShapePositionFunctor',['../structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapePositionFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapeprincipalcurvaturesanddirectionsfunctor_36',['ShapePrincipalCurvaturesAndDirectionsFunctor',['../structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapePrincipalCurvaturesAndDirectionsFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapes_37',['Shapes',['../classDGtal_1_1Shapes.html',1,'DGtal']]],
  ['shapesecondprincipalcurvaturefunctor_38',['ShapeSecondPrincipalCurvatureFunctor',['../structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeSecondPrincipalCurvatureFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shapesecondprincipaldirectionfunctor_39',['ShapeSecondPrincipalDirectionFunctor',['../structDGtal_1_1functors_1_1ShapeGeometricFunctors_1_1ShapeSecondPrincipalDirectionFunctor.html',1,'DGtal::functors::ShapeGeometricFunctors']]],
  ['shortcuts_40',['Shortcuts',['../classDGtal_1_1Shortcuts.html',1,'DGtal']]],
  ['shortcutsgeometry_41',['ShortcutsGeometry',['../classDGtal_1_1ShortcutsGeometry.html',1,'DGtal']]],
  ['shortestpaths_42',['ShortestPaths',['../structDGtal_1_1TangencyComputer_1_1ShortestPaths.html',1,'DGtal::TangencyComputer']]],
  ['shroudsregularization_43',['ShroudsRegularization',['../classDGtal_1_1ShroudsRegularization.html',1,'DGtal']]],
  ['signal_44',['Signal',['../classDGtal_1_1Signal.html',1,'DGtal']]],
  ['signal_3c_20value_20_3e_45',['Signal&lt; Value &gt;',['../classDGtal_1_1Signal.html',1,'DGtal']]],
  ['signaldata_46',['SignalData',['../structDGtal_1_1SignalData.html',1,'DGtal']]],
  ['signeddisttocircle_47',['SignedDistToCircle',['../structSignedDistToCircle.html',1,'']]],
  ['signedinteger_48',['SignedInteger',['../structboost_1_1SignedInteger.html',1,'boost']]],
  ['signedkhalimskycell_49',['SignedKhalimskyCell',['../structDGtal_1_1SignedKhalimskyCell.html',1,'DGtal']]],
  ['signedkhalimskyprecell_50',['SignedKhalimskyPreCell',['../structDGtal_1_1SignedKhalimskyPreCell.html',1,'DGtal']]],
  ['signedkhalimskyprecell_3c_20dim_2c_20integer_20_3e_51',['SignedKhalimskyPreCell&lt; dim, Integer &gt;',['../structDGtal_1_1SignedKhalimskyPreCell.html',1,'DGtal']]],
  ['simple2x2detcomputer_52',['Simple2x2DetComputer',['../classDGtal_1_1Simple2x2DetComputer.html',1,'DGtal']]],
  ['simple2x2detcomputer_3c_20integer_20_3e_53',['Simple2x2DetComputer&lt; Integer &gt;',['../classDGtal_1_1Simple2x2DetComputer.html',1,'DGtal']]],
  ['simple2x2detcomputer_3c_20typename_20tpoint_3a_3acoordinate_2c_20dgtal_3a_3aint64_5ft_20_3e_54',['Simple2x2DetComputer&lt; typename TPoint::Coordinate, DGtal::int64_t &gt;',['../classDGtal_1_1Simple2x2DetComputer.html',1,'DGtal']]],
  ['simpleassociativecategory_55',['SimpleAssociativeCategory',['../structDGtal_1_1SimpleAssociativeCategory.html',1,'DGtal']]],
  ['simpleassociativecontainer_56',['SimpleAssociativeContainer',['../structboost_1_1SimpleAssociativeContainer.html',1,'boost']]],
  ['simpleconstrange_57',['SimpleConstRange',['../classDGtal_1_1SimpleConstRange.html',1,'DGtal']]],
  ['simpledistancecolormap_58',['SimpleDistanceColorMap',['../classDGtal_1_1SimpleDistanceColorMap.html',1,'DGtal']]],
  ['simpleincremental2x2detcomputer_59',['SimpleIncremental2x2DetComputer',['../classDGtal_1_1SimpleIncremental2x2DetComputer.html',1,'DGtal']]],
  ['simplelinearregression_60',['SimpleLinearRegression',['../classDGtal_1_1SimpleLinearRegression.html',1,'DGtal']]],
  ['simplematrix_61',['SimpleMatrix',['../classDGtal_1_1SimpleMatrix.html',1,'DGtal']]],
  ['simplematrix_3c_20double_2c_203_2c_203_20_3e_62',['SimpleMatrix&lt; double, 3, 3 &gt;',['../classDGtal_1_1SimpleMatrix.html',1,'DGtal']]],
  ['simplematrix_3c_20integer_2c_203_2c_203_20_3e_63',['SimpleMatrix&lt; Integer, 3, 3 &gt;',['../classDGtal_1_1SimpleMatrix.html',1,'DGtal']]],
  ['simplematrix_3c_20typename_20tspace_3a_3arealvector_3a_3acomponent_2c_20tspace_3a_3adimension_2c_20tspace_3a_3adimension_20_3e_64',['SimpleMatrix&lt; typename TSpace::RealVector::Component, TSpace::dimension, TSpace::dimension &gt;',['../classDGtal_1_1SimpleMatrix.html',1,'DGtal']]],
  ['simplematrixspecializations_65',['SimpleMatrixSpecializations',['../structDGtal_1_1SimpleMatrixSpecializations.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_201_2c_201_20_3e_66',['SimpleMatrixSpecializations&lt; TMatrix, 1, 1 &gt;',['../structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_011_00_011_01_4.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_202_2c_202_20_3e_67',['SimpleMatrixSpecializations&lt; TMatrix, 2, 2 &gt;',['../structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_012_00_012_01_4.html',1,'DGtal']]],
  ['simplematrixspecializations_3c_20tmatrix_2c_203_2c_203_20_3e_68',['SimpleMatrixSpecializations&lt; TMatrix, 3, 3 &gt;',['../structDGtal_1_1SimpleMatrixSpecializations_3_01TMatrix_00_013_00_013_01_4.html',1,'DGtal']]],
  ['simplerandomaccessconstrangefrompoint_69',['SimpleRandomAccessConstRangeFromPoint',['../classDGtal_1_1SimpleRandomAccessConstRangeFromPoint.html',1,'DGtal']]],
  ['simplerandomaccessrangefrompoint_70',['SimpleRandomAccessRangeFromPoint',['../classDGtal_1_1SimpleRandomAccessRangeFromPoint.html',1,'DGtal']]],
  ['simplethresholdforegroundpredicate_71',['SimpleThresholdForegroundPredicate',['../classDGtal_1_1functors_1_1SimpleThresholdForegroundPredicate.html',1,'DGtal::functors']]],
  ['singlepassiteratorconcept_72',['SinglePassIteratorConcept',['../structboost__concepts_1_1SinglePassIteratorConcept.html',1,'boost_concepts']]],
  ['slice_73',['Slice',['../structSlice.html',1,'']]],
  ['slicerotator2d_74',['SliceRotator2D',['../classDGtal_1_1functors_1_1SliceRotator2D.html',1,'DGtal::functors']]],
  ['sortedassociativecontainer_75',['SortedAssociativeContainer',['../structboost_1_1SortedAssociativeContainer.html',1,'boost']]],
  ['spacend_76',['SpaceND',['../classDGtal_1_1SpaceND.html',1,'DGtal']]],
  ['spacend_3c_202_2c_20integer_20_3e_77',['SpaceND&lt; 2, Integer &gt;',['../classDGtal_1_1SpaceND.html',1,'DGtal']]],
  ['spaniterator_78',['SpanIterator',['../classDGtal_1_1ImageContainerBySTLVector_1_1SpanIterator.html',1,'DGtal::ImageContainerBySTLVector']]],
  ['spatialcubicalsubdivision_79',['SpatialCubicalSubdivision',['../classDGtal_1_1SpatialCubicalSubdivision.html',1,'DGtal']]],
  ['speedextrapolator_80',['SpeedExtrapolator',['../classDGtal_1_1SpeedExtrapolator.html',1,'DGtal']]],
  ['spherefittingestimator_81',['SphereFittingEstimator',['../classDGtal_1_1functors_1_1SphereFittingEstimator.html',1,'DGtal::functors']]],
  ['sphericalaccumulator_82',['SphericalAccumulator',['../classDGtal_1_1SphericalAccumulator.html',1,'DGtal']]],
  ['sphericalaccumulator_3c_20realpoint_20_3e_83',['SphericalAccumulator&lt; RealPoint &gt;',['../classDGtal_1_1SphericalAccumulator.html',1,'DGtal']]],
  ['sphericalhoughnormalvectorestimator_84',['SphericalHoughNormalVectorEstimator',['../classDGtal_1_1functors_1_1SphericalHoughNormalVectorEstimator.html',1,'DGtal::functors']]],
  ['sphericaltriangle_85',['SphericalTriangle',['../classDGtal_1_1SphericalTriangle.html',1,'DGtal']]],
  ['splitter_86',['Splitter',['../structDGtal_1_1Splitter.html',1,'DGtal']]],
  ['splitter_3c_20dgtal_3a_3apointvector_2c_20uint64_5ft_20_3e_87',['Splitter&lt; DGtal::PointVector, uint64_t &gt;',['../structDGtal_1_1Splitter.html',1,'DGtal']]],
  ['splitter_3c_20key_20_3e_88',['Splitter&lt; Key &gt;',['../structDGtal_1_1Splitter.html',1,'DGtal']]],
  ['splitter_3c_20point_20_3e_89',['Splitter&lt; Point &gt;',['../structDGtal_1_1Splitter.html',1,'DGtal']]],
  ['stabbingcirclecomputer_90',['StabbingCircleComputer',['../classDGtal_1_1StabbingCircleComputer.html',1,'DGtal']]],
  ['stabbinglinecomputer_91',['StabbingLineComputer',['../classDGtal_1_1StabbingLineComputer.html',1,'DGtal']]],
  ['standarddsl_92',['StandardDSL',['../classDGtal_1_1StandardDSL.html',1,'DGtal']]],
  ['standarddslq0_93',['StandardDSLQ0',['../classDGtal_1_1StandardDSLQ0.html',1,'DGtal']]],
  ['standarddss4_94',['StandardDSS4',['../classDGtal_1_1StandardDSS4.html',1,'DGtal']]],
  ['standarddss6computer_95',['StandardDSS6Computer',['../classDGtal_1_1StandardDSS6Computer.html',1,'DGtal']]],
  ['starshaped2d_96',['StarShaped2D',['../classDGtal_1_1StarShaped2D.html',1,'DGtal']]],
  ['starshaped2d_3c_20space_20_3e_97',['StarShaped2D&lt; Space &gt;',['../classDGtal_1_1StarShaped2D.html',1,'DGtal']]],
  ['starshaped3d_98',['StarShaped3D',['../classDGtal_1_1StarShaped3D.html',1,'DGtal']]],
  ['state_99',['state',['../structDGtal_1_1AlphaThickSegmentComputer_1_1State.html',1,'DGtal::AlphaThickSegmentComputer&lt; TInputPoint, TConstIterator &gt;::State'],['../structDGtal_1_1ChordNaivePlaneComputer_1_1State.html',1,'DGtal::ChordNaivePlaneComputer&lt; TSpace, TInputPoint, TInternalScalar &gt;::State'],['../structDGtal_1_1COBANaivePlaneComputer_1_1State.html',1,'DGtal::COBANaivePlaneComputer&lt; TSpace, TInternalInteger &gt;::State'],['../structDGtal_1_1UmbrellaComputer_1_1State.html',1,'DGtal::UmbrellaComputer&lt; TDigitalSurfaceTracker &gt;::State'],['../structLibBoard_1_1Board_1_1State.html',1,'LibBoard::Board::State']]],
  ['statistic_100',['Statistic',['../classDGtal_1_1Statistic.html',1,'DGtal']]],
  ['statistic_3c_20value_20_3e_101',['Statistic&lt; Value &gt;',['../classDGtal_1_1Statistic.html',1,'DGtal']]],
  ['stbreader_102',['STBReader',['../classDGtal_1_1STBReader.html',1,'DGtal']]],
  ['stbwriter_103',['STBWriter',['../classDGtal_1_1STBWriter.html',1,'DGtal']]],
  ['stdmaprebinder_104',['StdMapRebinder',['../structDGtal_1_1StdMapRebinder.html',1,'DGtal']]],
  ['sternbrocot_105',['SternBrocot',['../classDGtal_1_1SternBrocot.html',1,'DGtal']]],
  ['stlmaptovertexmapadapter_106',['STLMapToVertexMapAdapter',['../classDGtal_1_1STLMapToVertexMapAdapter.html',1,'DGtal']]],
  ['straightlinefrom2points_107',['StraightLineFrom2Points',['../classDGtal_1_1StraightLineFrom2Points.html',1,'DGtal']]],
  ['stricttruncationfunctor_108',['StrictTruncationFunctor',['../structDGtal_1_1functors_1_1StrictTruncationFunctor.html',1,'DGtal::functors']]],
  ['strictunitcell_109',['StrictUnitCell',['../structDGtal_1_1BoundedLatticePolytope_1_1StrictUnitCell.html',1,'DGtal::BoundedLatticePolytope']]],
  ['strictunitsegment_110',['StrictUnitSegment',['../structDGtal_1_1BoundedLatticePolytope_1_1StrictUnitSegment.html',1,'DGtal::BoundedLatticePolytope']]],
  ['style2dfactory_111',['Style2DFactory',['../structDGtal_1_1Style2DFactory.html',1,'DGtal']]],
  ['subcospace_112',['Subcospace',['../structDGtal_1_1SpaceND_1_1Subcospace.html',1,'DGtal::SpaceND']]],
  ['subspace_113',['Subspace',['../structDGtal_1_1SpaceND_1_1Subspace.html',1,'DGtal::SpaceND']]],
  ['surfacemesh_114',['SurfaceMesh',['../structDGtal_1_1SurfaceMesh.html',1,'DGtal']]],
  ['surfacemeshhelper_115',['SurfaceMeshHelper',['../structDGtal_1_1SurfaceMeshHelper.html',1,'DGtal']]],
  ['surfacemeshmeasure_116',['SurfaceMeshMeasure',['../structDGtal_1_1SurfaceMeshMeasure.html',1,'DGtal']]],
  ['surfacemeshreader_117',['SurfaceMeshReader',['../structDGtal_1_1SurfaceMeshReader.html',1,'DGtal']]],
  ['surfacemeshwriter_118',['SurfaceMeshWriter',['../structDGtal_1_1SurfaceMeshWriter.html',1,'DGtal']]],
  ['surfaces_119',['Surfaces',['../classDGtal_1_1Surfaces.html',1,'DGtal']]],
  ['surfel_5fposition_120',['surfel_position',['../structsurfel__position.html',1,'']]],
  ['surfel_5fposition_5ft_121',['surfel_position_t',['../structsurfel__position__t.html',1,'']]],
  ['surfeladjacency_122',['SurfelAdjacency',['../classDGtal_1_1SurfelAdjacency.html',1,'DGtal']]],
  ['surfeladjacency_3c_20kspace_3a_3adimension_20_3e_123',['SurfelAdjacency&lt; KSpace::dimension &gt;',['../classDGtal_1_1SurfelAdjacency.html',1,'DGtal']]],
  ['surfelmap_124',['surfelmap',['../structDGtal_1_1DigitalSurface_1_1SurfelMap.html',1,'DGtal::DigitalSurface&lt; TDigitalSurfaceContainer &gt;::SurfelMap&lt; Value &gt;'],['../structDGtal_1_1KhalimskyPreSpaceND_1_1SurfelMap.html',1,'DGtal::KhalimskyPreSpaceND&lt; dim, TInteger &gt;::SurfelMap&lt; Value &gt;'],['../structDGtal_1_1KhalimskySpaceND_1_1SurfelMap.html',1,'DGtal::KhalimskySpaceND&lt; dim, TInteger &gt;::SurfelMap&lt; Value &gt;']]],
  ['surfelneighborhood_125',['SurfelNeighborhood',['../classDGtal_1_1SurfelNeighborhood.html',1,'DGtal']]],
  ['surfelneighborhood_3c_20kspace_20_3e_126',['SurfelNeighborhood&lt; KSpace &gt;',['../classDGtal_1_1SurfelNeighborhood.html',1,'DGtal']]],
  ['surfelsetpredicate_127',['SurfelSetPredicate',['../structDGtal_1_1functors_1_1SurfelSetPredicate.html',1,'DGtal::functors']]],
  ['surfelsetpredicate_3c_20surfelset_2c_20surfel_20_3e_128',['SurfelSetPredicate&lt; SurfelSet, Surfel &gt;',['../structDGtal_1_1functors_1_1SurfelSetPredicate.html',1,'DGtal::functors']]],
  ['svoreader_129',['SVOReader',['../classDGtal_1_1SVOReader.html',1,'DGtal']]],
  ['svowriter_130',['SVOWriter',['../classDGtal_1_1SVOWriter.html',1,'DGtal']]],
  ['swappableiteratorconcept_131',['SwappableIteratorConcept',['../structboost__concepts_1_1SwappableIteratorConcept.html',1,'boost_concepts']]],
  ['symmetricconvexexpander_132',['SymmetricConvexExpander',['../classDGtal_1_1SymmetricConvexExpander.html',1,'DGtal']]]
];
