DGtal: DGtal::detail::GridPoint< Integer > Class Template Reference
DGtal::detail::GridPoint< Integer > Class Template Reference
A grid point consists of a couple of nonnegative coordinates \((x,y) \) and an integer index \(k \) that determines a point used as origin. For a triplet of vectors \((m_k)_{0 \leq k \leq 2} \) and a point \(q \), a grid point is defined as: \(q - m_{k} + x m_{(k+1)\bmod 3} + y m_{(k+2)\bmod 3} \). \(q - m_{k} \), called base point, is used as origin.
#include <DGtal/geometry/helpers/PlaneProbingEstimatorHelper.h>
Public Member Functions
GridPoint ()=default
GridPoint (std::pair< Integer, Integer > const &aDir, int aK)
GridPoint (Integer aX, Integer aY, int aK)
std::pair< Integer, Integer > direction () const
int k () const
template<typename Vector >
Vector directionVector (std::array< Vector, 3 > const &aM) const
template<typename Point >
Point relativePoint (std::array< Point, 3 > const &aM) const
bool operator== (GridPoint const &other) const
bool operator!= (GridPoint const &other) const
GridPoint getOnSameGrid (const std::pair< Integer, Integer > &aDir) const
GridPoint operator+ (const GridPoint &other) const
GridPoint operator* (Integer aValue) const
bool isValid () const
Private Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CInteger< Integer >))
Private Attributes
std::pair< Integer, Integer > myDir
int myK
Detailed Description
template<typename Integer = int>
class DGtal::detail::GridPoint< Integer >
A grid point consists of a couple of nonnegative coordinates \((x,y) \) and an integer index \(k \) that determines a point used as origin. For a triplet of vectors \((m_k)_{0 \leq k \leq 2} \) and a point \(q \), a grid point is defined as: \(q - m_{k} + x m_{(k+1)\bmod 3} + y m_{(k+2)\bmod 3} \). \(q - m_{k} \), called base point, is used as origin.
Description of template class 'GridPoint'
This class is used to represent candidate points for the plane-probing L-algorithm. In practice, the point \(q \) is the fixed point and the three vectors \((m_k)_{0 \leq k \leq 2} \) are the vectors defining the current probing frame.
Template Parameters
Integer the integer type, model of concepts::CInteger.
Definition at line 240 of file PlaneProbingEstimatorHelper.h.
Constructor & Destructor Documentation
GridPoint() [1/3]
template<typename Integer = int> DGtal::detail::GridPoint< Integer >::GridPoint () default
Default constructor.
Referenced by DGtal::detail::GridPoint< Integer >::getOnSameGrid().
GridPoint() [2/3]
template<typename Integer = int> DGtal::detail::GridPoint< Integer >::GridPoint (std::pair< Integer, Integer > const & aDir, int aK) inline
Constructs a grid point from a couple of coordinates and the index of the point used as origin.
Parameters
aDir a pair of nonnegative integers.
aK an index in {0,1,2}.
Definition at line 258 of file PlaneProbingEstimatorHelper.h.
 : myDir(aDir), myK(aK) {}
GridPoint() [3/3]
template<typename Integer = int> DGtal::detail::GridPoint< Integer >::GridPoint (Integer aX, Integer aY, int aK) inline
Constructs a grid point from a couple of coordinates and the index of the point used as origin.
Parameters
aX first coordinate.
aY second coordinate.
aK an index in {0,1,2}.
Definition at line 268 of file PlaneProbingEstimatorHelper.h.
 : myDir(std::make_pair(aX,aY)), myK(aK) {}
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename Integer = int> DGtal::detail::GridPoint< Integer >::BOOST_CONCEPT_ASSERT ((concepts::CInteger< Integer >)) private
direction()
template<typename Integer = int> std::pair<Integer,Integer> DGtal::detail::GridPoint< Integer >::direction () const inline
Returns the couple of coordinates, i.e., the direction going from the origin to the grid point.
Returns
the direction.
Definition at line 277 of file PlaneProbingEstimatorHelper.h.
{
           return myDir;
         }
References DGtal::detail::GridPoint< Integer >::myDir.
Referenced by DGtal::detail::operator<<().
directionVector()
template<typename Integer = int> template<typename Vector > Vector DGtal::detail::GridPoint< Integer >::directionVector (std::array< Vector, 3 > const & aM) const inline
Returns the vector going from the base point to the geometric realization of this object.
Parameters
aM an array of three vectors.
Template Parameters
Vector a type for vectors.
Returns
the computed vector.
Definition at line 299 of file PlaneProbingEstimatorHelper.h.
{
           return aM[(myK+1)%3]*myDir.first + aM[(myK+2)%3]*myDir.second;
         }
References DGtal::detail::GridPoint< Integer >::myDir, and DGtal::detail::GridPoint< Integer >::myK.
Referenced by DGtal::detail::GridPoint< Integer >::relativePoint().
getOnSameGrid()
template<typename Integer = int> GridPoint DGtal::detail::GridPoint< Integer >::getOnSameGrid (const std::pair< Integer, Integer > & aDir) const inline
Returns a grid point given a couple of coordinates.
Parameters
aDir a couple of coordinates.
Returns
the resulting grid point.
Definition at line 342 of file PlaneProbingEstimatorHelper.h.
{
           return GridPoint(aDir,myK);
         }
References DGtal::detail::GridPoint< Integer >::GridPoint(), and DGtal::detail::GridPoint< Integer >::myK.
Referenced by DGtal::detail::GridPointOnProbingRay< Integer >::gridPoint(), DGtal::detail::GridPoint< Integer >::operator*(), and DGtal::detail::GridPoint< Integer >::operator+().
isValid()
template<typename Integer = int> bool DGtal::detail::GridPoint< Integer >::isValid () const inline
Checks whether the representation of the grid point is valid, i.e., the coordinates are nonnegative coordinates, not both equal to zero, and the index is in {0,1,2}.
Returns
'true' if valid, 'false' otherwise.
Definition at line 378 of file PlaneProbingEstimatorHelper.h.
{
           if ( (myDir.first != 0) || (myDir.second != 0) ) { //not both null
             return ( (myDir.first >= 0) && (myDir.second >= 0)
                      && (myK >= 0) && (myK <= 2)
                      );
           } else {
             return false;
           }
         }
References DGtal::detail::GridPoint< Integer >::myDir, and DGtal::detail::GridPoint< Integer >::myK.
k()
template<typename Integer = int> int DGtal::detail::GridPoint< Integer >::k () const inline
Returns the index of the point used as origin.
Returns
the index.
Definition at line 286 of file PlaneProbingEstimatorHelper.h.
                       {
           return myK;
         }
References DGtal::detail::GridPoint< Integer >::myK.
Referenced by DGtal::detail::operator<<().
operator!=()
template<typename Integer = int> bool DGtal::detail::GridPoint< Integer >::operator!= (GridPoint< Integer > const & other) const inline
Tells whether this grid point is different from another or not.
Parameters
other another grid point.
Returns
'true' if different, i.e., not equal, 'false' otherwise.
Definition at line 332 of file PlaneProbingEstimatorHelper.h.
{
           return !(*this == other);
         }
operator*()
template<typename Integer = int> GridPoint DGtal::detail::GridPoint< Integer >::operator* (Integer aValue) const inline
Scales this grid point by a scalar (as if it was vector).
Parameters
aValue a scalar value
Returns
the resulting point.
Definition at line 365 of file PlaneProbingEstimatorHelper.h.
{
           std::pair<Integer,Integer> d = std::make_pair(myDir.first*aValue,
                                                 myDir.second*aValue);
           return getOnSameGrid(d);
         }
References DGtal::detail::GridPoint< Integer >::getOnSameGrid(), and DGtal::detail::GridPoint< Integer >::myDir.
operator+()
template<typename Integer = int> GridPoint DGtal::detail::GridPoint< Integer >::operator+ (const GridPoint< Integer > & other) const inline
Adds a grid point to this one (as if they were vectors).
Parameters
other another grid point.
Returns
the resulting point.
Definition at line 352 of file PlaneProbingEstimatorHelper.h.
{
           ASSERT(myK == other.myK);
           std::pair<Integer,Integer> d = std::make_pair(myDir.first+other.myDir.first,
                                                 myDir.second+other.myDir.second);
           return getOnSameGrid(d);
         }
References DGtal::detail::GridPoint< Integer >::getOnSameGrid(), DGtal::detail::GridPoint< Integer >::myDir, and DGtal::detail::GridPoint< Integer >::myK.
operator==()
template<typename Integer = int> bool DGtal::detail::GridPoint< Integer >::operator== (GridPoint< Integer > const & other) const inline
Tells whether this grid point is equal to another or not. Two grid points are equal iff their members are equal.
Parameters
other another grid point.
Returns
'true' if equal, 'false' otherwise.
Definition at line 322 of file PlaneProbingEstimatorHelper.h.
{
           return (myDir == other.myDir) && (myK == other.myK);
         }
References DGtal::detail::GridPoint< Integer >::myDir, and DGtal::detail::GridPoint< Integer >::myK.
relativePoint()
template<typename Integer = int> template<typename Point > Point DGtal::detail::GridPoint< Integer >::relativePoint (std::array< Point, 3 > const & aM) const inline
Returns the geometric realization of this grid point.
Parameters
aM an array of three points.
Template Parameters
Point a type for points.
Returns
the computed point.
Definition at line 311 of file PlaneProbingEstimatorHelper.h.
{
           return -aM[myK] + directionVector(aM);
         }
References DGtal::detail::GridPoint< Integer >::directionVector(), and DGtal::detail::GridPoint< Integer >::myK.
Referenced by DGtal::detail::GridPointOnProbingRay< Integer >::relativePoint().
Field Documentation
myDir
template<typename Integer = int> std::pair<Integer,Integer> DGtal::detail::GridPoint< Integer >::myDir private
Couple of coordinates giving a direction
Definition at line 390 of file PlaneProbingEstimatorHelper.h.
Referenced by DGtal::detail::GridPoint< Integer >::direction(), DGtal::detail::GridPoint< Integer >::directionVector(), DGtal::detail::GridPoint< Integer >::isValid(), DGtal::detail::GridPoint< Integer >::operator*(), DGtal::detail::GridPoint< Integer >::operator+(), and DGtal::detail::GridPoint< Integer >::operator==().
myK
template<typename Integer = int> int DGtal::detail::GridPoint< Integer >::myK private
Index of a point used as origin
Definition at line 391 of file PlaneProbingEstimatorHelper.h.
Referenced by DGtal::detail::GridPoint< Integer >::directionVector(), DGtal::detail::GridPoint< Integer >::getOnSameGrid(), DGtal::detail::GridPoint< Integer >::isValid(), DGtal::detail::GridPoint< Integer >::k(), DGtal::detail::GridPoint< Integer >::operator+(), DGtal::detail::GridPoint< Integer >::operator==(), and DGtal::detail::GridPoint< Integer >::relativePoint().
The documentation for this class was generated from the following file:
PlaneProbingEstimatorHelper.h