DGtal: DGtal::detail::GridPointOnProbingRay< Integer, Index > Class Template Reference
DGtal::detail::GridPointOnProbingRay< Integer, Index > Class Template Reference
Aim: Represents a grid point along a discrete ray defined on a grid.
#include <DGtal/geometry/helpers/PlaneProbingEstimatorHelper.h>
Public Member Functions
GridPointOnProbingRay ()=default
GridPointOnProbingRay (const GridPoint< Integer, Index > &aGridPoint, const std::pair< Integer, Integer > &aDirection, const Integer &aIdx=0)
bool operator== (GridPointOnProbingRay const &other) const
bool operator!= (GridPointOnProbingRay const &other) const
GridPointOnProbingRay next (const Integer &aInc) const
GridPointOnProbingRay previous (const Integer &aDec) const
Integer index () const
GridPoint< Integer, Index > gridPoint () const
template<typename Point >
Point relativePoint (std::array< Point, 3 > const &aM) const
Private Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CInteger< Integer >))
Private Attributes
GridPoint< Integer, Index > myOrigin
std::pair< Integer, Integer > myDirection
Integer myIdx
Detailed Description
template<typename Integer = int, typename Index = std::size_t>
class DGtal::detail::GridPointOnProbingRay< Integer, Index >
Aim: Represents a grid point along a discrete ray defined on a grid.
Description of template class 'GridPointOnProbingRay'
More precisely, a ray consists of a starting point (represented as an instance of 'GridPoint') and a direction (respresented as a couple of coordinates for the basis of the underlying grid). A grid point along that ray is determined by an index, 0 being the starting point of the ray. The class provides several methods to compare and move points along the ray.
Template Parameters
Integer the integer type, model of concepts::CInteger.
Definition at line 423 of file PlaneProbingEstimatorHelper.h.
Constructor & Destructor Documentation
GridPointOnProbingRay() [1/2]
template<typename Integer = int, typename Index = std::size_t> DGtal::detail::GridPointOnProbingRay< Integer, Index >::GridPointOnProbingRay () default
Default constructor.
Referenced by DGtal::detail::GridPointOnProbingRay< Integer, Index >::next(), and DGtal::detail::GridPointOnProbingRay< Integer, Index >::previous().
GridPointOnProbingRay() [2/2]
template<typename Integer = int, typename Index = std::size_t> DGtal::detail::GridPointOnProbingRay< Integer, Index >::GridPointOnProbingRay (const GridPoint< Integer, Index > & aGridPoint, const std::pair< Integer, Integer > & aDirection, const Integer & aIdx = 0) inline
Constructor.
Parameters
aGridPoint starting point of the ray
aDirection direction of the ray
aIdx index of the grid point along the ray
Definition at line 440 of file PlaneProbingEstimatorHelper.h.
           : myOrigin(aGridPoint), myDirection(aDirection), myIdx(aIdx) {}
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename Integer = int, typename Index = std::size_t> DGtal::detail::GridPointOnProbingRay< Integer, Index >::BOOST_CONCEPT_ASSERT ((concepts::CInteger< Integer >)) private
gridPoint()
template<typename Integer = int, typename Index = std::size_t> GridPoint<Integer, Index> DGtal::detail::GridPointOnProbingRay< Integer, Index >::gridPoint () const inline
Returns
the current grid point as an instance of GridPoint.
Definition at line 503 of file PlaneProbingEstimatorHelper.h.
{
           return myOrigin + myOrigin.getOnSameGrid(myDirection)*myIdx;
         }
References DGtal::detail::GridPoint< Integer, Index >::getOnSameGrid(), DGtal::detail::GridPointOnProbingRay< Integer, Index >::myDirection, DGtal::detail::GridPointOnProbingRay< Integer, Index >::myIdx, and DGtal::detail::GridPointOnProbingRay< Integer, Index >::myOrigin.
Referenced by DGtal::detail::GridPointOnProbingRay< Integer, Index >::relativePoint().
index()
template<typename Integer = int, typename Index = std::size_t> Integer DGtal::detail::GridPointOnProbingRay< Integer, Index >::index () const inline
Returns
index of the current grid point on the ray.
Definition at line 496 of file PlaneProbingEstimatorHelper.h.
{
           return myIdx;
         }
References DGtal::detail::GridPointOnProbingRay< Integer, Index >::myIdx.
next()
template<typename Integer = int, typename Index = std::size_t> GridPointOnProbingRay DGtal::detail::GridPointOnProbingRay< Integer, Index >::next (const Integer & aInc) const inline
Returns a grid point lying after this one along the ray. The distance is given as an input parameter.
Parameters
aInc an increment.
Returns
a new grid point on the same ray, with index, the current index incremented by 'aInc'.
Definition at line 477 of file PlaneProbingEstimatorHelper.h.
{
           return GridPointOnProbingRay(myOrigin, myDirection, myIdx+aInc);
         }
References DGtal::detail::GridPointOnProbingRay< Integer, Index >::GridPointOnProbingRay(), DGtal::detail::GridPointOnProbingRay< Integer, Index >::myDirection, DGtal::detail::GridPointOnProbingRay< Integer, Index >::myIdx, and DGtal::detail::GridPointOnProbingRay< Integer, Index >::myOrigin.
operator!=()
template<typename Integer = int, typename Index = std::size_t> bool DGtal::detail::GridPointOnProbingRay< Integer, Index >::operator!= (GridPointOnProbingRay< Integer, Index > const & other) const inline
Difference test.
Parameters
other another instance of GridPointOnProbingRay
Returns
'true' if different, i.e. not equal, 'false' otherwise
Definition at line 465 of file PlaneProbingEstimatorHelper.h.
{
           return !(*this == other);
         }
operator==()
template<typename Integer = int, typename Index = std::size_t> bool DGtal::detail::GridPointOnProbingRay< Integer, Index >::operator== (GridPointOnProbingRay< Integer, Index > const & other) const inline
Equality test. The two objects are equal iff the underlying rays are the same and the indices are the same.
Parameters
other another instance of GridPointOnProbingRay
Returns
'true' if equal, 'false' otherwise
Definition at line 453 of file PlaneProbingEstimatorHelper.h.
{
           return ( (myOrigin == other.myOrigin) &&
                    (myDirection == other.myDirection) &&
                    (myIdx == other.myIdx) );
         }
References DGtal::detail::GridPointOnProbingRay< Integer, Index >::myDirection, DGtal::detail::GridPointOnProbingRay< Integer, Index >::myIdx, and DGtal::detail::GridPointOnProbingRay< Integer, Index >::myOrigin.
previous()
template<typename Integer = int, typename Index = std::size_t> GridPointOnProbingRay DGtal::detail::GridPointOnProbingRay< Integer, Index >::previous (const Integer & aDec) const inline
Returns a grid point lying before this one along the ray. The distance is given as an input parameter.
Parameters
aDec a decrement.
Returns
a new grid point on the same ray, with index, the current index decremented by 'aDec'.
Definition at line 489 of file PlaneProbingEstimatorHelper.h.
{
           return GridPointOnProbingRay(myOrigin, myDirection, myIdx-aDec);
         }
References DGtal::detail::GridPointOnProbingRay< Integer, Index >::GridPointOnProbingRay(), DGtal::detail::GridPointOnProbingRay< Integer, Index >::myDirection, DGtal::detail::GridPointOnProbingRay< Integer, Index >::myIdx, and DGtal::detail::GridPointOnProbingRay< Integer, Index >::myOrigin.
relativePoint()
template<typename Integer = int, typename Index = std::size_t> template<typename Point > Point DGtal::detail::GridPointOnProbingRay< Integer, Index >::relativePoint (std::array< Point, 3 > const & aM) const inline
Returns the geometric realization of this grid point.
Parameters
aM an array of three points.
Template Parameters
Point a type for points.
Returns
the computed point.
Definition at line 515 of file PlaneProbingEstimatorHelper.h.
{
           return gridPoint().relativePoint(aM);
         }
References DGtal::detail::GridPointOnProbingRay< Integer, Index >::gridPoint(), and DGtal::detail::GridPoint< Integer, Index >::relativePoint().
Field Documentation
myDirection
template<typename Integer = int, typename Index = std::size_t> std::pair<Integer, Integer> DGtal::detail::GridPointOnProbingRay< Integer, Index >::myDirection private
direction of the ray
Definition at line 522 of file PlaneProbingEstimatorHelper.h.
Referenced by DGtal::detail::GridPointOnProbingRay< Integer, Index >::gridPoint(), DGtal::detail::GridPointOnProbingRay< Integer, Index >::next(), DGtal::detail::GridPointOnProbingRay< Integer, Index >::operator==(), and DGtal::detail::GridPointOnProbingRay< Integer, Index >::previous().
myIdx
template<typename Integer = int, typename Index = std::size_t> Integer DGtal::detail::GridPointOnProbingRay< Integer, Index >::myIdx private
index of the point along the ray
Definition at line 523 of file PlaneProbingEstimatorHelper.h.
Referenced by DGtal::detail::GridPointOnProbingRay< Integer, Index >::gridPoint(), DGtal::detail::GridPointOnProbingRay< Integer, Index >::index(), DGtal::detail::GridPointOnProbingRay< Integer, Index >::next(), DGtal::detail::GridPointOnProbingRay< Integer, Index >::operator==(), and DGtal::detail::GridPointOnProbingRay< Integer, Index >::previous().
myOrigin
template<typename Integer = int, typename Index = std::size_t> GridPoint<Integer, Index> DGtal::detail::GridPointOnProbingRay< Integer, Index >::myOrigin private
starting point of the ray
Definition at line 521 of file PlaneProbingEstimatorHelper.h.
Referenced by DGtal::detail::GridPointOnProbingRay< Integer, Index >::gridPoint(), DGtal::detail::GridPointOnProbingRay< Integer, Index >::next(), DGtal::detail::GridPointOnProbingRay< Integer, Index >::operator==(), and DGtal::detail::GridPointOnProbingRay< Integer, Index >::previous().
The documentation for this class was generated from the following file:
PlaneProbingEstimatorHelper.h